# Chapter 6

# Section 6.3.2: Subsample Analysis

# VAR-BEKK-GARCH model for Period 1 (2007/7 - 2011/9) (Section 6.3.2)

In [1]:
library(xts)
library(BEKKs)
library(MTS)
library(vars)
library(stargazer)
library(tidyverse)

Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric



Attaching package: ‘MTS’


The following object is masked from ‘package:BEKKs’:

    backtest


Loading required package: MASS

Loading required package: strucchange

Loading required package: sandwich

Loading required package: urca

Loading required package: lmtest


Attaching package: ‘vars’


The following object is masked from ‘package:MTS’:

    VAR



Please cite as: 


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer 


── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ───────────────────────────────

# Dataset Preperation

In [2]:
fr_d <- readRDS("fr_d.Rds")
fp_d <- readRDS("fp_d.Rds")
cr_d <- readRDS("cr_d.Rds")
cp_d <- readRDS("cp_d.Rds")
head(cr_d)
head(fr_d)
us_d <- cr_d[,1]
l_d <- cr_d[,2]

                     usc           lc
2007-07-06  0.0033026687  0.005272420
2007-07-09 -0.0108928380 -0.013233541
2007-07-10 -0.0378502241 -0.040784991
2007-07-11  0.0210431058  0.019240172
2007-07-12  0.0057943185  0.004526943
2007-07-13 -0.0009633912 -0.004526943

                  eurusd        gbpusd        chfusd        usdgbp       eurgbp
2007-07-06  2.240547e-03 -0.0004972527 -0.0003044418  0.0007037652  0.002659380
2007-07-09  7.337565e-05  0.0022605055  0.0012172115 -0.0025157246 -0.001993871
2007-07-10  8.584371e-03  0.0057647029  0.0115503355 -0.0056582954  0.002805051
2007-07-11 -7.274844e-05  0.0027838359 -0.0029504763 -0.0026379885 -0.002952903
2007-07-12  3.485969e-03 -0.0009845428  0.0028903495  0.0008124302  0.004573291
2007-07-13 -7.252421e-04  0.0019435396  0.0000000000 -0.0020323145 -0.003391083
                  chfgbp        ghsusd        ghsgbp
2007-07-06  0.0001273483 -0.0033264938 -2.614079e-03
2007-07-09 -0.0009873737  0.0040086898  1.236683e-03
2007-07-10  0.0059364761 -0.0002705906 -5.801912e-03
2007-07-11 -0.0057330414  0.0026887042  4.994937e-05
2007-07-12  0.0037670817  0.0027212691  3.716576e-03
2007-07-13 -0.0020261005 -0.0051426368 -7.210559e-03

In [3]:
head(fr_d)
head(fp_d)

                  eurusd        gbpusd        chfusd        usdgbp       eurgbp
2007-07-06  2.240547e-03 -0.0004972527 -0.0003044418  0.0007037652  0.002659380
2007-07-09  7.337565e-05  0.0022605055  0.0012172115 -0.0025157246 -0.001993871
2007-07-10  8.584371e-03  0.0057647029  0.0115503355 -0.0056582954  0.002805051
2007-07-11 -7.274844e-05  0.0027838359 -0.0029504763 -0.0026379885 -0.002952903
2007-07-12  3.485969e-03 -0.0009845428  0.0028903495  0.0008124302  0.004573291
2007-07-13 -7.252421e-04  0.0019435396  0.0000000000 -0.0020323145 -0.003391083
                  chfgbp        ghsusd        ghsgbp
2007-07-06  0.0001273483 -0.0033264938 -2.614079e-03
2007-07-09 -0.0009873737  0.0040086898  1.236683e-03
2007-07-10  0.0059364761 -0.0002705906 -5.801912e-03
2007-07-11 -0.0057330414  0.0026887042  4.994937e-05
2007-07-12  0.0037670817  0.0027212691  3.716576e-03
2007-07-13 -0.0020261005 -0.0051426368 -7.210559e-03

            eurusd  gbpusd  chfusd  usdgbp  eurgbp   chfgbp   ghsusd    ghsgbp
2007-07-05 1.35975 2.01155 0.82130 0.49715 0.67595 0.408303 1.074838 0.5343465
2007-07-06 1.36280 2.01055 0.82105 0.49750 0.67775 0.408355 1.071268 0.5329515
2007-07-09 1.36290 2.01510 0.82205 0.49625 0.67640 0.407952 1.075571 0.5336110
2007-07-10 1.37465 2.02675 0.83160 0.49345 0.67830 0.410381 1.075280 0.5305240
2007-07-11 1.37455 2.03240 0.82915 0.49215 0.67630 0.408035 1.078175 0.5305505
2007-07-12 1.37935 2.03040 0.83155 0.49255 0.67940 0.409575 1.081113 0.5325260

In [4]:
d <- na.omit(merge(cr_d,fr_d))
colnames(d) <- c("US Cocoa","London Cocoa","EURUSD","GBPUSD","CHFUSD","USDGBP","EURGBP","CHFGBP","GHSUSD","GHSGBP")
head(d)

                US Cocoa London Cocoa        EURUSD        GBPUSD        CHFUSD
2007-07-06  0.0033026687  0.005272420  2.240547e-03 -0.0004972527 -0.0003044418
2007-07-09 -0.0108928380 -0.013233541  7.337565e-05  0.0022605055  0.0012172115
2007-07-10 -0.0378502241 -0.040784991  8.584371e-03  0.0057647029  0.0115503355
2007-07-11  0.0210431058  0.019240172 -7.274844e-05  0.0027838359 -0.0029504763
2007-07-12  0.0057943185  0.004526943  3.485969e-03 -0.0009845428  0.0028903495
2007-07-13 -0.0009633912 -0.004526943 -7.252421e-04  0.0019435396  0.0000000000
                  USDGBP       EURGBP        CHFGBP        GHSUSD        GHSGBP
2007-07-06  0.0007037652  0.002659380  0.0001273483 -0.0033264938 -2.614079e-03
2007-07-09 -0.0025157246 -0.001993871 -0.0009873737  0.0040086898  1.236683e-03
2007-07-10 -0.0056582954  0.002805051  0.0059364761 -0.0002705906 -5.801912e-03
2007-07-11 -0.0026379885 -0.002952903 -0.0057330414  0.0026887042  4.994937e-05
2007-07-12  0.0008124302  0.004573291  0

In [5]:
d_p <- na.omit(merge(cp_d,fp_d))
colnames(d_p) <- c("US Cocoa","London Cocoa","EURUSD","GBPUSD","CHFUSD","USDGBP","EURGBP","CHFGBP","GHSUSD","GHSGBP")
head(d_p)
tail(d_p)
str(d_p)

           US Cocoa London Cocoa  EURUSD  GBPUSD  CHFUSD  USDGBP  EURGBP
2007-07-05     2116         1135 1.35975 2.01155 0.82130 0.49715 0.67595
2007-07-06     2123         1141 1.36280 2.01055 0.82105 0.49750 0.67775
2007-07-09     2100         1126 1.36290 2.01510 0.82205 0.49625 0.67640
2007-07-10     2022         1081 1.37465 2.02675 0.83160 0.49345 0.67830
2007-07-11     2065         1102 1.37455 2.03240 0.82915 0.49215 0.67630
2007-07-12     2077         1107 1.37935 2.03040 0.83155 0.49255 0.67940
             CHFGBP   GHSUSD    GHSGBP
2007-07-05 0.408303 1.074838 0.5343465
2007-07-06 0.408355 1.071268 0.5329515
2007-07-09 0.407952 1.075571 0.5336110
2007-07-10 0.410381 1.075280 0.5305240
2007-07-11 0.408035 1.078175 0.5305505
2007-07-12 0.409575 1.081113 0.5325260

           US Cocoa London Cocoa  EURUSD  GBPUSD  CHFUSD  USDGBP EURGBP  CHFGBP
2024-04-26    10594         8979 1.06940 1.24910 1.09385 0.80055 0.8561 0.87570
2024-04-29     8931         7678 1.07210 1.25630 1.09830 0.79600 0.8534 0.87425
2024-04-30     9283         7929 1.06655 1.24910 1.08765 0.80055 0.8538 0.87070
2024-05-01     8284         7250 1.07110 1.25270 1.09215 0.79830 0.8554 0.87190
2024-05-02     7563         6555 1.07270 1.25340 1.09820 0.79780 0.8555 0.87620
2024-05-03     8145         6887 1.07600 1.25465 1.10425 0.79705 0.8577 0.88010
              GHSUSD    GHSGBP
2024-04-26 0.0735850 0.0589105
2024-04-29 0.0732610 0.0583150
2024-04-30 0.0731535 0.0585630
2024-05-01 0.0729935 0.0582690
2024-05-02 0.0727285 0.0580250
2024-05-03 0.0728340 0.0580515

An xts object on 2007-07-05 / 2024-05-03 containing: 
  Data:    double [4176, 10]
  Columns: US Cocoa, London Cocoa, EURUSD, GBPUSD, CHFUSD ... with 5 more columns
  Index:   Date [4176] (TZ: "UTC")
  xts Attributes:
    $ na.action: 'omit' int [1:216] 38 43 101 102 123 124 125 129 143 163 ...
  ..- attr(*, "index")= num [1:216] 1.19e+09 1.19e+09 1.20e+09 1.20e+09 1.20e+09 ...


# Period 1: Data 2007/7 - 2011/9

In [6]:
d <- d["2007-7/2011-9"]
str(d)
head(d)
tail(d)

An xts object on 2007-07-06 / 2011-09-30 containing: 
  Data:    double [1049, 10]
  Columns: US Cocoa, London Cocoa, EURUSD, GBPUSD, CHFUSD ... with 5 more columns
  Index:   Date [1049] (TZ: "UTC")
  xts Attributes:
    $ na.action       : 'omit' int [1:216] 37 42 100 101 122 123 124 128 142 162 ...
  ..- attr(*, "index")= num [1:216] 1.19e+09 1.19e+09 1.20e+09 1.20e+09 1.20e+09 ...
    $ ret_type        : chr "log"
    $ coredata_content: chr "logReturn"


                US Cocoa London Cocoa        EURUSD        GBPUSD        CHFUSD
2007-07-06  0.0033026687  0.005272420  2.240547e-03 -0.0004972527 -0.0003044418
2007-07-09 -0.0108928380 -0.013233541  7.337565e-05  0.0022605055  0.0012172115
2007-07-10 -0.0378502241 -0.040784991  8.584371e-03  0.0057647029  0.0115503355
2007-07-11  0.0210431058  0.019240172 -7.274844e-05  0.0027838359 -0.0029504763
2007-07-12  0.0057943185  0.004526943  3.485969e-03 -0.0009845428  0.0028903495
2007-07-13 -0.0009633912 -0.004526943 -7.252421e-04  0.0019435396  0.0000000000
                  USDGBP       EURGBP        CHFGBP        GHSUSD        GHSGBP
2007-07-06  0.0007037652  0.002659380  0.0001273483 -0.0033264938 -2.614079e-03
2007-07-09 -0.0025157246 -0.001993871 -0.0009873737  0.0040086898  1.236683e-03
2007-07-10 -0.0056582954  0.002805051  0.0059364761 -0.0002705906 -5.801912e-03
2007-07-11 -0.0026379885 -0.002952903 -0.0057330414  0.0026887042  4.994937e-05
2007-07-12  0.0008124302  0.004573291  0

              US Cocoa London Cocoa       EURUSD       GBPUSD       CHFUSD
2011-09-23 -0.01739818 -0.022397353  0.002819098  0.008342714  0.002539799
2011-09-26  0.01298479  0.006772035  0.003106626  0.006380326  0.004880042
2011-09-27  0.01645075  0.006726483  0.003759403  0.004358981  0.005842713
2011-09-28 -0.02014351 -0.016901811 -0.003611709 -0.003652562 -0.004491362
2011-09-29  0.01103764  0.007923075  0.003758849  0.003236715  0.003235812
2011-09-30 -0.03159527 -0.026272214 -0.015382353 -0.002755352 -0.011870781
                 USDGBP        EURGBP        CHFGBP        GHSUSD       GHSGBP
2011-09-23 -0.008394027 -0.0046255400 -0.0056419176 -0.0094318412 -0.017836194
2011-09-26 -0.005816901 -0.0044170443 -0.0009013486 -0.0004104134 -0.006455727
2011-09-27 -0.005068830 -0.0004025186  0.0008705228  0.0005667548 -0.004261738
2011-09-28  0.004134978  0.0000000000 -0.0004106353  0.0000000000  0.004078864
2011-09-29 -0.003197258  0.0006899328 -0.0004556802 -0.0049640488 -0.008178170
2

# VAR-BEKK Models for the subsample

#### The estimation of the VAR-BEKK model is conducted in two stages, VAR model is the model specification for the mean equation (first stage) and BEKK is the specification for the variance equation (second stage).

## (i) Spillover between US Cocoa and London Cocoa

In [7]:
cr_d <- cr_d["2007-7/2011-9"]
str(cr_d)

An xts object on 2007-07-06 / 2011-09-30 containing: 
  Data:    double [1049, 2]
  Columns: usc, lc
  Index:   Date [1049] (TZ: "UTC")
  xts Attributes:
    $ na.action       : 'omit' int [1:159] 37 42 100 101 122 123 140 160 184 214 ...
  ..- attr(*, "index")= num [1:159] 1.19e+09 1.19e+09 1.20e+09 1.20e+09 1.20e+09 ...
    $ ret_type        : chr "log"
    $ coredata_content: chr "logReturn"


In [8]:
VARselect(cr_d)

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.731155e+01 -1.730841e+01 -1.730374e+01 -1.729952e+01 -1.729371e+01
HQ(n)  -1.730071e+01 -1.729035e+01 -1.727846e+01 -1.726701e+01 -1.725399e+01
SC(n)  -1.728298e+01 -1.726081e+01 -1.723709e+01 -1.721383e+01 -1.718899e+01
FPE(n)  3.031737e-08  3.041259e-08  3.055499e-08  3.068420e-08  3.086283e-08
                   6             7             8             9            10
AIC(n) -1.728852e+01 -1.729191e+01 -1.728968e+01 -1.728789e+01 -1.728404e+01
HQ(n)  -1.724156e+01 -1.723773e+01 -1.722828e+01 -1.721927e+01 -1.720819e+01
SC(n)  -1.716475e+01 -1.714910e+01 -1.712783e+01 -1.710700e+01 -1.708410e+01
FPE(n)  3.102369e-08  3.091874e-08  3.098762e-08  3.104326e-08  3.116331e-08

In [9]:
var_cr<-VAR(cr_d,p = 1,type = "const")
summary(var_cr)
res_cr <- residuals(var_cr)
res_cr <- as.data.frame(res_cr)


VAR Estimation Results:
Endogenous variables: usc, lc 
Deterministic variables: const 
Sample size: 1048 
Log Likelihood: 6106.118 
Roots of the characteristic polynomial:
0.09387 0.009223
Call:
VAR(y = cr_d, p = 1, type = "const")


Estimation results for equation usc: 
usc = usc.l1 + lc.l1 + const 

         Estimate Std. Error t value Pr(>|t|)   
usc.l1 -0.1913250  0.0599077  -3.194  0.00145 **
lc.l1   0.2349088  0.0726108   3.235  0.00125 **
const   0.0001875  0.0006238   0.301  0.76378   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


Residual standard error: 0.02018 on 1045 degrees of freedom
Multiple R-Squared: 0.01054,	Adjusted R-squared: 0.008645 
F-statistic: 5.565 on 2 and 1045 DF,  p-value: 0.003943 


Estimation results for equation lc: 
lc = usc.l1 + lc.l1 + const 

         Estimate Std. Error t value Pr(>|t|)  
usc.l1 -0.0831974  0.0496134  -1.677   0.0939 .
lc.l1   0.1066748  0.0601336   1.774   0.0764 .
const   0.0004335  0.0005166   0.839   0.4

In [10]:
ind_var <- index(cr_d)[-1]
str(ind_var)

 Date[1:1048], format: "2007-07-09" "2007-07-10" "2007-07-11" "2007-07-12" "2007-07-13" ...


In [11]:
res_cr <- xts(res_cr,order.by = ind_var)
str(res_cr)
head(res_cr)

An xts object on 2007-07-09 / 2011-09-30 containing: 
  Data:    double [1048, 2]
  Columns: usc, lc
  Index:   Date [1048] (TZ: "UTC")


                    usc           lc
2007-07-09 -0.011686998 -0.013954682
2007-07-10 -0.037013126 -0.040713042
2007-07-11  0.023194659  0.020008381
2007-07-12  0.005113200  0.003791754
2007-07-13 -0.001105717 -0.004961262
2007-07-16 -0.008993713 -0.009146555

In [12]:
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk_fit <- bekk_fit(spec = bekk_spec,data = res_cr)

In [13]:
bekk_fit$A
bekk_fit$A_t
bekk_fit$G
bekk_fit$G_t

[,1]         [,2]      
[1,] 1.588014e-05 -0.1617740
[2,] 1.654724e-01  0.2621322

[,1]         [,2]     
[1,] 0.0004950053 -6.997709
[2,] 4.6312885724  9.928989

[,1]       [,2]      
[1,]  1.0001579 0.02303504
[2,] -0.0187964 0.95841538

[,1]      [,2]      
[1,] 121.87053   3.345989
[2,]  -1.45236 103.129139

### VAR-BEKK Model Table for US Cocoa - London Cocoa

In [14]:
bekkc <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_cr)$varresult$usc$coefficients["const","Estimate"],summary(var_cr)$varresult$lc$coefficients["const","Estimate"],
                                   summary(var_cr)$varresult$usc$coefficients["usc.l1","Estimate"],summary(var_cr)$varresult$usc$coefficients["lc.l1","Estimate"],
                                   summary(var_cr)$varresult$lc$coefficients["usc.l1","Estimate"],summary(var_cr)$varresult$lc$coefficients["lc.l1","Estimate"],
                                   bekk_fit$A[1,1],bekk_fit$A[1,2],bekk_fit$A[2,1],bekk_fit$A[2,2],bekk_fit$G[1,1],bekk_fit$G[1,2],bekk_fit$G[2,1],bekk_fit$G[2,2]),
                   Std_error = c(summary(var_cr)$varresult$usc$coefficients["const","Std. Error"],summary(var_cr)$varresult$lc$coefficients["const","Std. Error"],
                               summary(var_cr)$varresult$usc$coefficients["usc.l1","Std. Error"],summary(var_cr)$varresult$usc$coefficients["lc.l1","Std. Error"],
                                 summary(var_cr)$varresult$lc$coefficients["usc.l1","Std. Error"],summary(var_cr)$varresult$lc$coefficients["lc.l1","Std. Error"],
                                 bekk_fit$A_sd[1,1],bekk_fit$A_sd[1,2],bekk_fit$A_sd[2,1],bekk_fit$A_sd[2,2],bekk_fit$G_sd[1,1],bekk_fit$G_sd[1,2],bekk_fit$G_sd[2,1],bekk_fit$G_sd[2,2]),
                   T_value = c(summary(var_cr)$varresult$usc$coefficients["const","t value"],summary(var_cr)$varresult$lc$coefficients["const","t value"],
                               summary(var_cr)$varresult$usc$coefficients["usc.l1","t value"],summary(var_cr)$varresult$usc$coefficients["lc.l1","t value"],
                               summary(var_cr)$varresult$lc$coefficients["usc.l1","t value"],summary(var_cr)$varresult$lc$coefficients["lc.l1","t value"],
                               bekk_fit$A_t[1,1],bekk_fit$A_t[1,2],bekk_fit$A_t[2,1],bekk_fit$A_t[2,2],bekk_fit$G_t[1,1],bekk_fit$G_t[1,2],
                                 bekk_fit$G_t[2,1],bekk_fit$G_t[2,2]))

bekkc$Significant_at_5p_level[abs(bekkc$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekkc$Significant_at_5p_level[abs(bekkc$T_value) > 1.96 & abs(bekkc$T_value) < 2.58] <- "Stat significant at 5%"
bekkc$Significant_at_5p_level[abs(bekkc$T_value) > 1.645 & abs(bekkc$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekkc$Significant_at_5p_level[abs(bekkc$T_value) <= 1.645] <- "Not Statistically Significant"
bekkc

Parameters Coefficient   Std_error    T_value      
1  mu10        1.875052e-04 0.0006237624  3.006035e-01
2  mu20        4.334802e-04 0.0005165777  8.391384e-01
3  phi11      -1.913250e-01 0.0599077328 -3.193662e+00
4  phi12       2.349088e-01 0.0726107528  3.235179e+00
5  phi21      -8.319739e-02 0.0496134437 -1.676912e+00
6  phi22       1.066748e-01 0.0601336310  1.773962e+00
7  a11         1.588014e-05 0.0320807540  4.950053e-04
8  a12        -1.617740e-01 0.0231181420 -6.997709e+00
9  a21         1.654724e-01 0.0357292259  4.631289e+00
10 a22         2.621322e-01 0.0264006988  9.928989e+00
11 g11         1.000158e+00 0.0082067253  1.218705e+02
12 g12         2.303504e-02 0.0068843737  3.345989e+00
13 g21        -1.879640e-02 0.0129419703 -1.452360e+00
14 g22         9.584154e-01 0.0092933518  1.031291e+02
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Stat significant at 1%       
4  Stat significant at 1%       
5  Stat significant at 10%      
6  Stat significant at 10%      
7  Not Statistically Significant
8  Stat significant at 1%       
9  Stat significant at 1%       
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Stat significant at 1%       
13 Not Statistically Significant
14 Stat significant at 1%

In [15]:
causality(var_cr,cause = "usc")$Granger
causality(var_cr,cause = "lc")$Granger


	Granger causality H0: usc do not Granger-cause lc

data:  VAR object var_cr
F-Test = 2.812, df1 = 1, df2 = 2090, p-value = 0.09371



	Granger causality H0: lc do not Granger-cause usc

data:  VAR object var_cr
F-Test = 10.466, df1 = 1, df2 = 2090, p-value = 0.001235


## (ii) VAR-BEKK Models for US Cocoa

## (a) US Cocoa - EURUSD

In [16]:
us_d <- na.omit(merge(cr_d[,1],fr_d))
str(us_d)

An xts object on 2007-07-06 / 2011-09-30 containing: 
  Data:    double [1049, 9]
  Columns: usc, eurusd, gbpusd, chfusd, usdgbp ... with 4 more columns
  Index:   Date [1049] (TZ: "UTC")
  xts Attributes:
    $ na.action       : 'omit' int [1:3342] 37 42 100 101 122 123 124 128 142 162 ...
  ..- attr(*, "index")= num [1:3342] 1.19e+09 1.19e+09 1.20e+09 1.20e+09 1.20e+09 ...
    $ ret_type        : chr "log"
    $ coredata_content: chr "logReturn"


In [17]:
bekk1data <- us_d[,c(1:2)]
head(bekk1data)
tail(bekk1data)
VARselect(bekk1data,type = "const")

                     usc        eurusd
2007-07-06  0.0033026687  2.240547e-03
2007-07-09 -0.0108928380  7.337565e-05
2007-07-10 -0.0378502241  8.584371e-03
2007-07-11  0.0210431058 -7.274844e-05
2007-07-12  0.0057943185  3.485969e-03
2007-07-13 -0.0009633912 -7.252421e-04

                   usc       eurusd
2011-09-23 -0.01739818  0.002819098
2011-09-26  0.01298479  0.003106626
2011-09-27  0.01645075  0.003759403
2011-09-28 -0.02014351 -0.003611709
2011-09-29  0.01103764  0.003758849
2011-09-30 -0.03159527 -0.015382353

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.764232e+01 -1.763662e+01 -1.763501e+01 -1.763012e+01 -1.762463e+01
HQ(n)  -1.763148e+01 -1.761856e+01 -1.760973e+01 -1.759761e+01 -1.758490e+01
SC(n)  -1.761375e+01 -1.758901e+01 -1.756837e+01 -1.754443e+01 -1.751990e+01
FPE(n)  2.177906e-08  2.190353e-08  2.193877e-08  2.204643e-08  2.216775e-08
                   6             7             8             9            10
AIC(n) -1.762230e+01 -1.761690e+01 -1.761726e+01 -1.761754e+01 -1.761264e+01
HQ(n)  -1.757535e+01 -1.756272e+01 -1.755586e+01 -1.754892e+01 -1.753680e+01
SC(n)  -1.749853e+01 -1.747409e+01 -1.745541e+01 -1.743665e+01 -1.741271e+01
FPE(n)  2.221949e-08  2.233982e-08  2.233177e-08  2.232549e-08  2.243524e-08

In [18]:
var_bekk1<-VAR(bekk1data,p = 1,type = "const")
res_bekk1 <- residuals(var_bekk1)
res_bekk1 <- as.data.frame(res_bekk1)

In [19]:
summary(var_bekk1)


VAR Estimation Results:
Endogenous variables: usc, eurusd 
Deterministic variables: const 
Sample size: 1048 
Log Likelihood: 6279.888 
Roots of the characteristic polynomial:
0.07821 0.02982
Call:
VAR(y = bekk1data, p = 1, type = "const")


Estimation results for equation usc: 
usc = usc.l1 + eurusd.l1 + const 

            Estimate Std. Error t value Pr(>|t|)    
usc.l1    -0.0727378  0.0323668  -2.247   0.0248 *  
eurusd.l1  0.3901174  0.0850842   4.585 5.09e-06 ***
const      0.0002554  0.0006203   0.412   0.6806    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


Residual standard error: 0.02008 on 1045 degrees of freedom
Multiple R-Squared: 0.02034,	Adjusted R-squared: 0.01846 
F-statistic: 10.85 on 2 and 1045 DF,  p-value: 2.175e-05 


Estimation results for equation eurusd: 
eurusd = usc.l1 + eurusd.l1 + const 

           Estimate Std. Error t value Pr(>|t|)
usc.l1    1.439e-03  1.244e-02   0.116    0.908
eurusd.l1 2.434e-02  3.271e-02   0.744    0.457
co

In [20]:
ind_var1 <- index(bekk1data)[-1]
str(ind_var1)

 Date[1:1048], format: "2007-07-09" "2007-07-10" "2007-07-11" "2007-07-12" "2007-07-13" ...


In [21]:
res_bekk1 <- xts(res_bekk1,order.by = ind_var1)

In [22]:
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk1_fit <- bekk_fit(spec = bekk_spec,data = res_bekk1)

In [23]:
bekk1_fit$A
bekk1_fit$A_t
bekk1_fit$G
bekk1_fit$G_t

[,1]      [,2]       
[1,] 0.2047896 0.003000337
[2,] 0.2225896 0.176604054

[,1]     [,2]    
[1,] 8.423957 0.210060
[2,] 3.267366 6.537797

[,1]       [,2]       
[1,]  0.9020282 0.006663802
[2,] -0.0543896 0.979963429

[,1]      [,2]       
[1,] 32.709882   0.6858352
[2,] -2.452691 209.4718720

### VAR-BEKK Model Table for US Cocoa - EURUSD

In [24]:
bekk1 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk1)$varresult$usc$coefficients["const","Estimate"],summary(var_bekk1)$varresult$eurusd$coefficients["const","Estimate"],
                                   summary(var_bekk1)$varresult$usc$coefficients["usc.l1","Estimate"],summary(var_bekk1)$varresult$usc$coefficients["eurusd.l1","Estimate"],
                                   summary(var_bekk1)$varresult$eurusd$coefficients["usc.l1","Estimate"],summary(var_bekk1)$varresult$eurusd$coefficients["eurusd.l1","Estimate"],
                                   bekk1_fit$A[1,1],bekk1_fit$A[1,2],bekk1_fit$A[2,1],bekk1_fit$A[2,2],bekk1_fit$G[1,1],bekk1_fit$G[1,2],bekk1_fit$G[2,1],bekk1_fit$G[2,2]),
                   Std_error = c(summary(var_bekk1)$varresult$usc$coefficients["const","Std. Error"],summary(var_bekk1)$varresult$eurusd$coefficients["const","Std. Error"],
                                summary(var_bekk1)$varresult$usc$coefficients["usc.l1","Std. Error"],summary(var_bekk1)$varresult$usc$coefficients["eurusd.l1","Std. Error"],
                                 summary(var_bekk1)$varresult$eurusd$coefficients["usc.l1","Std. Error"],summary(var_bekk1)$varresult$eurusd$coefficients["eurusd.l1","Std. Error"],
                                 bekk1_fit$A_sd[1,1],bekk1_fit$A_sd[1,2],bekk1_fit$A_sd[2,1],bekk1_fit$A_sd[2,2],bekk1_fit$G_sd[1,1],bekk1_fit$G_sd[1,2],bekk1_fit$G_sd[2,1],bekk1_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk1)$varresult$usc$coefficients["const","t value"],summary(var_bekk1)$varresult$eurusd$coefficients["const","t value"],
                       summary(var_bekk1)$varresult$usc$coefficients["usc.l1","t value"],summary(var_bekk1)$varresult$usc$coefficients["eurusd.l1","t value"],
                               summary(var_bekk1)$varresult$eurusd$coefficients["usc.l1","t value"],summary(var_bekk1)$varresult$eurusd$coefficients["eurusd.l1","t value"],
                               bekk1_fit$A_t[1,1],bekk1_fit$A_t[1,2],bekk1_fit$A_t[2,1],bekk1_fit$A_t[2,2],bekk1_fit$G_t[1,1],bekk1_fit$G_t[1,2],bekk1_fit$G_t[2,1],bekk1_fit$G_t[2,2]))

bekk1$Significant_at_5p_level[abs(bekk1$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk1$Significant_at_5p_level[abs(bekk1$T_value) > 1.96 & abs(bekk1$T_value) < 2.58] <- "Stat significant at 5%"
bekk1$Significant_at_5p_level[abs(bekk1$T_value) > 1.645 & abs(bekk1$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk1$Significant_at_5p_level[abs(bekk1$T_value) <= 1.645] <- "Not Statistically Significant"
bekk1

Parameters Coefficient   Std_error    T_value     
1  mu10        2.553914e-04 0.0006203057   0.41171852
2  mu20        1.863631e-05 0.0002384939   0.07814165
3  phi11      -7.273777e-02 0.0323667821  -2.24729679
4  phi12       3.901174e-01 0.0850842186   4.58507326
5  phi21       1.438653e-03 0.0124443164   0.11560724
6  phi22       2.434271e-02 0.0327130122   0.74412918
7  a11         2.047896e-01 0.0243103804   8.42395667
8  a12         3.000337e-03 0.0142832358   0.21006001
9  a21         2.225896e-01 0.0681250929   3.26736564
10 a22         1.766041e-01 0.0270127779   6.53779682
11 g11         9.020282e-01 0.0275766253  32.70988230
12 g12         6.663802e-03 0.0097163309   0.68583524
13 g21        -5.438960e-02 0.0221754827  -2.45269077
14 g22         9.799634e-01 0.0046782578 209.47187203
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Stat significant at 5%       
4  Stat significant at 1%       
5  Not Statistically Significant
6  Not Statistically Significant
7  Stat significant at 1%       
8  Not Statistically Significant
9  Stat significant at 1%       
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Not Statistically Significant
13 Stat significant at 5%       
14 Stat significant at 1%

In [25]:
causality(var_bekk1,cause = "usc")$Granger
causality(var_bekk1,cause = "eurusd")$Granger


	Granger causality H0: usc do not Granger-cause eurusd

data:  VAR object var_bekk1
F-Test = 0.013365, df1 = 1, df2 = 2090, p-value = 0.908



	Granger causality H0: eurusd do not Granger-cause usc

data:  VAR object var_bekk1
F-Test = 21.023, df1 = 1, df2 = 2090, p-value = 4.807e-06


## (b) VAR-BEKK: US Cocoa-GBPUSD

In [26]:
bekk2data <- us_d[,c(1,3)]
head(bekk2data)

                     usc        gbpusd
2007-07-06  0.0033026687 -0.0004972527
2007-07-09 -0.0108928380  0.0022605055
2007-07-10 -0.0378502241  0.0057647029
2007-07-11  0.0210431058  0.0027838359
2007-07-12  0.0057943185 -0.0009845428
2007-07-13 -0.0009633912  0.0019435396

In [27]:
VARselect(bekk2data,type = "const")

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.772074e+01 -1.771614e+01 -1.771309e+01 -1.770949e+01 -1.771180e+01
HQ(n)  -1.770990e+01 -1.769808e+01 -1.768781e+01 -1.767698e+01 -1.767207e+01
SC(n)  -1.769217e+01 -1.766854e+01 -1.764645e+01 -1.762380e+01 -1.760708e+01
FPE(n)  2.013643e-08  2.022918e-08  2.029097e-08  2.036419e-08  2.031711e-08
                   6             7             8             9            10
AIC(n) -1.770925e+01 -1.770708e+01 -1.770516e+01 -1.769957e+01 -1.770503e+01
HQ(n)  -1.766230e+01 -1.765290e+01 -1.764376e+01 -1.763095e+01 -1.762918e+01
SC(n)  -1.758548e+01 -1.756427e+01 -1.754331e+01 -1.751868e+01 -1.750509e+01
FPE(n)  2.036901e-08  2.041332e-08  2.045262e-08  2.056727e-08  2.045548e-08

In [28]:
var_bekk2<-VAR(bekk2data,p = 1,type = "const")
res_bekk2 <- residuals(var_bekk2)
res_bekk2 <- as.data.frame(res_bekk2)

In [29]:
summary(var_bekk2)


VAR Estimation Results:
Endogenous variables: usc, gbpusd 
Deterministic variables: const 
Sample size: 1048 
Log Likelihood: 6321.264 
Roots of the characteristic polynomial:
0.04121 0.03365
Call:
VAR(y = bekk2data, p = 1, type = "const")


Estimation results for equation usc: 
usc = usc.l1 + gbpusd.l1 + const 

            Estimate Std. Error t value Pr(>|t|)    
usc.l1    -0.0661593  0.0327138  -2.022 0.043393 *  
gbpusd.l1  0.3284468  0.0890570   3.688 0.000238 ***
const      0.0003234  0.0006227   0.519 0.603602    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


Residual standard error: 0.02015 on 1045 degrees of freedom
Multiple R-Squared: 0.01347,	Adjusted R-squared: 0.01158 
F-statistic: 7.134 on 2 and 1045 DF,  p-value: 0.0008371 


Estimation results for equation gbpusd: 
gbpusd = usc.l1 + gbpusd.l1 + const 

            Estimate Std. Error t value Pr(>|t|)  
usc.l1    -0.0075810  0.0120668  -0.628   0.5300  
gbpusd.l1  0.0585988  0.0328497   1.784   0.

In [30]:
ind_var2 <- index(bekk2data)[-1]
str(ind_var2)

 Date[1:1048], format: "2007-07-09" "2007-07-10" "2007-07-11" "2007-07-12" "2007-07-13" ...


In [31]:
res_bekk2 <- xts(res_bekk2,order.by = ind_var2)

In [32]:
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk2_fit <- bekk_fit(spec = bekk_spec,data = res_bekk2)

In [33]:
bekk2_fit$A
bekk2_fit$A_t

[,1]      [,2]       
[1,] 0.2166136 -0.01206659
[2,] 0.2758726  0.18008490

[,1]     [,2]      
[1,] 8.000065 -0.8584682
[2,] 5.085962  4.9182747

In [34]:
bekk2_fit$G
bekk2_fit$G_t

[,1]        [,2]      
[1,]  0.89764060 0.01933899
[2,] -0.06027656 0.97123753

[,1]      [,2]      
[1,] 36.336145   1.791482
[2,] -2.185385 121.467081

### VAR-BEKK Model Table for US Cocoa - GBPUSD

In [35]:
bekk2 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk2)$varresult$usc$coefficients["const","Estimate"],summary(var_bekk2)$varresult$gbpusd$coefficients["const","Estimate"],
                       summary(var_bekk2)$varresult$usc$coefficients["usc.l1","Estimate"],summary(var_bekk2)$varresult$usc$coefficients["gbpusd.l1","Estimate"],
                                   summary(var_bekk2)$varresult$gbpusd$coefficients["usc.l1","Estimate"],summary(var_bekk2)$varresult$gbpusd$coefficients["gbpusd.l1","Estimate"],
                                   bekk2_fit$A[1,1],bekk2_fit$A[1,2],bekk2_fit$A[2,1],bekk2_fit$A[2,2],bekk2_fit$G[1,1],bekk2_fit$G[1,2],bekk2_fit$G[2,1],bekk2_fit$G[2,2]),
                   Std_error = c(summary(var_bekk2)$varresult$usc$coefficients["const","Std. Error"],summary(var_bekk2)$varresult$gbpusd$coefficients["const","Std. Error"],
                       summary(var_bekk2)$varresult$usc$coefficients["usc.l1","Std. Error"],summary(var_bekk2)$varresult$usc$coefficients["gbpusd.l1","Std. Error"],
                                 summary(var_bekk2)$varresult$gbpusd$coefficients["usc.l1","Std. Error"],summary(var_bekk2)$varresult$gbpusd$coefficients["gbpusd.l1","Std. Error"],
                                 bekk2_fit$A_sd[1,1],bekk2_fit$A_sd[1,2],bekk2_fit$A_sd[2,1],bekk2_fit$A_sd[2,2],bekk2_fit$G_sd[1,1],bekk2_fit$G_sd[1,2],bekk2_fit$G_sd[2,1],bekk2_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk2)$varresult$usc$coefficients["const","t value"],summary(var_bekk2)$varresult$gbpusd$coefficients["const","t value"],
                       summary(var_bekk2)$varresult$usc$coefficients["usc.l1","t value"],summary(var_bekk2)$varresult$usc$coefficients["gbpusd.l1","t value"],
                               summary(var_bekk2)$varresult$gbpusd$coefficients["usc.l1","t value"],summary(var_bekk2)$varresult$gbpusd$coefficients["gbpusd.l1","t value"],
                               bekk2_fit$A_t[1,1],bekk2_fit$A_t[1,2],bekk2_fit$A_t[2,1],bekk2_fit$A_t[2,2],bekk2_fit$G_t[1,1],bekk2_fit$G_t[1,2],bekk2_fit$G_t[2,1],bekk2_fit$G_t[2,2]))

bekk2$Significant_at_5p_level[abs(bekk2$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk2$Significant_at_5p_level[abs(bekk2$T_value) > 1.96 & abs(bekk2$T_value) < 2.58] <- "Stat significant at 5%"
bekk2$Significant_at_5p_level[abs(bekk2$T_value) > 1.645 & abs(bekk2$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk2$Significant_at_5p_level[abs(bekk2$T_value) <= 1.645] <- "Not Statistically Significant"
bekk2

Parameters Coefficient   Std_error    T_value    
1  mu10        0.0003234433 0.0006227426   0.5193852
2  mu20       -0.0001592954 0.0002297055  -0.6934764
3  phi11      -0.0661593197 0.0327137605  -2.0223698
4  phi12       0.3284467681 0.0890570059   3.6880509
5  phi21      -0.0075809821 0.0120668354  -0.6282494
6  phi22       0.0585987803 0.0328496699   1.7838469
7  a11         0.2166136101 0.0270764799   8.0000654
8  a12        -0.0120665870 0.0140559508  -0.8584682
9  a21         0.2758726146 0.0542419752   5.0859618
10 a22         0.1800849049 0.0366154627   4.9182747
11 g11         0.8976406011 0.0247037927  36.3361453
12 g12         0.0193389937 0.0107949694   1.7914820
13 g21        -0.0602765551 0.0275816597  -2.1853854
14 g22         0.9712375326 0.0079958910 121.4670808
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Stat significant at 5%       
4  Stat significant at 1%       
5  Not Statistically Significant
6  Stat significant at 10%      
7  Stat significant at 1%       
8  Not Statistically Significant
9  Stat significant at 1%       
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Stat significant at 10%      
13 Stat significant at 5%       
14 Stat significant at 1%

In [36]:
causality(var_bekk2,cause = "usc")$Granger
causality(var_bekk2,cause = "gbpusd")$Granger


	Granger causality H0: usc do not Granger-cause gbpusd

data:  VAR object var_bekk2
F-Test = 0.3947, df1 = 1, df2 = 2090, p-value = 0.5299



	Granger causality H0: gbpusd do not Granger-cause usc

data:  VAR object var_bekk2
F-Test = 13.602, df1 = 1, df2 = 2090, p-value = 0.0002317


## (c) VAR-BEKK: US Cocoa-CHFUSD

In [37]:
bekk3data <- us_d[,c(1,4)]
head(bekk3data)
tail(bekk3data)

                     usc        chfusd
2007-07-06  0.0033026687 -0.0003044418
2007-07-09 -0.0108928380  0.0012172115
2007-07-10 -0.0378502241  0.0115503355
2007-07-11  0.0210431058 -0.0029504763
2007-07-12  0.0057943185  0.0028903495
2007-07-13 -0.0009633912  0.0000000000

                   usc       chfusd
2011-09-23 -0.01739818  0.002539799
2011-09-26  0.01298479  0.004880042
2011-09-27  0.01645075  0.005842713
2011-09-28 -0.02014351 -0.004491362
2011-09-29  0.01103764  0.003235812
2011-09-30 -0.03159527 -0.011870781

In [38]:
VARselect(bekk3data,type = "const")

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.735801e+01 -1.735232e+01 -1.734964e+01 -1.734245e+01 -1.733744e+01
HQ(n)  -1.734718e+01 -1.733426e+01 -1.732435e+01 -1.730995e+01 -1.729771e+01
SC(n)  -1.732945e+01 -1.730471e+01 -1.728299e+01 -1.725677e+01 -1.723271e+01
FPE(n)  2.894081e-08  2.910617e-08  2.918426e-08  2.939471e-08  2.954242e-08
                   6             7             8             9            10
AIC(n) -1.733431e+01 -1.732832e+01 -1.732481e+01 -1.731947e+01 -1.731502e+01
HQ(n)  -1.728735e+01 -1.727414e+01 -1.726341e+01 -1.725085e+01 -1.723917e+01
SC(n)  -1.721054e+01 -1.718551e+01 -1.716295e+01 -1.713858e+01 -1.711509e+01
FPE(n)  2.963520e-08  2.981317e-08  2.991815e-08  3.007816e-08  3.021252e-08

In [39]:
var_bekk3<-VAR(bekk3data,p = 1,type = "const")
res_bekk3 <- residuals(var_bekk3)
res_bekk3 <- as.data.frame(res_bekk3)

In [40]:
summary(var_bekk3)


VAR Estimation Results:
Endogenous variables: usc, chfusd 
Deterministic variables: const 
Sample size: 1048 
Log Likelihood: 6130.958 
Roots of the characteristic polynomial:
0.0663 0.01549
Call:
VAR(y = bekk3data, p = 1, type = "const")


Estimation results for equation usc: 
usc = usc.l1 + chfusd.l1 + const 

            Estimate Std. Error t value Pr(>|t|)  
usc.l1    -0.0362216  0.0315750  -1.147   0.2516  
chfusd.l1  0.1300245  0.0750164   1.733   0.0833 .
const      0.0002207  0.0006260   0.353   0.7245  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


Residual standard error: 0.02025 on 1045 degrees of freedom
Multiple R-Squared: 0.003494,	Adjusted R-squared: 0.001586 
F-statistic: 1.832 on 2 and 1045 DF,  p-value: 0.1606 


Estimation results for equation chfusd: 
chfusd = usc.l1 + chfusd.l1 + const 

            Estimate Std. Error t value Pr(>|t|)
usc.l1     0.0119630  0.0133051   0.899    0.369
chfusd.l1 -0.0145907  0.0316105  -0.462    0.644
const    

In [41]:
ind_var3 <- index(bekk3data)[-1]
str(ind_var3)

 Date[1:1048], format: "2007-07-09" "2007-07-10" "2007-07-11" "2007-07-12" "2007-07-13" ...


In [42]:
res_bekk3 <- xts(res_bekk3,order.by = ind_var3)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk3_fit <- bekk_fit(spec = bekk_spec,data = res_bekk3)

In [43]:
bekk3_fit$A
bekk3_fit$A_t
bekk3_fit$G
bekk3_fit$G_t

[,1]       [,2]      
[1,]  0.1312116 0.02478097
[2,] -0.1539834 0.23775846

[,1]      [,2]     
[1,]  7.121404  2.843748
[2,] -2.171163 12.636885

[,1]       [,2]        
[1,] 0.98508938 -0.008244219
[2,] 0.08904694  0.952021316

[,1]       [,2]      
[1,] 241.465645  -3.150029
[2,]   3.070449 140.964275

### VAR-BEKK Model Table for US Cocoa - CHFUSD

In [44]:
bekk3 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk3)$varresult$usc$coefficients["const","Estimate"],summary(var_bekk3)$varresult$chfusd$coefficients["const","Estimate"],
                       summary(var_bekk3)$varresult$usc$coefficients["usc.l1","Estimate"],summary(var_bekk3)$varresult$usc$coefficients["chfusd.l1","Estimate"],
                                   summary(var_bekk3)$varresult$chfusd$coefficients["usc.l1","Estimate"],summary(var_bekk3)$varresult$chfusd$coefficients["chfusd.l1","Estimate"],
                                   bekk3_fit$A[1,1],bekk3_fit$A[1,2],bekk3_fit$A[2,1],bekk3_fit$A[2,2],bekk3_fit$G[1,1],bekk3_fit$G[1,2],bekk3_fit$G[2,1],bekk3_fit$G[2,2]),
                   Std_error = c(summary(var_bekk3)$varresult$usc$coefficients["const","Std. Error"],summary(var_bekk3)$varresult$chfusd$coefficients["const","Std. Error"],
                       summary(var_bekk3)$varresult$usc$coefficients["usc.l1","Std. Error"],summary(var_bekk3)$varresult$usc$coefficients["chfusd.l1","Std. Error"],
                                 summary(var_bekk3)$varresult$chfusd$coefficients["usc.l1","Std. Error"],summary(var_bekk3)$varresult$chfusd$coefficients["chfusd.l1","Std. Error"],
                                 bekk3_fit$A_sd[1,1],bekk3_fit$A_sd[1,2],bekk3_fit$A_sd[2,1],bekk3_fit$A_sd[2,2],bekk3_fit$G_sd[1,1],bekk3_fit$G_sd[1,2],bekk3_fit$G_sd[2,1],bekk3_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk3)$varresult$usc$coefficients["const","t value"],summary(var_bekk3)$varresult$chfusd$coefficients["const","t value"],
                       summary(var_bekk3)$varresult$usc$coefficients["usc.l1","t value"],summary(var_bekk3)$varresult$usc$coefficients["chfusd.l1","t value"],
                               summary(var_bekk3)$varresult$chfusd$coefficients["usc.l1","t value"],summary(var_bekk3)$varresult$chfusd$coefficients["chfusd.l1","t value"],
                               bekk3_fit$A_t[1,1],bekk3_fit$A_t[1,2],bekk3_fit$A_t[2,1],bekk3_fit$A_t[2,2],bekk3_fit$G_t[1,1],bekk3_fit$G_t[1,2],bekk3_fit$G_t[2,1],bekk3_fit$G_t[2,2]))

bekk3$Significant_at_5p_level[abs(bekk3$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk3$Significant_at_5p_level[abs(bekk3$T_value) > 1.96 & abs(bekk3$T_value) < 2.58] <- "Stat significant at 5%"
bekk3$Significant_at_5p_level[abs(bekk3$T_value) > 1.645 & abs(bekk3$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk3$Significant_at_5p_level[abs(bekk3$T_value) <= 1.645] <- "Not Statistically Significant"
bekk3

Parameters Coefficient   Std_error    T_value    
1  mu10        0.0002206973 0.0006259521   0.3525785
2  mu20        0.0002876954 0.0002637646   1.0907278
3  phi11      -0.0362215824 0.0315750074  -1.1471599
4  phi12       0.1300244541 0.0750163508   1.7332815
5  phi21       0.0119629977 0.0133051216   0.8991273
6  phi22      -0.0145906609 0.0316104969  -0.4615765
7  a11         0.1312116256 0.0184249667   7.1214037
8  a12         0.0247809691 0.0087141920   2.8437483
9  a21        -0.1539834494 0.0709221183  -2.1711626
10 a22         0.2377584601 0.0188146411  12.6368852
11 g11         0.9850893755 0.0040796254 241.4656451
12 g12        -0.0082442192 0.0026171886  -3.1500287
13 g21         0.0890469400 0.0290012800   3.0704486
14 g22         0.9520213159 0.0067536354 140.9642746
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Not Statistically Significant
4  Stat significant at 10%      
5  Not Statistically Significant
6  Not Statistically Significant
7  Stat significant at 1%       
8  Stat significant at 1%       
9  Stat significant at 5%       
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Stat significant at 1%       
13 Stat significant at 1%       
14 Stat significant at 1%

In [45]:
causality(var_bekk3,cause = "usc")$Granger
causality(var_bekk3,cause = "chfusd")$Granger


	Granger causality H0: usc do not Granger-cause chfusd

data:  VAR object var_bekk3
F-Test = 0.80843, df1 = 1, df2 = 2090, p-value = 0.3687



	Granger causality H0: chfusd do not Granger-cause usc

data:  VAR object var_bekk3
F-Test = 3.0043, df1 = 1, df2 = 2090, p-value = 0.08319


## (d) VAR-BEKK model for US Cocoa - GHSUSD

In [46]:
bekk7data <- na.omit(merge(cr_d[,1],fr_d[,7]))
head(bekk7data)
tail(bekk7data)

                     usc        ghsusd
2007-07-06  0.0033026687 -0.0033264938
2007-07-09 -0.0108928380  0.0040086898
2007-07-10 -0.0378502241 -0.0002705906
2007-07-11  0.0210431058  0.0026887042
2007-07-12  0.0057943185  0.0027212691
2007-07-13 -0.0009633912 -0.0051426368

                   usc        ghsusd
2011-09-23 -0.01739818 -0.0094318412
2011-09-26  0.01298479 -0.0004104134
2011-09-27  0.01645075  0.0005667548
2011-09-28 -0.02014351  0.0000000000
2011-09-29  0.01103764 -0.0049640488
2011-09-30 -0.03159527 -0.0053142702

In [47]:
VARselect(bekk7data,type = "const")

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     2      2      2      2 

$criteria
                   1             2             3             4             5
AIC(n) -1.786316e+01 -1.792601e+01 -1.792038e+01 -1.792412e+01 -1.791841e+01
HQ(n)  -1.785232e+01 -1.790795e+01 -1.789510e+01 -1.789162e+01 -1.787868e+01
SC(n)  -1.783459e+01 -1.787841e+01 -1.785374e+01 -1.783844e+01 -1.781369e+01
FPE(n)  1.746344e-08  1.639953e-08  1.649217e-08  1.643055e-08  1.652466e-08
                   6             7             8             9            10
AIC(n) -1.791297e+01 -1.790885e+01 -1.790701e+01 -1.790330e+01 -1.789936e+01
HQ(n)  -1.786601e+01 -1.785468e+01 -1.784561e+01 -1.783468e+01 -1.782351e+01
SC(n)  -1.778920e+01 -1.776604e+01 -1.774516e+01 -1.772241e+01 -1.769943e+01
FPE(n)  1.661495e-08  1.668345e-08  1.671419e-08  1.677640e-08  1.684268e-08

In [48]:
var_bekk7<-VAR(bekk7data,p = 2,type = "const")
res_bekk7 <- residuals(var_bekk7)
res_bekk7 <- as.data.frame(res_bekk7)

In [49]:
summary(var_bekk7)


VAR Estimation Results:
Endogenous variables: usc, ghsusd 
Deterministic variables: const 
Sample size: 1047 
Log Likelihood: 6426.799 
Roots of the characteristic polynomial:
0.5032 0.5032 0.2361 0.2137
Call:
VAR(y = bekk7data, p = 2, type = "const")


Estimation results for equation usc: 
usc = usc.l1 + ghsusd.l1 + usc.l2 + ghsusd.l2 + const 

            Estimate Std. Error t value Pr(>|t|)
usc.l1    -0.0246993  0.0309699  -0.798    0.425
ghsusd.l1 -0.1398955  0.0968638  -1.444    0.149
usc.l2     0.0436942  0.0309539   1.412    0.158
ghsusd.l2 -0.0892564  0.0969434  -0.921    0.357
const      0.0001561  0.0006301   0.248    0.804


Residual standard error: 0.02026 on 1042 degrees of freedom
Multiple R-Squared: 0.004691,	Adjusted R-squared: 0.0008698 
F-statistic: 1.228 on 4 and 1042 DF,  p-value: 0.2973 


Estimation results for equation ghsusd: 
ghsusd = usc.l1 + ghsusd.l1 + usc.l2 + ghsusd.l2 + const 

            Estimate Std. Error t value Pr(>|t|)    
usc.l1    -0.0003128  0.

In [50]:
ind_var7 <- index(bekk7data)[-c(1:2)]
str(ind_var7)

 Date[1:1047], format: "2007-07-10" "2007-07-11" "2007-07-12" "2007-07-13" "2007-07-16" ...


In [51]:
res_bekk7 <- xts(res_bekk7,order.by = ind_var7)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk7_fit <- bekk_fit(spec = bekk_spec,data = res_bekk7)

In [52]:
bekk7_fit$A
bekk7_fit$A_t
bekk7_fit$G
bekk7_fit$G_t

[,1]       [,2]      
[1,] 0.17422800 0.01377806
[2,] 0.06760061 0.39084217

[,1]      [,2]     
[1,] 7.0411230  2.031696
[2,] 0.9447338 16.929950

[,1]        [,2]      
[1,]  0.87962614 0.02342983
[2,] -0.03496488 0.91606089

[,1]      [,2]      
[1,] 21.747205   2.551369
[2,] -1.064556 156.781230

### VAR-BEKK Model Table for US Cocoa - GHSUSD

In [53]:
bekk7 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi13","phi14","phi21","phi22","phi23","phi24","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk7)$varresult$usc$coefficients["const","Estimate"],summary(var_bekk7)$varresult$ghsusd$coefficients["const","Estimate"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l1","Estimate"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l1","Estimate"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l2","Estimate"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l2","Estimate"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l1","Estimate"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l1","Estimate"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l2","Estimate"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l2","Estimate"],
                                   bekk7_fit$A[1,1],bekk7_fit$A[1,2],bekk7_fit$A[2,1],bekk7_fit$A[2,2],bekk7_fit$G[1,1],bekk7_fit$G[1,2],bekk7_fit$G[2,1],bekk7_fit$G[2,2]),
                   Std_error = c(summary(var_bekk7)$varresult$usc$coefficients["const","Std. Error"],summary(var_bekk7)$varresult$ghsusd$coefficients["const","Std. Error"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l1","Std. Error"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l1","Std. Error"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l2","Std. Error"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l2","Std. Error"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l1","Std. Error"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l1","Std. Error"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l2","Std. Error"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l2","Std. Error"],
                                   bekk7_fit$A_sd[1,1],bekk7_fit$A_sd[1,2],bekk7_fit$A_sd[2,1],bekk7_fit$A_sd[2,2],bekk7_fit$G_sd[1,1],bekk7_fit$G_sd[1,2],bekk7_fit$G_sd[2,1],bekk7_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk7)$varresult$usc$coefficients["const","t value"],summary(var_bekk7)$varresult$ghsusd$coefficients["const","t value"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l1","t value"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l1","t value"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l2","t value"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l2","t value"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l1","t value"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l1","t value"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l2","t value"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l2","t value"],
                                   bekk7_fit$A_t[1,1],bekk7_fit$A_t[1,2],bekk7_fit$A_t[2,1],bekk7_fit$A_t[2,2],bekk7_fit$G_t[1,1],bekk7_fit$G_t[1,2],bekk7_fit$G_t[2,1],bekk7_fit$G_t[2,2]))

bekk7$Significant_at_5p_level[abs(bekk7$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk7$Significant_at_5p_level[abs(bekk7$T_value) > 1.96 & abs(bekk7$T_value) < 2.58] <- "Stat significant at 5%"
bekk7$Significant_at_5p_level[abs(bekk7$T_value) > 1.645 & abs(bekk7$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk7$Significant_at_5p_level[abs(bekk7$T_value) <= 1.645] <- "Not Statistically Significant"
bekk7

Parameters Coefficient   Std_error    T_value     
1  mu10        0.0001560578 0.0006300652   0.24768519
2  mu20       -0.0007128594 0.0001948386  -3.65871795
3  phi11      -0.0246993155 0.0309699096  -0.79752624
4  phi12      -0.1398955216 0.0968637529  -1.44425048
5  phi13       0.0436941899 0.0309539348   1.41158758
6  phi14      -0.0892563935 0.0969434174  -0.92070608
7  phi21      -0.0003128186 0.0095769979  -0.03266354
8  phi22      -0.4007074723 0.0299537188 -13.37755340
9  phi23      -0.0229001324 0.0095720580  -2.39239383
10 phi24      -0.2455996640 0.0299783538  -8.19256672
11 a11         0.1742279965 0.0247443479   7.04112298
12 a12         0.0137780603 0.0067815549   2.03169633
13 a21         0.0676006104 0.0715551971   0.94473376
14 a22         0.3908421666 0.0230858425  16.92995030
15 g11         0.8796261437 0.0404477793  21.74720489
16 g12         0.0234298277 0.0091832384   2.55136877
17 g21        -0.0349648818 0.0328445648  -1.06455610
18 g22         0.9160608949 0.0058429245 156.78122999
   Significant_at_5p_level      
1  Not Statistically Significant
2  Stat significant at 1%       
3  Not Statistically Significant
4  Not Statistically Significant
5  Not Statistically Significant
6  Not Statistically Significant
7  Not Statistically Significant
8  Stat significant at 1%       
9  Stat significant at 5%       
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Stat significant at 5%       
13 Not Statistically Significant
14 Stat significant at 1%       
15 Stat significant at 1%       
16 Stat significant at 5%       
17 Not Statistically Significant
18 Stat significant at 1%

In [54]:
causality(var_bekk7,cause = "usc")$Granger
causality(var_bekk7,cause = "ghsusd")$Granger


	Granger causality H0: usc do not Granger-cause ghsusd

data:  VAR object var_bekk7
F-Test = 2.8621, df1 = 2, df2 = 2084, p-value = 0.05737



	Granger causality H0: ghsusd do not Granger-cause usc

data:  VAR object var_bekk7
F-Test = 1.1583, df1 = 2, df2 = 2084, p-value = 0.3142


## (iii) VAR-BEKK Models for London Cocoa

In [55]:
l_d <- na.omit(merge(cr_d[,2],fr_d[,c(4:6)]))
str(l_d)
head(l_d)
tail(l_d)

An xts object on 2007-07-06 / 2011-09-30 containing: 
  Data:    double [1049, 4]
  Columns: lc, usdgbp, eurgbp, chfgbp
  Index:   Date [1049] (TZ: "UTC")
  xts Attributes:
    $ na.action       : 'omit' int [1:3342] 37 42 100 101 122 123 124 128 142 162 ...
  ..- attr(*, "index")= num [1:3342] 1.19e+09 1.19e+09 1.20e+09 1.20e+09 1.20e+09 ...
    $ ret_type        : chr "log"
    $ coredata_content: chr "logReturn"


                     lc        usdgbp       eurgbp        chfgbp
2007-07-06  0.005272420  0.0007037652  0.002659380  0.0001273483
2007-07-09 -0.013233541 -0.0025157246 -0.001993871 -0.0009873737
2007-07-10 -0.040784991 -0.0056582954  0.002805051  0.0059364761
2007-07-11  0.019240172 -0.0026379885 -0.002952903 -0.0057330414
2007-07-12  0.004526943  0.0008124302  0.004573291  0.0037670817
2007-07-13 -0.004526943 -0.0020323145 -0.003391083 -0.0020261005

                     lc       usdgbp        eurgbp        chfgbp
2011-09-23 -0.022397353 -0.008394027 -0.0046255400 -0.0056419176
2011-09-26  0.006772035 -0.005816901 -0.0044170443 -0.0009013486
2011-09-27  0.006726483 -0.005068830 -0.0004025186  0.0008705228
2011-09-28 -0.016901811  0.004134978  0.0000000000 -0.0004106353
2011-09-29  0.007923075 -0.003197258  0.0006899328 -0.0004556802
2011-09-30 -0.026272214  0.002418381 -0.0126668167 -0.0090966262

## (a) VAR-BEKK: London Cocoa-USDGBP

In [56]:
bekk4data <- l_d[,c(1,2)]
head(bekk4data)
tail(bekk4data)

                     lc        usdgbp
2007-07-06  0.005272420  0.0007037652
2007-07-09 -0.013233541 -0.0025157246
2007-07-10 -0.040784991 -0.0056582954
2007-07-11  0.019240172 -0.0026379885
2007-07-12  0.004526943  0.0008124302
2007-07-13 -0.004526943 -0.0020323145

                     lc       usdgbp
2011-09-23 -0.022397353 -0.008394027
2011-09-26  0.006772035 -0.005816901
2011-09-27  0.006726483 -0.005068830
2011-09-28 -0.016901811  0.004134978
2011-09-29  0.007923075 -0.003197258
2011-09-30 -0.026272214  0.002418381

In [57]:
VARselect(bekk4data,type = "const")

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.797082e+01 -1.796619e+01 -1.796135e+01 -1.795495e+01 -1.795469e+01
HQ(n)  -1.795999e+01 -1.794813e+01 -1.793606e+01 -1.792244e+01 -1.791496e+01
SC(n)  -1.794226e+01 -1.791859e+01 -1.789470e+01 -1.786926e+01 -1.784996e+01
FPE(n)  1.568092e-08  1.575370e-08  1.583020e-08  1.593187e-08  1.593601e-08
                   6             7             8             9            10
AIC(n) -1.795115e+01 -1.795054e+01 -1.794578e+01 -1.794096e+01 -1.794601e+01
HQ(n)  -1.790420e+01 -1.789636e+01 -1.788438e+01 -1.787234e+01 -1.787016e+01
SC(n)  -1.782738e+01 -1.780773e+01 -1.778393e+01 -1.776007e+01 -1.774607e+01
FPE(n)  1.599245e-08  1.600228e-08  1.607866e-08  1.615635e-08  1.607508e-08

In [58]:
var_bekk4<-VAR(bekk4data,p = 1,type = "const")
res_bekk4 <- residuals(var_bekk4)
res_bekk4 <- as.data.frame(res_bekk4)

In [59]:
summary(var_bekk4)


VAR Estimation Results:
Endogenous variables: lc, usdgbp 
Deterministic variables: const 
Sample size: 1048 
Log Likelihood: 6451.919 
Roots of the characteristic polynomial:
0.05064 0.01865
Call:
VAR(y = bekk4data, p = 1, type = "const")


Estimation results for equation lc: 
lc = lc.l1 + usdgbp.l1 + const 

           Estimate Std. Error t value Pr(>|t|)
lc.l1     0.0204368  0.0309972   0.659    0.510
usdgbp.l1 0.0119853  0.0695077   0.172    0.863
const     0.0004504  0.0005173   0.871    0.384


Residual standard error: 0.01673 on 1045 degrees of freedom
Multiple R-Squared: 0.0004351,	Adjusted R-squared: -0.001478 
F-statistic: 0.2275 on 2 and 1045 DF,  p-value: 0.7966 


Estimation results for equation usdgbp: 
usdgbp = lc.l1 + usdgbp.l1 + const 

           Estimate Std. Error t value Pr(>|t|)
lc.l1     0.0045102  0.0137936   0.327    0.744
usdgbp.l1 0.0488479  0.0309307   1.579    0.115
const     0.0001626  0.0002302   0.706    0.480


Residual standard error: 0.007447 on 1045 

In [60]:
ind_var4 <- index(bekk4data)[-1]
str(ind_var4)

 Date[1:1048], format: "2007-07-09" "2007-07-10" "2007-07-11" "2007-07-12" "2007-07-13" ...


In [61]:
res_bekk4 <- xts(res_bekk4,order.by = ind_var4)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk4_fit <- bekk_fit(spec = bekk_spec,data = res_bekk4)

In [62]:
bekk4_fit$A
bekk4_fit$A_t
bekk4_fit$G
bekk4_fit$G_t

[,1]      [,2]       
[1,] 0.1506586 -0.01197994
[2,] 0.1247712  0.21502093

[,1]     [,2]     
[1,] 9.314731 -1.148244
[2,] 2.749649  8.347270

[,1]        [,2]       
[1,]  0.98096365 0.004287268
[2,] -0.04368706 0.971184240

[,1]       [,2]      
[1,] 221.296501   1.303889
[2,]  -3.261958 130.352124

### VAR-BEKK Model Table for London Cocoa - USDGBP

In [63]:
bekk4 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk4)$varresult$lc$coefficients["const","Estimate"],summary(var_bekk4)$varresult$usdgbp$coefficients["const","Estimate"],
                                   summary(var_bekk4)$varresult$lc$coefficients["lc.l1","Estimate"],summary(var_bekk4)$varresult$lc$coefficients["usdgbp.l1","Estimate"],
                                   summary(var_bekk4)$varresult$usdgbp$coefficients["lc.l1","Estimate"],summary(var_bekk4)$varresult$usdgbp$coefficients["usdgbp.l1","Estimate"],
                                   bekk4_fit$A[1,1],bekk4_fit$A[1,2],bekk4_fit$A[2,1],bekk4_fit$A[2,2],bekk4_fit$G[1,1],bekk4_fit$G[1,2],bekk4_fit$G[2,1],bekk4_fit$G[2,2]),
                   Std_error = c(summary(var_bekk4)$varresult$lc$coefficients["const","Std. Error"],summary(var_bekk4)$varresult$usdgbp$coefficients["const","Std. Error"],
                                   summary(var_bekk4)$varresult$lc$coefficients["lc.l1","Std. Error"],summary(var_bekk4)$varresult$lc$coefficients["usdgbp.l1","Std. Error"],
                                   summary(var_bekk4)$varresult$usdgbp$coefficients["lc.l1","Std. Error"],summary(var_bekk4)$varresult$usdgbp$coefficients["usdgbp.l1","Std. Error"],
                                   bekk4_fit$A_sd[1,1],bekk4_fit$A_sd[1,2],bekk4_fit$A_sd[2,1],bekk4_fit$A_sd[2,2],bekk4_fit$G_sd[1,1],bekk4_fit$G_sd[1,2],bekk4_fit$G_sd[2,1],bekk4_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk4)$varresult$lc$coefficients["const","t value"],summary(var_bekk4)$varresult$usdgbp$coefficients["const","t value"],
                                   summary(var_bekk4)$varresult$lc$coefficients["lc.l1","t value"],summary(var_bekk4)$varresult$lc$coefficients["usdgbp.l1","t value"],
                                   summary(var_bekk4)$varresult$usdgbp$coefficients["lc.l1","t value"],summary(var_bekk4)$varresult$usdgbp$coefficients["usdgbp.l1","t value"],
                                   bekk4_fit$A_t[1,1],bekk4_fit$A_t[1,2],bekk4_fit$A_t[2,1],bekk4_fit$A_t[2,2],bekk4_fit$G_t[1,1],bekk4_fit$G_t[1,2],bekk4_fit$G_t[2,1],bekk4_fit$G_t[2,2]))

bekk4$Significant_at_5p_level[abs(bekk4$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk4$Significant_at_5p_level[abs(bekk4$T_value) > 1.96 & abs(bekk4$T_value) < 2.58] <- "Stat significant at 5%"
bekk4$Significant_at_5p_level[abs(bekk4$T_value) > 1.645 & abs(bekk4$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk4$Significant_at_5p_level[abs(bekk4$T_value) <= 1.645] <- "Not Statistically Significant"
bekk4

Parameters Coefficient   Std_error    T_value    
1  mu10        0.0004504054 0.0005172933   0.8706963
2  mu20        0.0001626113 0.0002301935   0.7064115
3  phi11       0.0204367884 0.0309971784   0.6593112
4  phi12       0.0119852635 0.0695077075   0.1724307
5  phi21       0.0045102190 0.0137936209   0.3269786
6  phi22       0.0488478839 0.0309306530   1.5792710
7  a11         0.1506586105 0.0161742305   9.3147313
8  a12        -0.0119799417 0.0104332751  -1.1482436
9  a21         0.1247711876 0.0453771261   2.7496494
10 a22         0.2150209297 0.0257594314   8.3472700
11 g11         0.9809636452 0.0044328023 221.2965014
12 g12         0.0042872683 0.0032880622   1.3038891
13 g21        -0.0436870605 0.0133928929  -3.2619585
14 g22         0.9711842401 0.0074504673 130.3521235
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Not Statistically Significant
4  Not Statistically Significant
5  Not Statistically Significant
6  Not Statistically Significant
7  Stat significant at 1%       
8  Not Statistically Significant
9  Stat significant at 1%       
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Not Statistically Significant
13 Stat significant at 1%       
14 Stat significant at 1%

In [64]:
causality(var_bekk4,cause = "lc")$Granger
causality(var_bekk4,cause = "usdgbp")$Granger


	Granger causality H0: lc do not Granger-cause usdgbp

data:  VAR object var_bekk4
F-Test = 0.10692, df1 = 1, df2 = 2090, p-value = 0.7437



	Granger causality H0: usdgbp do not Granger-cause lc

data:  VAR object var_bekk4
F-Test = 0.029732, df1 = 1, df2 = 2090, p-value = 0.8631


## (b) VAR-BEKK: London Cocoa-EURGBP

In [65]:
bekk5data <- l_d[,c(1,3)]
head(bekk5data)

                     lc       eurgbp
2007-07-06  0.005272420  0.002659380
2007-07-09 -0.013233541 -0.001993871
2007-07-10 -0.040784991  0.002805051
2007-07-11  0.019240172 -0.002952903
2007-07-12  0.004526943  0.004573291
2007-07-13 -0.004526943 -0.003391083

In [66]:
VARselect(bekk5data,type = "const")

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.825475e+01 -1.825316e+01 -1.824960e+01 -1.824643e+01 -1.823900e+01
HQ(n)  -1.824391e+01 -1.823510e+01 -1.822431e+01 -1.821393e+01 -1.819927e+01
SC(n)  -1.822619e+01 -1.820556e+01 -1.818295e+01 -1.816074e+01 -1.813427e+01
FPE(n)  1.180492e-08  1.182369e-08  1.186591e-08  1.190353e-08  1.199239e-08
                   6             7             8             9            10
AIC(n) -1.823981e+01 -1.823737e+01 -1.823129e+01 -1.823430e+01 -1.822849e+01
HQ(n)  -1.819285e+01 -1.818319e+01 -1.816989e+01 -1.816568e+01 -1.815265e+01
SC(n)  -1.811604e+01 -1.809456e+01 -1.806944e+01 -1.805341e+01 -1.802856e+01
FPE(n)  1.198268e-08  1.201195e-08  1.208515e-08  1.204887e-08  1.211910e-08

In [67]:
var_bekk5<-VAR(bekk5data,p = 1,type = "const")
res_bekk5 <- residuals(var_bekk5)
res_bekk5 <- as.data.frame(res_bekk5)

In [68]:
summary(var_bekk5)


VAR Estimation Results:
Endogenous variables: lc, eurgbp 
Deterministic variables: const 
Sample size: 1048 
Log Likelihood: 6600.438 
Roots of the characteristic polynomial:
0.08353 0.01067
Call:
VAR(y = bekk5data, p = 1, type = "const")


Estimation results for equation lc: 
lc = lc.l1 + eurgbp.l1 + const 

           Estimate Std. Error t value Pr(>|t|)  
lc.l1     0.0120302  0.0310939   0.387   0.6989  
eurgbp.l1 0.1821257  0.0797708   2.283   0.0226 *
const     0.0004179  0.0005161   0.810   0.4183  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


Residual standard error: 0.01669 on 1045 degrees of freedom
Multiple R-Squared: 0.005368,	Adjusted R-squared: 0.003464 
F-statistic:  2.82 on 2 and 1045 DF,  p-value: 0.06006 


Estimation results for equation eurgbp: 
eurgbp = lc.l1 + eurgbp.l1 + const 

           Estimate Std. Error t value Pr(>|t|)  
lc.l1     0.0089112  0.0121327   0.734   0.4628  
eurgbp.l1 0.0608307  0.0311261   1.954   0.0509 .
const     0.0

In [69]:
ind_var5 <- index(bekk5data)[-1]
str(ind_var5)

 Date[1:1048], format: "2007-07-09" "2007-07-10" "2007-07-11" "2007-07-12" "2007-07-13" ...


In [70]:
res_bekk5 <- xts(res_bekk5,order.by = ind_var5)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk5_fit <- bekk_fit(spec = bekk_spec,data = res_bekk5)

In [71]:
bekk5_fit$A
bekk5_fit$A_t
bekk5_fit$G
bekk5_fit$G_t

[,1]      [,2]       
[1,] 0.2474365 -0.03452528
[2,] 0.1418848  0.22582982

[,1]     [,2]     
[1,] 9.162987 -2.736205
[2,] 1.755250  8.116690

[,1]        [,2]      
[1,]  0.89590950 0.01868497
[2,] -0.03807764 0.96702481

[,1]      [,2]      
[1,] 34.429514   1.719434
[2,] -1.289812 105.482591

### VAR-BEKK Model Table for London Cocoa-EURGBP

In [72]:
bekk5 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk5)$varresult$lc$coefficients["const","Estimate"],summary(var_bekk5)$varresult$eurgbp$coefficients["const","Estimate"],
                                   summary(var_bekk5)$varresult$lc$coefficients["lc.l1","Estimate"],summary(var_bekk5)$varresult$lc$coefficients["eurgbp.l1","Estimate"],
                                   summary(var_bekk5)$varresult$eurgbp$coefficients["lc.l1","Estimate"],summary(var_bekk5)$varresult$eurgbp$coefficients["eurgbp.l1","Estimate"],
                                   bekk5_fit$A[1,1],bekk5_fit$A[1,2],bekk5_fit$A[2,1],bekk5_fit$A[2,2],bekk5_fit$G[1,1],bekk5_fit$G[1,2],bekk5_fit$G[2,1],bekk5_fit$G[2,2]),
                   Std_error = c(summary(var_bekk5)$varresult$lc$coefficients["const","Std. Error"],summary(var_bekk5)$varresult$eurgbp$coefficients["const","Std. Error"],
                                   summary(var_bekk5)$varresult$lc$coefficients["lc.l1","Std. Error"],summary(var_bekk5)$varresult$lc$coefficients["eurgbp.l1","Std. Error"],
                                   summary(var_bekk5)$varresult$eurgbp$coefficients["lc.l1","Std. Error"],summary(var_bekk5)$varresult$eurgbp$coefficients["eurgbp.l1","Std. Error"],
                                   bekk5_fit$A_sd[1,1],bekk5_fit$A_sd[1,2],bekk5_fit$A_sd[2,1],bekk5_fit$A_sd[2,2],bekk5_fit$G_sd[1,1],bekk5_fit$G_sd[1,2],bekk5_fit$G_sd[2,1],bekk5_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk5)$varresult$lc$coefficients["const","t value"],summary(var_bekk5)$varresult$eurgbp$coefficients["const","t value"],
                                   summary(var_bekk5)$varresult$lc$coefficients["lc.l1","t value"],summary(var_bekk5)$varresult$lc$coefficients["eurgbp.l1","t value"],
                                   summary(var_bekk5)$varresult$eurgbp$coefficients["lc.l1","t value"],summary(var_bekk5)$varresult$eurgbp$coefficients["eurgbp.l1","t value"],
                                   bekk5_fit$A_t[1,1],bekk5_fit$A_t[1,2],bekk5_fit$A_t[2,1],bekk5_fit$A_t[2,2],bekk5_fit$G_t[1,1],bekk5_fit$G_t[1,2],bekk5_fit$G_t[2,1],bekk5_fit$G_t[2,2]))

bekk5$Significant_at_5p_level[abs(bekk5$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk5$Significant_at_5p_level[abs(bekk5$T_value) > 1.96 & abs(bekk5$T_value) < 2.58] <- "Stat significant at 5%"
bekk5$Significant_at_5p_level[abs(bekk5$T_value) > 1.645 & abs(bekk5$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk5$Significant_at_5p_level[abs(bekk5$T_value) <= 1.645] <- "Not Statistically Significant"
bekk5

Parameters Coefficient   Std_error    T_value    
1  mu10        0.0004178811 0.0005160854   0.8097132
2  mu20        0.0001806640 0.0002013737   0.8971575
3  phi11       0.0120302248 0.0310939477   0.3868992
4  phi12       0.1821256857 0.0797707815   2.2831127
5  phi21       0.0089112209 0.0121326918   0.7344801
6  phi22       0.0608307014 0.0311261314   1.9543290
7  a11         0.2474364737 0.0270039107   9.1629867
8  a12        -0.0345252811 0.0126179456  -2.7362046
9  a21         0.1418848309 0.0808345244   1.7552504
10 a22         0.2258298203 0.0278228967   8.1166897
11 g11         0.8959094951 0.0260215548  34.4295143
12 g12         0.0186849661 0.0108669274   1.7194342
13 g21        -0.0380776406 0.0295218483  -1.2898122
14 g22         0.9670248087 0.0091676247 105.4825907
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Not Statistically Significant
4  Stat significant at 5%       
5  Not Statistically Significant
6  Stat significant at 10%      
7  Stat significant at 1%       
8  Stat significant at 1%       
9  Stat significant at 10%      
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Stat significant at 10%      
13 Not Statistically Significant
14 Stat significant at 1%

In [73]:
causality(var_bekk5,cause = "lc")$Granger
causality(var_bekk5,cause = "eurgbp")$Granger


	Granger causality H0: lc do not Granger-cause eurgbp

data:  VAR object var_bekk5
F-Test = 0.53946, df1 = 1, df2 = 2090, p-value = 0.4627



	Granger causality H0: eurgbp do not Granger-cause lc

data:  VAR object var_bekk5
F-Test = 5.2126, df1 = 1, df2 = 2090, p-value = 0.02252


## (c) VAR-BEKK: London Cocoa-CHFGBP

In [74]:
bekk6data <- l_d[,c(1,4)]
head(bekk6data)
tail(bekk6data)

                     lc        chfgbp
2007-07-06  0.005272420  0.0001273483
2007-07-09 -0.013233541 -0.0009873737
2007-07-10 -0.040784991  0.0059364761
2007-07-11  0.019240172 -0.0057330414
2007-07-12  0.004526943  0.0037670817
2007-07-13 -0.004526943 -0.0020261005

                     lc        chfgbp
2011-09-23 -0.022397353 -0.0056419176
2011-09-26  0.006772035 -0.0009013486
2011-09-27  0.006726483  0.0008705228
2011-09-28 -0.016901811 -0.0004106353
2011-09-29  0.007923075 -0.0004556802
2011-09-30 -0.026272214 -0.0090966262

In [75]:
VARselect(bekk6data,type = "const")

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.760332e+01 -1.759807e+01 -1.759577e+01 -1.758893e+01 -1.758279e+01
HQ(n)  -1.759248e+01 -1.758001e+01 -1.757049e+01 -1.755642e+01 -1.754306e+01
SC(n)  -1.757475e+01 -1.755047e+01 -1.752913e+01 -1.750324e+01 -1.747806e+01
FPE(n)  2.264526e-08  2.276438e-08  2.281673e-08  2.297349e-08  2.311497e-08
                   6             7             8             9            10
AIC(n) -1.757816e+01 -1.757509e+01 -1.756959e+01 -1.756711e+01 -1.756666e+01
HQ(n)  -1.753120e+01 -1.752091e+01 -1.750819e+01 -1.749849e+01 -1.749081e+01
SC(n)  -1.745439e+01 -1.743228e+01 -1.740774e+01 -1.738622e+01 -1.736672e+01
FPE(n)  2.322223e-08  2.329361e-08  2.342214e-08  2.348025e-08  2.349101e-08

In [76]:
var_bekk6<-VAR(bekk6data,p = 1,type = "const")
res_bekk6 <- residuals(var_bekk6)
res_bekk6 <- as.data.frame(res_bekk6)

In [77]:
summary(var_bekk6)


VAR Estimation Results:
Endogenous variables: lc, chfgbp 
Deterministic variables: const 
Sample size: 1048 
Log Likelihood: 6259.506 
Roots of the characteristic polynomial:
0.0505 0.01526
Call:
VAR(y = bekk6data, p = 1, type = "const")


Estimation results for equation lc: 
lc = lc.l1 + chfgbp.l1 + const 

           Estimate Std. Error t value Pr(>|t|)
lc.l1     0.0192093  0.0309526   0.621    0.535
chfgbp.l1 0.0712497  0.0578372   1.232    0.218
const     0.0004198  0.0005175   0.811    0.417


Residual standard error: 0.01672 on 1045 degrees of freedom
Multiple R-Squared: 0.001856,	Adjusted R-squared: -5.409e-05 
F-statistic: 0.9717 on 2 and 1045 DF,  p-value: 0.3788 


Estimation results for equation chfgbp: 
chfgbp = lc.l1 + chfgbp.l1 + const 

           Estimate Std. Error t value Pr(>|t|)
lc.l1     0.0151378  0.0165606   0.914    0.361
chfgbp.l1 0.0160296  0.0309448   0.518    0.605
const     0.0004427  0.0002769   1.599    0.110


Residual standard error: 0.008947 on 1045 d

In [78]:
ind_var6 <- index(bekk6data)[-1]
str(ind_var6)

 Date[1:1048], format: "2007-07-09" "2007-07-10" "2007-07-11" "2007-07-12" "2007-07-13" ...


In [79]:
res_bekk6 <- xts(res_bekk6,order.by = ind_var6)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk6_fit <- bekk_fit(spec = bekk_spec,data = res_bekk6)

In [80]:
bekk6_fit$A
bekk6_fit$A_t

[,1]      [,2]       
[1,] 0.3150766 -0.02513636
[2,] 0.1619242  0.31016499

[,1]     [,2]     
[1,] 6.865311 -1.139447
[2,] 2.003291 11.323514

In [81]:
bekk6_fit$G
bekk6_fit$G_t

[,1]        [,2]       
[1,]  0.64332279 -0.05486202
[2,] -0.02453976  0.94284744

[,1]       [,2]     
[1,]  7.6091071 -1.746292
[2,] -0.5520533 96.390180

### VAR-BEKK Model Table for London Cocoa-CHFGBP

In [82]:
bekk6 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk6)$varresult$lc$coefficients["const","Estimate"],summary(var_bekk6)$varresult$chfgbp$coefficients["const","Estimate"],
                                   summary(var_bekk6)$varresult$lc$coefficients["lc.l1","Estimate"],summary(var_bekk6)$varresult$lc$coefficients["chfgbp.l1","Estimate"],
                                   summary(var_bekk6)$varresult$chfgbp$coefficients["lc.l1","Estimate"],summary(var_bekk6)$varresult$chfgbp$coefficients["chfgbp.l1","Estimate"],
                                   bekk6_fit$A[1,1],bekk6_fit$A[1,2],bekk6_fit$A[2,1],bekk6_fit$A[2,2],bekk6_fit$G[1,1],bekk6_fit$G[1,2],bekk6_fit$G[2,1],bekk6_fit$G[2,2]),
                   Std_error = c(summary(var_bekk6)$varresult$lc$coefficients["const","Std. Error"],summary(var_bekk6)$varresult$chfgbp$coefficients["const","Std. Error"],
                                   summary(var_bekk6)$varresult$lc$coefficients["lc.l1","Std. Error"],summary(var_bekk6)$varresult$lc$coefficients["chfgbp.l1","Std. Error"],
                                   summary(var_bekk6)$varresult$chfgbp$coefficients["lc.l1","Std. Error"],summary(var_bekk6)$varresult$chfgbp$coefficients["chfgbp.l1","Std. Error"],
                                   bekk6_fit$A_sd[1,1],bekk6_fit$A_sd[1,2],bekk6_fit$A_sd[2,1],bekk6_fit$A_sd[2,2],bekk6_fit$G_sd[1,1],bekk6_fit$G_sd[1,2],bekk6_fit$G_sd[2,1],bekk6_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk6)$varresult$lc$coefficients["const","t value"],summary(var_bekk6)$varresult$chfgbp$coefficients["const","t value"],
                                   summary(var_bekk6)$varresult$lc$coefficients["lc.l1","t value"],summary(var_bekk6)$varresult$lc$coefficients["chfgbp.l1","t value"],
                                   summary(var_bekk6)$varresult$chfgbp$coefficients["lc.l1","t value"],summary(var_bekk6)$varresult$chfgbp$coefficients["chfgbp.l1","t value"],
                                   bekk6_fit$A_t[1,1],bekk6_fit$A_t[1,2],bekk6_fit$A_t[2,1],bekk6_fit$A_t[2,2],bekk6_fit$G_t[1,1],bekk6_fit$G_t[1,2],bekk6_fit$G_t[2,1],bekk6_fit$G_t[2,2]))

bekk6$Significant_at_5p_level[abs(bekk6$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk6$Significant_at_5p_level[abs(bekk6$T_value) > 1.96 & abs(bekk6$T_value) < 2.58] <- "Stat significant at 5%"
bekk6$Significant_at_5p_level[abs(bekk6$T_value) > 1.645 & abs(bekk6$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk6$Significant_at_5p_level[abs(bekk6$T_value) <= 1.645] <- "Not Statistically Significant"
bekk6

Parameters Coefficient   Std_error    T_value   
1  mu10        0.0004198342 0.0005174547  0.8113449
2  mu20        0.0004426845 0.0002768553  1.5989746
3  phi11       0.0192092597 0.0309525649  0.6206032
4  phi12       0.0712496853 0.0578372495  1.2318996
5  phi21       0.0151378133 0.0165606390  0.9140839
6  phi22       0.0160296172 0.0309448283  0.5180063
7  a11         0.3150765591 0.0458939991  6.8653106
8  a12        -0.0251363602 0.0220601367 -1.1394472
9  a21         0.1619242038 0.0808291149  2.0032906
10 a22         0.3101649915 0.0273912320 11.3235137
11 g11         0.6433227914 0.0845464232  7.6091071
12 g12        -0.0548620249 0.0314162864 -1.7462925
13 g21        -0.0245397624 0.0444517953 -0.5520533
14 g22         0.9428474379 0.0097815715 96.3901796
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Not Statistically Significant
4  Not Statistically Significant
5  Not Statistically Significant
6  Not Statistically Significant
7  Stat significant at 1%       
8  Not Statistically Significant
9  Stat significant at 5%       
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Stat significant at 10%      
13 Not Statistically Significant
14 Stat significant at 1%

In [83]:
causality(var_bekk6,cause = "lc")$Granger
causality(var_bekk6,cause = "chfgbp")$Granger


	Granger causality H0: lc do not Granger-cause chfgbp

data:  VAR object var_bekk6
F-Test = 0.83555, df1 = 1, df2 = 2090, p-value = 0.3608



	Granger causality H0: chfgbp do not Granger-cause lc

data:  VAR object var_bekk6
F-Test = 1.5176, df1 = 1, df2 = 2090, p-value = 0.2181


## (d) VAR-BEKK Model for London Cocoa - GHSGBP

In [84]:
bekk8data <- na.omit(merge(cr_d[,2],fr_d[,8]))
head(bekk8data)
tail(bekk8data)

                     lc        ghsgbp
2007-07-06  0.005272420 -2.614079e-03
2007-07-09 -0.013233541  1.236683e-03
2007-07-10 -0.040784991 -5.801912e-03
2007-07-11  0.019240172  4.994937e-05
2007-07-12  0.004526943  3.716576e-03
2007-07-13 -0.004526943 -7.210559e-03

                     lc       ghsgbp
2011-09-23 -0.022397353 -0.017836194
2011-09-26  0.006772035 -0.006455727
2011-09-27  0.006726483 -0.004261738
2011-09-28 -0.016901811  0.004078864
2011-09-29  0.007923075 -0.008178170
2011-09-30 -0.026272214 -0.002884669

In [85]:
VARselect(bekk8data,type = "const")

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     2      1      1      2 

$criteria
                   1             2             3             4             5
AIC(n) -1.736817e+01 -1.737000e+01 -1.736263e+01 -1.736016e+01 -1.736215e+01
HQ(n)  -1.735733e+01 -1.735194e+01 -1.733734e+01 -1.732766e+01 -1.732242e+01
SC(n)  -1.733960e+01 -1.732240e+01 -1.729598e+01 -1.727448e+01 -1.725742e+01
FPE(n)  2.864849e-08  2.859597e-08  2.880762e-08  2.887863e-08  2.882144e-08
                   6             7             8             9            10
AIC(n) -1.735870e+01 -1.735506e+01 -1.735085e+01 -1.734724e+01 -1.734239e+01
HQ(n)  -1.731175e+01 -1.730089e+01 -1.728944e+01 -1.727862e+01 -1.726654e+01
SC(n)  -1.723493e+01 -1.721225e+01 -1.718899e+01 -1.716635e+01 -1.714246e+01
FPE(n)  2.892098e-08  2.902643e-08  2.914917e-08  2.925439e-08  2.939675e-08

In [86]:
var_bekk8<-VAR(bekk8data,p = 2,type = "const")
res_bekk8 <- residuals(var_bekk8)
res_bekk8 <- as.data.frame(res_bekk8)

In [87]:
summary(var_bekk8)


VAR Estimation Results:
Endogenous variables: lc, ghsgbp 
Deterministic variables: const 
Sample size: 1047 
Log Likelihood: 6134.733 
Roots of the characteristic polynomial:
0.2701 0.2701 0.2156 0.1832
Call:
VAR(y = bekk8data, p = 2, type = "const")


Estimation results for equation lc: 
lc = lc.l1 + ghsgbp.l1 + lc.l2 + ghsgbp.l2 + const 

            Estimate Std. Error t value Pr(>|t|)
lc.l1      0.0190423  0.0310035   0.614    0.539
ghsgbp.l1 -0.0269107  0.0514947  -0.523    0.601
lc.l2      0.0442394  0.0309988   1.427    0.154
ghsgbp.l2  0.0165855  0.0515080   0.322    0.748
const      0.0004421  0.0005179   0.854    0.394


Residual standard error: 0.01673 on 1042 degrees of freedom
Multiple R-Squared: 0.002715,	Adjusted R-squared: -0.001114 
F-statistic: 0.7091 on 4 and 1042 DF,  p-value: 0.5858 


Estimation results for equation ghsgbp: 
ghsgbp = lc.l1 + ghsgbp.l1 + lc.l2 + ghsgbp.l2 + const 

            Estimate Std. Error t value Pr(>|t|)    
lc.l1      0.0068224  0.018598

In [88]:
ind_var8 <- index(bekk8data)[-c(1:2)]
str(ind_var8)

 Date[1:1047], format: "2007-07-10" "2007-07-11" "2007-07-12" "2007-07-13" "2007-07-16" ...


In [89]:
res_bekk8 <- xts(res_bekk8,order.by = ind_var8)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk8_fit <- bekk_fit(spec = bekk_spec,data = res_bekk8)

In [90]:
bekk8_fit$A
bekk8_fit$A_t
bekk8_fit$G
bekk8_fit$G_t

[,1]       [,2]       
[1,] 0.09708700 -0.01752225
[2,] 0.08009023  0.24840442

[,1]     [,2]     
[1,] 5.819492 -1.555887
[2,] 2.058909 11.790396

[,1]        [,2]      
[1,]  0.99056985 0.01107886
[2,] -0.03904157 0.96570266

[,1]       [,2]      
[1,] 258.622676   3.211535
[2,]  -4.158166 196.763462

### VAR-BEKK Model Table for London Cocoa - GHSGBP

In [91]:
bekk8 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi13","phi14","phi21","phi22","phi23","phi24","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk8)$varresult$lc$coefficients["const","Estimate"],summary(var_bekk8)$varresult$ghsgbp$coefficients["const","Estimate"],
                                   summary(var_bekk8)$varresult$lc$coefficients["lc.l1","Estimate"],summary(var_bekk8)$varresult$lc$coefficients["ghsgbp.l1","Estimate"],
                                   summary(var_bekk8)$varresult$lc$coefficients["lc.l2","Estimate"],summary(var_bekk8)$varresult$lc$coefficients["ghsgbp.l2","Estimate"],
                                   summary(var_bekk8)$varresult$ghsgbp$coefficients["lc.l1","Estimate"],summary(var_bekk8)$varresult$ghsgbp$coefficients["ghsgbp.l1","Estimate"],
                                   summary(var_bekk8)$varresult$ghsgbp$coefficients["lc.l2","Estimate"],summary(var_bekk8)$varresult$ghsgbp$coefficients["ghsgbp.l2","Estimate"],
                                   bekk8_fit$A[1,1],bekk8_fit$A[1,2],bekk8_fit$A[2,1],bekk8_fit$A[2,2],bekk8_fit$G[1,1],bekk8_fit$G[1,2],bekk8_fit$G[2,1],bekk8_fit$G[2,2]),
                   Std_error = c(summary(var_bekk8)$varresult$lc$coefficients["const","Std. Error"],summary(var_bekk8)$varresult$ghsgbp$coefficients["const","Std. Error"],
                                   summary(var_bekk8)$varresult$lc$coefficients["lc.l1","Std. Error"],summary(var_bekk8)$varresult$lc$coefficients["ghsgbp.l1","Std. Error"],
                                   summary(var_bekk8)$varresult$lc$coefficients["lc.l2","Std. Error"],summary(var_bekk8)$varresult$lc$coefficients["ghsgbp.l2","Std. Error"],
                                   summary(var_bekk8)$varresult$ghsgbp$coefficients["lc.l1","Std. Error"],summary(var_bekk8)$varresult$ghsgbp$coefficients["ghsgbp.l1","Std. Error"],
                                   summary(var_bekk8)$varresult$ghsgbp$coefficients["lc.l2","Std. Error"],summary(var_bekk8)$varresult$ghsgbp$coefficients["ghsgbp.l2","Std. Error"],
                                   bekk8_fit$A_sd[1,1],bekk8_fit$A_sd[1,2],bekk8_fit$A_sd[2,1],bekk8_fit$A_sd[2,2],bekk8_fit$G_sd[1,1],bekk8_fit$G_sd[1,2],bekk8_fit$G_sd[2,1],bekk8_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk8)$varresult$lc$coefficients["const","t value"],summary(var_bekk8)$varresult$ghsgbp$coefficients["const","t value"],
                                   summary(var_bekk8)$varresult$lc$coefficients["lc.l1","t value"],summary(var_bekk8)$varresult$lc$coefficients["ghsgbp.l1","t value"],
                                   summary(var_bekk8)$varresult$lc$coefficients["lc.l2","t value"],summary(var_bekk8)$varresult$lc$coefficients["ghsgbp.l2","t value"],
                                   summary(var_bekk8)$varresult$ghsgbp$coefficients["lc.l1","t value"],summary(var_bekk8)$varresult$ghsgbp$coefficients["ghsgbp.l1","t value"],
                                   summary(var_bekk8)$varresult$ghsgbp$coefficients["lc.l2","t value"],summary(var_bekk8)$varresult$ghsgbp$coefficients["ghsgbp.l2","t value"],
                                   bekk8_fit$A_t[1,1],bekk8_fit$A_t[1,2],bekk8_fit$A_t[2,1],bekk8_fit$A_t[2,2],bekk8_fit$G_t[1,1],bekk8_fit$G_t[1,2],bekk8_fit$G_t[2,1],bekk8_fit$G_t[2,2]))

bekk8$Significant_at_5p_level[abs(bekk8$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk8$Significant_at_5p_level[abs(bekk8$T_value) > 1.96 & abs(bekk8$T_value) < 2.58] <- "Stat significant at 5%"
bekk8$Significant_at_5p_level[abs(bekk8$T_value) > 1.645 & abs(bekk8$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk8$Significant_at_5p_level[abs(bekk8$T_value) <= 1.645] <- "Not Statistically Significant"
bekk8

Parameters Coefficient   Std_error    T_value    
1  mu10        0.0004420629 0.0005179257   0.8535257
2  mu20       -0.0003063797 0.0003106995  -0.9860966
3  phi11       0.0190423020 0.0310035480   0.6141975
4  phi12      -0.0269106816 0.0514947241  -0.5225910
5  phi13       0.0442393752 0.0309988178   1.4271310
6  phi14       0.0165854726 0.0515080134   0.3219979
7  phi21       0.0068223558 0.0185987814   0.3668174
8  phi22      -0.1269590670 0.0308912747  -4.1098682
9  phi23      -0.0273991763 0.0185959438  -1.4733953
10 phi24      -0.0754103044 0.0308992468  -2.4405224
11 a11         0.0970870004 0.0166830725   5.8194916
12 a12        -0.0175222489 0.0112619003  -1.5558874
13 a21         0.0800902270 0.0388993445   2.0589094
14 a22         0.2484044163 0.0210683689  11.7903962
15 g11         0.9905698544 0.0038301740 258.6226761
16 g12         0.0110788551 0.0034497072   3.2115349
17 g21        -0.0390415664 0.0093891318  -4.1581658
18 g22         0.9657026633 0.0049079369 196.7634617
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Not Statistically Significant
4  Not Statistically Significant
5  Not Statistically Significant
6  Not Statistically Significant
7  Not Statistically Significant
8  Stat significant at 1%       
9  Not Statistically Significant
10 Stat significant at 5%       
11 Stat significant at 1%       
12 Not Statistically Significant
13 Stat significant at 5%       
14 Stat significant at 1%       
15 Stat significant at 1%       
16 Stat significant at 1%       
17 Stat significant at 1%       
18 Stat significant at 1%

In [92]:
causality(var_bekk8,cause = "lc")$Granger
causality(var_bekk8,cause = "ghsgbp")$Granger


	Granger causality H0: lc do not Granger-cause ghsgbp

data:  VAR object var_bekk8
F-Test = 1.142, df1 = 2, df2 = 2084, p-value = 0.3194



	Granger causality H0: ghsgbp do not Granger-cause lc

data:  VAR object var_bekk8
F-Test = 0.21156, df1 = 2, df2 = 2084, p-value = 0.8093


# Summary of Period 1 models

In [93]:
bekk_c <- rep(NA,14)
for(i in 1:14){
    bekk_c[i] = paste0(round(bekkc[i,2],4)," (",round(bekkc[i,3],4),")")
}

bekk_1 <- rep(NA,14)
for(i in 1:14){
    bekk_1[i] = paste0(round(bekk1[i,2],4)," (",round(bekk1[i,3],4),")")
}

bekk_2 <- rep(NA,14)
for(i in 1:14){
    bekk_2[i] = paste0(round(bekk2[i,2],4)," (",round(bekk2[i,3],4),")")
}

bekk_3 <- rep(NA,14)
for(i in 1:14){
    bekk_3[i] = paste0(round(bekk3[i,2],4)," (",round(bekk3[i,3],4),")")
}

bekk_4 <- rep(NA,14)
for(i in 1:14){
    bekk_4[i] = paste0(round(bekk4[i,2],4)," (",round(bekk4[i,3],4),")")
}

bekk_5 <- rep(NA,14)
for(i in 1:14){
    bekk_5[i] = paste0(round(bekk5[i,2],4)," (",round(bekk5[i,3],4),")")
}

bekk_6 <- rep(NA,14)
for(i in 1:14){
    bekk_6[i] = paste0(round(bekk6[i,2],4)," (",round(bekk6[i,3],4),")")
}

bekk_7 <- rep(NA,18)
for(i in 1:18){
    bekk_7[i] = paste0(round(bekk7[i,2],4)," (",round(bekk7[i,3],4),")")
}


bekk_8 <- rep(NA,18)
for(i in 1:18){
    bekk_8[i] = paste0(round(bekk8[i,2],4)," (",round(bekk8[i,3],4),")")
}


In [94]:
parameters1 = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22")
parameters2 = c("mu10","mu20","phi11","phi12","phi13","phi14","phi21","phi22","phi23","phi24","a11","a12","a21","a22","g11","g12","g21","g22")

In [95]:
daily_bekk1 <- data.frame("Parameters" = parameters1,"BEKKC" = bekk_c,"BEKK1" = bekk_1,"BEKK2" = bekk_2,"BEKK3" = bekk_3,"BEKK4" = bekk_4,"BEKK5" = bekk_5,
                         "BEKK6" = bekk_6)
daily_bekk2 <- data.frame("Parameters" = parameters2,"BEKK7" = bekk_7,"BEKK8" = bekk_8)

In [96]:
daily_bekk1

Parameters BEKKC            BEKK1            BEKK2           
1  mu10       2e-04 (6e-04)    3e-04 (6e-04)    3e-04 (6e-04)   
2  mu20       4e-04 (5e-04)    0 (2e-04)        -2e-04 (2e-04)  
3  phi11      -0.1913 (0.0599) -0.0727 (0.0324) -0.0662 (0.0327)
4  phi12      0.2349 (0.0726)  0.3901 (0.0851)  0.3284 (0.0891) 
5  phi21      -0.0832 (0.0496) 0.0014 (0.0124)  -0.0076 (0.0121)
6  phi22      0.1067 (0.0601)  0.0243 (0.0327)  0.0586 (0.0328) 
7  a11        0 (0.0321)       0.2048 (0.0243)  0.2166 (0.0271) 
8  a12        -0.1618 (0.0231) 0.003 (0.0143)   -0.0121 (0.0141)
9  a21        0.1655 (0.0357)  0.2226 (0.0681)  0.2759 (0.0542) 
10 a22        0.2621 (0.0264)  0.1766 (0.027)   0.1801 (0.0366) 
11 g11        1.0002 (0.0082)  0.902 (0.0276)   0.8976 (0.0247) 
12 g12        0.023 (0.0069)   0.0067 (0.0097)  0.0193 (0.0108) 
13 g21        -0.0188 (0.0129) -0.0544 (0.0222) -0.0603 (0.0276)
14 g22        0.9584 (0.0093)  0.98 (0.0047)    0.9712 (0.008)  
   BEKK3            BEKK4            BEKK5            BEKK6           
1  2e-04 (6e-04)    5e-04 (5e-04)    4e-04 (5e-04)    4e-04 (5e-04)   
2  3e-04 (3e-04)    2e-04 (2e-04)    2e-04 (2e-04)    4e-04 (3e-04)   
3  -0.0362 (0.0316) 0.0204 (0.031)   0.012 (0.0311)   0.0192 (0.031)  
4  0.13 (0.075)     0.012 (0.0695)   0.1821 (0.0798)  0.0712 (0.0578) 
5  0.012 (0.0133)   0.0045 (0.0138)  0.0089 (0.0121)  0.0151 (0.0166) 
6  -0.0146 (0.0316) 0.0488 (0.0309)  0.0608 (0.0311)  0.016 (0.0309)  
7  0.1312 (0.0184)  0.1507 (0.0162)  0.2474 (0.027)   0.3151 (0.0459) 
8  0.0248 (0.0087)  -0.012 (0.0104)  -0.0345 (0.0126) -0.0251 (0.0221)
9  -0.154 (0.0709)  0.1248 (0.0454)  0.1419 (0.0808)  0.1619 (0.0808) 
10 0.2378 (0.0188)  0.215 (0.0258)   0.2258 (0.0278)  0.3102 (0.0274) 
11 0.9851 (0.0041)  0.981 (0.0044)   0.8959 (0.026)   0.6433 (0.0845) 
12 -0.0082 (0.0026) 0.0043 (0.0033)  0.0187 (0.0109)  -0.0549 (0.0314)
13 0.089 (0.029)    -0.0437 (0.0134) -0.0381 (0.0295) -0.0245 (0.0445)
14 0.952 (0.0068)   0.9712 (0.0075)  0.967 (0.0092)   0.9428 (0.0098)

In [97]:
daily_bekk2

Parameters BEKK7            BEKK8           
1  mu10       2e-04 (6e-04)    4e-04 (5e-04)   
2  mu20       -7e-04 (2e-04)   -3e-04 (3e-04)  
3  phi11      -0.0247 (0.031)  0.019 (0.031)   
4  phi12      -0.1399 (0.0969) -0.0269 (0.0515)
5  phi13      0.0437 (0.031)   0.0442 (0.031)  
6  phi14      -0.0893 (0.0969) 0.0166 (0.0515) 
7  phi21      -3e-04 (0.0096)  0.0068 (0.0186) 
8  phi22      -0.4007 (0.03)   -0.127 (0.0309) 
9  phi23      -0.0229 (0.0096) -0.0274 (0.0186)
10 phi24      -0.2456 (0.03)   -0.0754 (0.0309)
11 a11        0.1742 (0.0247)  0.0971 (0.0167) 
12 a12        0.0138 (0.0068)  -0.0175 (0.0113)
13 a21        0.0676 (0.0716)  0.0801 (0.0389) 
14 a22        0.3908 (0.0231)  0.2484 (0.0211) 
15 g11        0.8796 (0.0404)  0.9906 (0.0038) 
16 g12        0.0234 (0.0092)  0.0111 (0.0034) 
17 g21        -0.035 (0.0328)  -0.039 (0.0094) 
18 g22        0.9161 (0.0058)  0.9657 (0.0049)

# Final VAR-BEKK Table for Period 1 (Table A.2)

In [98]:
daily_bekk <- data.frame("Parameters" = c(parameters2,"Port"),
                         "BEKKC"=c(bekk_c[1:4],rep(NA,2),bekk_c[5:6],rep(NA,2),bekk_c[7:14],bekk_fit$Portmanteau.test$statistic),
                         "BEKK1"=c(bekk_1[1:4],rep(NA,2),bekk_1[5:6],rep(NA,2),bekk_1[7:14],bekk1_fit$Portmanteau.test$statistic),
                         "BEKK2"=c(bekk_2[1:4],rep(NA,2),bekk_2[5:6],rep(NA,2),bekk_2[7:14],bekk2_fit$Portmanteau.test$statistic),
                          "BEKK3"=c(bekk_3[1:4],rep(NA,2),bekk_3[5:6],rep(NA,2),bekk_3[7:14],bekk3_fit$Portmanteau.test$statistic),
                          "BEKK4"=c(bekk_4[1:4],rep(NA,2),bekk_4[5:6],rep(NA,2),bekk_4[7:14],bekk4_fit$Portmanteau.test$statistic),
                         "BEKK5"=c(bekk_5[1:4],rep(NA,2),bekk_5[5:6],rep(NA,2),bekk_5[7:14],bekk5_fit$Portmanteau.test$statistic),
                          "BEKK6"=c(bekk_6[1:4],rep(NA,2),bekk_6[5:6],rep(NA,2),bekk_6[7:14],bekk6_fit$Portmanteau.test$statistic),
                         "BEKK7" = c(bekk_7,bekk7_fit$Portmanteau.test$statistic),
                         "BEKK8" = c(bekk_8,bekk8_fit$Portmanteau.test$statistic))
daily_bekk

Parameters BEKKC             BEKK1             BEKK2            
1  mu10       2e-04 (6e-04)     3e-04 (6e-04)     3e-04 (6e-04)    
2  mu20       4e-04 (5e-04)     0 (2e-04)         -2e-04 (2e-04)   
3  phi11      -0.1913 (0.0599)  -0.0727 (0.0324)  -0.0662 (0.0327) 
4  phi12      0.2349 (0.0726)   0.3901 (0.0851)   0.3284 (0.0891)  
5  phi13      NA                NA                NA               
6  phi14      NA                NA                NA               
7  phi21      -0.0832 (0.0496)  0.0014 (0.0124)   -0.0076 (0.0121) 
8  phi22      0.1067 (0.0601)   0.0243 (0.0327)   0.0586 (0.0328)  
9  phi23      NA                NA                NA               
10 phi24      NA                NA                NA               
11 a11        0 (0.0321)        0.2048 (0.0243)   0.2166 (0.0271)  
12 a12        -0.1618 (0.0231)  0.003 (0.0143)    -0.0121 (0.0141) 
13 a21        0.1655 (0.0357)   0.2226 (0.0681)   0.2759 (0.0542)  
14 a22        0.2621 (0.0264)   0.1766 (0.027)    0.1801 (0.0366)  
15 g11        1.0002 (0.0082)   0.902 (0.0276)    0.8976 (0.0247)  
16 g12        0.023 (0.0069)    0.0067 (0.0097)   0.0193 (0.0108)  
17 g21        -0.0188 (0.0129)  -0.0544 (0.0222)  -0.0603 (0.0276) 
18 g22        0.9584 (0.0093)   0.98 (0.0047)     0.9712 (0.008)   
19 Port       0.511483459159855 0.824596190237684 0.890967299888113
   BEKK3             BEKK4             BEKK5             BEKK6            
1  2e-04 (6e-04)     5e-04 (5e-04)     4e-04 (5e-04)     4e-04 (5e-04)    
2  3e-04 (3e-04)     2e-04 (2e-04)     2e-04 (2e-04)     4e-04 (3e-04)    
3  -0.0362 (0.0316)  0.0204 (0.031)    0.012 (0.0311)    0.0192 (0.031)   
4  0.13 (0.075)      0.012 (0.0695)    0.1821 (0.0798)   0.0712 (0.0578)  
5  NA                NA                NA                NA               
6  NA                NA                NA                NA               
7  0.012 (0.0133)    0.0045 (0.0138)   0.0089 (0.0121)   0.0151 (0.0166)  
8  -0.0146 (0.0316)  0.0488 (0.0309)   0.0608 (0.0311)   0.016 (0.0309)   
9  NA                NA                NA                NA               
10 NA                NA                NA                NA               
11 0.1312 (0.0184)   0.1507 (0.0162)   0.2474 (0.027)    0.3151 (0.0459)  
12 0.0248 (0.0087)   -0.012 (0.0104)   -0.0345 (0.0126)  -0.0251 (0.0221) 
13 -0.154 (0.0709)   0.1248 (0.0454)   0.1419 (0.0808)   0.1619 (0.0808)  
14 0.2378 (0.0188)   0.215 (0.0258)    0.2258 (0.0278)   0.3102 (0.0274)  
15 0.9851 (0.0041)   0.981 (0.0044)    0.8959 (0.026)    0.6433 (0.0845)  
16 -0.0082 (0.0026)  0.0043 (0.0033)   0.0187 (0.0109)   -0.0549 (0.0314) 
17 0.089 (0.029)     -0.0437 (0.0134)  -0.0381 (0.0295)  -0.0245 (0.0445) 
18 0.952 (0.0068)    0.9712 (0.0075)   0.967 (0.0092)    0.9428 (0.0098)  
19 0.523482192521593 0.922435912594983 0.826177617769445 0.643441559748342
   BEKK7             BEKK8            
1  2e-04 (6e-04)     4e-04 (5e-04)    
2  -7e-04 (2e-04)    -3e-04 (3e-04)   
3  -0.0247 (0.031)   0.019 (0.031)    
4  -0.1399 (0.0969)  -0.0269 (0.0515) 
5  0.0437 (0.031)    0.0442 (0.031)   
6  -0.0893 (0.0969)  0.0166 (0.0515)  
7  -3e-04 (0.0096)   0.0068 (0.0186)  
8  -0.4007 (0.03)    -0.127 (0.0309)  
9  -0.0229 (0.0096)  -0.0274 (0.0186) 
10 -0.2456 (0.03)    -0.0754 (0.0309) 
11 0.1742 (0.0247)   0.0971 (0.0167)  
12 0.0138 (0.0068)   -0.0175 (0.0113) 
13 0.0676 (0.0716)   0.0801 (0.0389)  
14 0.3908 (0.0231)   0.2484 (0.0211)  
15 0.8796 (0.0404)   0.9906 (0.0038)  
16 0.0234 (0.0092)   0.0111 (0.0034)  
17 -0.035 (0.0328)   -0.039 (0.0094)  
18 0.9161 (0.0058)   0.9657 (0.0049)  
19 0.469395633560111 0.757924968901614