# Chapter 6

# Section 6.3.2: Full Sample Analysis (weekly data)

# VAR-BEKK Model for weekly data (Section 6.3.1)

In [1]:
library(xts)
library(BEKKs)
library(MTS)
library(vars)
library(stargazer)

Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric



Attaching package: ‘MTS’


The following object is masked from ‘package:BEKKs’:

    backtest


Loading required package: MASS

Loading required package: strucchange

Loading required package: sandwich

Loading required package: urca

Loading required package: lmtest


Attaching package: ‘vars’


The following object is masked from ‘package:MTS’:

    VAR



Please cite as: 


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer 




# Weekly Data preparation for the analysis

In [2]:
fr_w <- readRDS("fr_w.Rds")
fp_w <- readRDS("fp_w.Rds")
cr_w <- readRDS("cr_w.Rds")
cp_w <- readRDS("cp_w.Rds")
head(fr_w)
tail(fr_w)
head(cr_w)
tail(cr_w)

                 eurusd       gbpusd       chfusd       usdgbp        eurgbp
2007-07-13  0.011345725  0.011768041  0.012707420 -0.012031893 -0.0009595159
2007-07-20  0.003150978  0.010561671  0.001682187 -0.010223993 -0.0067425143
2007-07-27 -0.014056529 -0.015439970 -0.006685362  0.015297055  0.0008917293
2007-08-03  0.010216084  0.007480166  0.014875514 -0.007721262  0.0031888492
2007-08-10 -0.005898004 -0.007776587 -0.006690586  0.007822461  0.0022187717
2007-08-17 -0.016011531 -0.021627054 -0.007943236  0.021424385  0.0050110643
                  chfgbp       ghsusd       ghsgbp
2007-07-13  0.0009570421  0.004005436 -0.008009262
2007-07-20 -0.0088982748  0.002202455 -0.008376197
2007-07-27  0.0087979629 -0.003802426  0.011804209
2007-08-03  0.0074008865 -0.002685547 -0.009823491
2007-08-10  0.0010801929 -0.004550623  0.002725996
2007-08-17  0.0136908894  0.007384225  0.028262443

                 eurusd       gbpusd        chfusd       usdgbp       eurgbp
2024-03-29 -0.001111008  0.001744094 -0.0047696275 -0.001639758 -0.003269503
2024-04-05  0.003883141  0.001029173  0.0005411012 -0.001136794  0.002803085
2024-04-12 -0.018063806 -0.014867051 -0.0138903731  0.014927523 -0.003037031
2024-04-19  0.001173792 -0.006324418  0.0043785703  0.006268057  0.007691449
2024-04-26  0.003606646  0.009491706 -0.0043785703 -0.009510561 -0.006171781
2024-05-03  0.006152718  0.004433357  0.0094627884 -0.004381579  0.001867196
                  chfgbp       ghsusd       ghsgbp
2024-03-29 -0.0064137348 -0.015207144 -0.016876113
2024-04-05 -0.0005126015 -0.007520957 -0.008626210
2024-04-12  0.0009680267 -0.007463621  0.007446289
2024-04-19  0.0106995275  0.000000000  0.006285208
2024-04-26 -0.0138918686 -0.010349197 -0.019840737
2024-05-03  0.0050119709 -0.010258321 -0.014688795

                   usc           lc
2007-07-13 -0.02286903 -0.034778360
2007-07-20  0.02522142  0.003623192
2007-07-27 -0.07969033 -0.061529190
2007-08-03 -0.01849051 -0.036225204
2007-08-10 -0.03965627 -0.027288202
2007-08-17 -0.04129406 -0.023847683

                     usc          lc
2024-03-29  0.1057665488  0.12489565
2024-04-05  0.0006445376 -0.01368545
2024-04-12  0.1176875748  0.12562621
2024-04-19  0.0899585017  0.12954487
2024-04-26 -0.0786621644 -0.09105893
2024-05-03 -0.2628835611 -0.26525294

# VAR-BEKK model estimation

#### The estimation is conducted in two stages. Since the VAR model is used as the mean equation, it consitutes the first stage of the estimation process. The variance specification is the BEKK model, therefore, it is used as the second stage of the model. This procedure is followed in each case.

# (i) Spillover between US Cocoa and London Cocoa

## VAR

In [3]:
VARselect(cr_w,type = "const")

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.484548e+01 -1.483818e+01 -1.483208e+01 -1.482400e+01 -1.481934e+01
HQ(n)  -1.483287e+01 -1.481717e+01 -1.480266e+01 -1.478618e+01 -1.477311e+01
SC(n)  -1.481253e+01 -1.478327e+01 -1.475520e+01 -1.472516e+01 -1.469853e+01
FPE(n)  3.570179e-07  3.596344e-07  3.618362e-07  3.647702e-07  3.664761e-07
                   6             7             8             9            10
AIC(n) -1.481394e+01 -1.481237e+01 -1.481206e+01 -1.481529e+01 -1.480736e+01
HQ(n)  -1.475931e+01 -1.474933e+01 -1.474062e+01 -1.473545e+01 -1.471911e+01
SC(n)  -1.467117e+01 -1.464764e+01 -1.462536e+01 -1.460664e+01 -1.457674e+01
FPE(n)  3.684603e-07  3.690393e-07  3.691551e-07  3.679643e-07  3.708960e-07

In [4]:
var_cr<-VAR(cr_w,p = 1,type = "const")
summary(var_cr)
res_cr <- residuals(var_cr)
res_cr <- as.data.frame(res_cr)


VAR Estimation Results:
Endogenous variables: usc, lc 
Deterministic variables: const 
Sample size: 877 
Log Likelihood: 4029.845 
Roots of the characteristic polynomial:
0.08176 0.07899
Call:
VAR(y = cr_w, p = 1, type = "const")


Estimation results for equation usc: 
usc = usc.l1 + lc.l1 + const 

        Estimate Std. Error t value Pr(>|t|)   
usc.l1 -0.155331   0.078167  -1.987   0.0472 * 
lc.l1   0.247906   0.088087   2.814   0.0050 **
const   0.001261   0.001328   0.949   0.3427   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


Residual standard error: 0.03922 on 874 degrees of freedom
Multiple R-Squared: 0.01064,	Adjusted R-squared: 0.008377 
F-statistic:   4.7 on 2 and 874 DF,  p-value: 0.009325 


Estimation results for equation lc: 
lc = usc.l1 + lc.l1 + const 

        Estimate Std. Error t value Pr(>|t|)  
usc.l1 -0.073007   0.069963  -1.044   0.2970  
lc.l1   0.158099   0.078842   2.005   0.0452 *
const   0.001851   0.001189   1.558   0.1197  
---
Si

In [5]:
ind_var <- index(cr_w)[-1]
str(ind_var)

 Date[1:877], format: "2007-07-20" "2007-07-27" "2007-08-03" "2007-08-10" "2007-08-17" ...


In [6]:
res_cr <- xts(res_cr,order.by = ind_var)
str(res_cr)
head(res_cr)

An xts object on 2007-07-20 / 2024-05-03 containing: 
  Data:    double [877, 2]
  Columns: usc, lc
  Index:   Date [877] (TZ: "UTC")


                    usc           lc
2007-07-20  0.029030123  0.005600569
2007-07-27 -0.077931646 -0.062112097
2007-08-03 -0.016876237 -0.034166929
2007-08-10 -0.034808760 -0.024762416
2007-08-17 -0.041949789 -0.024280087
2007-08-24  0.008860472 -0.006356319

In [7]:
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk_fit <- bekk_fit(spec = bekk_spec,data = res_cr)
str(bekk_fit)

List of 25
 $ C0                         : num [1:2, 1:2] 0.005945 0.004418 0 0.000605
 $ A                          : num [1:2, 1:2] 0.0284 0.2969 -0.1379 0.4491
 $ G                          : num [1:2, 1:2] 0.9614 -0.0171 -0.0194 0.9636
 $ C0_t                       : num [1:2, 1:2] 4.575 4.004 0 0.692
 $ A_t                        : num [1:2, 1:2] 0.501 5.656 -2.74 8.661
 $ G_t                        : num [1:2, 1:2] 43.499 -0.83 -0.952 51.295
 $ C0_sd                      : num [1:2, 1:2] 0.001299 0.001103 0 0.000874
 $ A_sd                       : num [1:2, 1:2] 0.0566 0.0525 0.0503 0.0519
 $ G_sd                       : num [1:2, 1:2] 0.0221 0.0206 0.0204 0.0188
 $ theta                      : num [1:11, 1] 0.005945 0.004418 0.000605 0.028365 0.29687 ...
 $ log_likelihood             : num 4175
 $ BEKK_valid                 : logi TRUE
 $ sigma_t                    :An xts object on 2007-07-20 / 2024-05-03 containing: 
  Data:    double [877, 3]
  Columns: Conditional standard d

In [8]:
bekk_fit$A
bekk_fit$A_t

[,1]       [,2]      
[1,] 0.02836459 -0.1378523
[2,] 0.29686971  0.4490872

[,1]      [,2]     
[1,] 0.5011374 -2.740430
[2,] 5.6560361  8.660893

In [9]:
bekk_fit$G
bekk_fit$G_t

[,1]        [,2]       
[1,]  0.96135263 -0.01940285
[2,] -0.01714422  0.96364192

[,1]       [,2]      
[1,] 43.4994900 -0.9516857
[2,] -0.8304669 51.2946311

### VAR-BEKK Model Table for US Cocoa - London Cocoa

In [10]:
bekkc <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_cr)$varresult$usc$coefficients["const","Estimate"],summary(var_cr)$varresult$lc$coefficients["const","Estimate"],
                                   summary(var_cr)$varresult$usc$coefficients["usc.l1","Estimate"],summary(var_cr)$varresult$usc$coefficients["lc.l1","Estimate"],
                                   summary(var_cr)$varresult$lc$coefficients["usc.l1","Estimate"],summary(var_cr)$varresult$lc$coefficients["lc.l1","Estimate"],
                                   bekk_fit$A[1,1],bekk_fit$A[1,2],bekk_fit$A[2,1],bekk_fit$A[2,2],bekk_fit$G[1,1],bekk_fit$G[1,2],bekk_fit$G[2,1],bekk_fit$G[2,2]),
                   Std_error = c(summary(var_cr)$varresult$usc$coefficients["const","Std. Error"],summary(var_cr)$varresult$lc$coefficients["const","Std. Error"],
                               summary(var_cr)$varresult$usc$coefficients["usc.l1","Std. Error"],summary(var_cr)$varresult$usc$coefficients["lc.l1","Std. Error"],
                                 summary(var_cr)$varresult$lc$coefficients["usc.l1","Std. Error"],summary(var_cr)$varresult$lc$coefficients["lc.l1","Std. Error"],
                                 bekk_fit$A_sd[1,1],bekk_fit$A_sd[1,2],bekk_fit$A_sd[2,1],bekk_fit$A_sd[2,2],bekk_fit$G_sd[1,1],bekk_fit$G_sd[1,2],bekk_fit$G_sd[2,1],bekk_fit$G_sd[2,2]),
                   T_value = c(summary(var_cr)$varresult$usc$coefficients["const","t value"],summary(var_cr)$varresult$lc$coefficients["const","t value"],
                               summary(var_cr)$varresult$usc$coefficients["usc.l1","t value"],summary(var_cr)$varresult$usc$coefficients["lc.l1","t value"],
                               summary(var_cr)$varresult$lc$coefficients["usc.l1","t value"],summary(var_cr)$varresult$lc$coefficients["lc.l1","t value"],
                               bekk_fit$A_t[1,1],bekk_fit$A_t[1,2],bekk_fit$A_t[2,1],bekk_fit$A_t[2,2],bekk_fit$G_t[1,1],bekk_fit$G_t[1,2],
                                 bekk_fit$G_t[2,1],bekk_fit$G_t[2,2]))

bekkc$Significant_at_5p_level[abs(bekkc$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekkc$Significant_at_5p_level[abs(bekkc$T_value) > 1.96 & abs(bekkc$T_value) < 2.58] <- "Stat significant at 5%"
bekkc$Significant_at_5p_level[abs(bekkc$T_value) > 1.645 & abs(bekkc$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekkc$Significant_at_5p_level[abs(bekkc$T_value) <= 1.645] <- "Not Statistically Significant"
bekkc

Parameters Coefficient  Std_error   T_value    Significant_at_5p_level      
1  mu10        0.001260782 0.001328108  0.9493065 Not Statistically Significant
2  mu20        0.001851436 0.001188718  1.5575065 Not Statistically Significant
3  phi11      -0.155331179 0.078167228 -1.9871650 Stat significant at 5%       
4  phi12       0.247905884 0.088087112  2.8143264 Stat significant at 1%       
5  phi21      -0.073007499 0.069963278 -1.0435117 Not Statistically Significant
6  phi22       0.158098996 0.078842033  2.0052628 Stat significant at 5%       
7  a11         0.028364588 0.056600426  0.5011374 Not Statistically Significant
8  a12        -0.137852276 0.050303159 -2.7404298 Stat significant at 1%       
9  a21         0.296869706 0.052487237  5.6560361 Stat significant at 1%       
10 a22         0.449087222 0.051852298  8.6608933 Stat significant at 1%       
11 g11         0.961352627 0.022100319 43.4994900 Stat significant at 1%       
12 g12        -0.019402847 0.020387874 -0.9516857 Not Statistically Significant
13 g21        -0.017144222 0.020644075 -0.8304669 Not Statistically Significant
14 g22         0.963641916 0.018786409 51.2946311 Stat significant at 1%

- mean spillover from London Cocoa to US Cocoa
-  shock spillover works in both ways
- no volatility spillover

In [11]:
round(0.158098996,4)

[1] 0.1581

In [12]:
causality(var_cr,cause = "usc")$Granger
causality(var_cr,cause = "lc")$Granger


	Granger causality H0: usc do not Granger-cause lc

data:  VAR object var_cr
F-Test = 1.0889, df1 = 1, df2 = 1748, p-value = 0.2969



	Granger causality H0: lc do not Granger-cause usc

data:  VAR object var_cr
F-Test = 7.9204, df1 = 1, df2 = 1748, p-value = 0.004943


# (ii) VAR-BEKK Models for US Cocoa

In [13]:
head(cr_w)
head(fr_w)

                   usc           lc
2007-07-13 -0.02286903 -0.034778360
2007-07-20  0.02522142  0.003623192
2007-07-27 -0.07969033 -0.061529190
2007-08-03 -0.01849051 -0.036225204
2007-08-10 -0.03965627 -0.027288202
2007-08-17 -0.04129406 -0.023847683

                 eurusd       gbpusd       chfusd       usdgbp        eurgbp
2007-07-13  0.011345725  0.011768041  0.012707420 -0.012031893 -0.0009595159
2007-07-20  0.003150978  0.010561671  0.001682187 -0.010223993 -0.0067425143
2007-07-27 -0.014056529 -0.015439970 -0.006685362  0.015297055  0.0008917293
2007-08-03  0.010216084  0.007480166  0.014875514 -0.007721262  0.0031888492
2007-08-10 -0.005898004 -0.007776587 -0.006690586  0.007822461  0.0022187717
2007-08-17 -0.016011531 -0.021627054 -0.007943236  0.021424385  0.0050110643
                  chfgbp       ghsusd       ghsgbp
2007-07-13  0.0009570421  0.004005436 -0.008009262
2007-07-20 -0.0088982748  0.002202455 -0.008376197
2007-07-27  0.0087979629 -0.003802426  0.011804209
2007-08-03  0.0074008865 -0.002685547 -0.009823491
2007-08-10  0.0010801929 -0.004550623  0.002725996
2007-08-17  0.0136908894  0.007384225  0.028262443

In [14]:
us_w <- na.omit(merge(cr_w[,1],fr_w))
str(us_w)
head(us_w)

An xts object on 2007-07-13 / 2024-05-03 containing: 
  Data:    double [878, 9]
  Columns: usc, eurusd, gbpusd, chfusd, usdgbp ... with 4 more columns
  Index:   Date [878] (TZ: "UTC")
  xts Attributes:
    $ ret_type        : chr "log"
    $ coredata_content: chr "logReturn"


                   usc       eurusd       gbpusd       chfusd       usdgbp
2007-07-13 -0.02286903  0.011345725  0.011768041  0.012707420 -0.012031893
2007-07-20  0.02522142  0.003150978  0.010561671  0.001682187 -0.010223993
2007-07-27 -0.07969033 -0.014056529 -0.015439970 -0.006685362  0.015297055
2007-08-03 -0.01849051  0.010216084  0.007480166  0.014875514 -0.007721262
2007-08-10 -0.03965627 -0.005898004 -0.007776587 -0.006690586  0.007822461
2007-08-17 -0.04129406 -0.016011531 -0.021627054 -0.007943236  0.021424385
                  eurgbp        chfgbp       ghsusd       ghsgbp
2007-07-13 -0.0009595159  0.0009570421  0.004005436 -0.008009262
2007-07-20 -0.0067425143 -0.0088982748  0.002202455 -0.008376197
2007-07-27  0.0008917293  0.0087979629 -0.003802426  0.011804209
2007-08-03  0.0031888492  0.0074008865 -0.002685547 -0.009823491
2007-08-10  0.0022187717  0.0010801929 -0.004550623  0.002725996
2007-08-17  0.0050110643  0.0136908894  0.007384225  0.028262443

## (a) US Cocoa - EURUSD

In [15]:
bekk1data <- us_w[,c(1:2)]
head(bekk1data)

                   usc       eurusd
2007-07-13 -0.02286903  0.011345725
2007-07-20  0.02522142  0.003150978
2007-07-27 -0.07969033 -0.014056529
2007-08-03 -0.01849051  0.010216084
2007-08-10 -0.03965627 -0.005898004
2007-08-17 -0.04129406 -0.016011531

In [16]:
VARselect(bekk1data,type = "const")
var_bekk1<-VAR(bekk1data,p = 1,type = "const")
res_bekk1 <- residuals(var_bekk1)
res_bekk1 <- as.data.frame(res_bekk1)
summary(var_bekk1)
ind_var1 <- index(bekk1data)[-1]
str(ind_var1)

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.526901e+01 -1.526377e+01 -1.525540e+01 -1.524817e+01 -1.524367e+01
HQ(n)  -1.525640e+01 -1.524276e+01 -1.522598e+01 -1.521035e+01 -1.519744e+01
SC(n)  -1.523606e+01 -1.520886e+01 -1.517852e+01 -1.514933e+01 -1.512287e+01
FPE(n)  2.337509e-07  2.349790e-07  2.369549e-07  2.386739e-07  2.397502e-07
                   6             7             8             9            10
AIC(n) -1.524095e+01 -1.523333e+01 -1.523340e+01 -1.523504e+01 -1.522646e+01
HQ(n)  -1.518632e+01 -1.517029e+01 -1.516196e+01 -1.515520e+01 -1.513821e+01
SC(n)  -1.509818e+01 -1.506860e+01 -1.504671e+01 -1.502639e+01 -1.499584e+01
FPE(n)  2.404039e-07  2.422435e-07  2.422259e-07  2.418300e-07  2.439156e-07


VAR Estimation Results:
Endogenous variables: usc, eurusd 
Deterministic variables: const 
Sample size: 877 
Log Likelihood: 4215.722 
Roots of the characteristic polynomial:
0.05075 0.007778
Call:
VAR(y = bekk1data, p = 1, type = "const")


Estimation results for equation usc: 
usc = usc.l1 + eurusd.l1 + const 

           Estimate Std. Error t value Pr(>|t|)
usc.l1     0.045756   0.036398   1.257    0.209
eurusd.l1 -0.037212   0.109600  -0.340    0.734
const      0.001465   0.001333   1.099    0.272


Residual standard error: 0.03939 on 874 degrees of freedom
Multiple R-Squared: 0.001807,	Adjusted R-squared: -0.0004773 
F-statistic: 0.791 on 2 and 874 DF,  p-value: 0.4537 


Estimation results for equation eurusd: 
eurusd = usc.l1 + eurusd.l1 + const 

            Estimate Std. Error t value Pr(>|t|)
usc.l1    -0.0071890  0.0117790  -0.610    0.542
eurusd.l1 -0.0027811  0.0354678  -0.078    0.938
const     -0.0002700  0.0004313  -0.626    0.531


Residual standard error: 0.01275 on 

 Date[1:877], format: "2007-07-20" "2007-07-27" "2007-08-03" "2007-08-10" "2007-08-17" ...


In [17]:
res_bekk1 <- xts(res_bekk1,order.by = ind_var1)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk1_fit <- bekk_fit(spec = bekk_spec,data = res_bekk1)
bekk1_fit$A
bekk1_fit$A_t
bekk1_fit$G
bekk1_fit$G_t

[,1]       [,2]        
[1,] 0.30355934 -0.008215322
[2,] 0.03576806  0.278101120

[,1]       [,2]     
[1,] 11.2128659 -0.784881
[2,]  0.4043397  9.804262

[,1]        [,2]     
[1,] 0.933837983 0.0070885
[2,] 0.001637461 0.9434765

[,1]      [,2]     
[1,] 56.337633  1.303809
[2,]  0.033929 75.000933

### VAR-BEKK Model Table for US Cocoa - EURUSD

In [18]:
bekk1 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk1)$varresult$usc$coefficients["const","Estimate"],summary(var_bekk1)$varresult$eurusd$coefficients["const","Estimate"],
                                   summary(var_bekk1)$varresult$usc$coefficients["usc.l1","Estimate"],summary(var_bekk1)$varresult$usc$coefficients["eurusd.l1","Estimate"],
                                   summary(var_bekk1)$varresult$eurusd$coefficients["usc.l1","Estimate"],summary(var_bekk1)$varresult$eurusd$coefficients["eurusd.l1","Estimate"],
                                   bekk1_fit$A[1,1],bekk1_fit$A[1,2],bekk1_fit$A[2,1],bekk1_fit$A[2,2],bekk1_fit$G[1,1],bekk1_fit$G[1,2],bekk1_fit$G[2,1],bekk1_fit$G[2,2]),
                   Std_error = c(summary(var_bekk1)$varresult$usc$coefficients["const","Std. Error"],summary(var_bekk1)$varresult$eurusd$coefficients["const","Std. Error"],
                                summary(var_bekk1)$varresult$usc$coefficients["usc.l1","Std. Error"],summary(var_bekk1)$varresult$usc$coefficients["eurusd.l1","Std. Error"],
                                 summary(var_bekk1)$varresult$eurusd$coefficients["usc.l1","Std. Error"],summary(var_bekk1)$varresult$eurusd$coefficients["eurusd.l1","Std. Error"],
                                 bekk1_fit$A_sd[1,1],bekk1_fit$A_sd[1,2],bekk1_fit$A_sd[2,1],bekk1_fit$A_sd[2,2],bekk1_fit$G_sd[1,1],bekk1_fit$G_sd[1,2],bekk1_fit$G_sd[2,1],bekk1_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk1)$varresult$usc$coefficients["const","t value"],summary(var_bekk1)$varresult$eurusd$coefficients["const","t value"],
                       summary(var_bekk1)$varresult$usc$coefficients["usc.l1","t value"],summary(var_bekk1)$varresult$usc$coefficients["eurusd.l1","t value"],
                               summary(var_bekk1)$varresult$eurusd$coefficients["usc.l1","t value"],summary(var_bekk1)$varresult$eurusd$coefficients["eurusd.l1","t value"],
                               bekk1_fit$A_t[1,1],bekk1_fit$A_t[1,2],bekk1_fit$A_t[2,1],bekk1_fit$A_t[2,2],bekk1_fit$G_t[1,1],bekk1_fit$G_t[1,2],bekk1_fit$G_t[2,1],bekk1_fit$G_t[2,2]))

bekk1$Significant_at_5p_level[abs(bekk1$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk1$Significant_at_5p_level[abs(bekk1$T_value) > 1.96 & abs(bekk1$T_value) < 2.58] <- "Stat significant at 5%"
bekk1$Significant_at_5p_level[abs(bekk1$T_value) > 1.645 & abs(bekk1$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk1$Significant_at_5p_level[abs(bekk1$T_value) <= 1.645] <- "Not Statistically Significant"
bekk1

Parameters Coefficient  Std_error    T_value    
1  mu10        0.001465075 0.0013326381  1.09937941
2  mu20       -0.000269960 0.0004312581 -0.62598233
3  phi11       0.045755848 0.0363983528  1.25708567
4  phi12      -0.037212136 0.1095997523 -0.33952756
5  phi21      -0.007189014 0.0117789566 -0.61032687
6  phi22      -0.002781125 0.0354678337 -0.07841259
7  a11         0.303559340 0.0270724134 11.21286588
8  a12        -0.008215322 0.0104669657 -0.78488097
9  a21         0.035768064 0.0884604409  0.40433966
10 a22         0.278101120 0.0283653300  9.80426173
11 g11         0.933837983 0.0165757405 56.33763285
12 g12         0.007088500 0.0054367650  1.30380851
13 g21         0.001637461 0.0482614053  0.03392900
14 g22         0.943476517 0.0125795305 75.00093255
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Not Statistically Significant
4  Not Statistically Significant
5  Not Statistically Significant
6  Not Statistically Significant
7  Stat significant at 1%       
8  Not Statistically Significant
9  Not Statistically Significant
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Not Statistically Significant
13 Not Statistically Significant
14 Stat significant at 1%

- no transmission found whatsoever

In [19]:
causality(var_bekk1,cause = "usc")$Granger
causality(var_bekk1,cause = "eurusd")$Granger


	Granger causality H0: usc do not Granger-cause eurusd

data:  VAR object var_bekk1
F-Test = 0.3725, df1 = 1, df2 = 1748, p-value = 0.5417



	Granger causality H0: eurusd do not Granger-cause usc

data:  VAR object var_bekk1
F-Test = 0.11528, df1 = 1, df2 = 1748, p-value = 0.7343


## (b) VAR-BEKK: US Cocoa-GBPUSD

In [20]:
bekk2data <- us_w[,c(1,3)]
head(bekk2data)

                   usc       gbpusd
2007-07-13 -0.02286903  0.011768041
2007-07-20  0.02522142  0.010561671
2007-07-27 -0.07969033 -0.015439970
2007-08-03 -0.01849051  0.007480166
2007-08-10 -0.03965627 -0.007776587
2007-08-17 -0.04129406 -0.021627054

In [21]:
VARselect(bekk2data,type = "const")
var_bekk2<-VAR(bekk2data,p = 1,type = "const")
res_bekk2 <- residuals(var_bekk2)
res_bekk2 <- as.data.frame(res_bekk2)
summary(var_bekk2)

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.513043e+01 -1.512928e+01 -1.512602e+01 -1.511778e+01 -1.511250e+01
HQ(n)  -1.511783e+01 -1.510827e+01 -1.509660e+01 -1.507996e+01 -1.506627e+01
SC(n)  -1.509749e+01 -1.507437e+01 -1.504914e+01 -1.501894e+01 -1.499169e+01
FPE(n)  2.684952e-07  2.688055e-07  2.696839e-07  2.719142e-07  2.733552e-07
                   6             7             8             9            10
AIC(n) -1.510989e+01 -1.510441e+01 -1.510530e+01 -1.510499e+01 -1.509990e+01
HQ(n)  -1.505526e+01 -1.504138e+01 -1.503385e+01 -1.502514e+01 -1.501165e+01
SC(n)  -1.496712e+01 -1.493968e+01 -1.491860e+01 -1.489633e+01 -1.486928e+01
FPE(n)  2.740698e-07  2.755747e-07  2.753326e-07  2.754185e-07  2.768255e-07


VAR Estimation Results:
Endogenous variables: usc, gbpusd 
Deterministic variables: const 
Sample size: 877 
Log Likelihood: 4154.461 
Roots of the characteristic polynomial:
0.02985 0.01823
Call:
VAR(y = bekk2data, p = 1, type = "const")


Estimation results for equation usc: 
usc = usc.l1 + gbpusd.l1 + const 

           Estimate Std. Error t value Pr(>|t|)
usc.l1     0.055511   0.036062   1.539    0.124
gbpusd.l1 -0.138041   0.101913  -1.355    0.176
const      0.001383   0.001332   1.038    0.300


Residual standard error: 0.03935 on 874 degrees of freedom
Multiple R-Squared: 0.003767,	Adjusted R-squared: 0.001487 
F-statistic: 1.652 on 2 and 874 DF,  p-value: 0.1922 


Estimation results for equation gbpusd: 
gbpusd = usc.l1 + gbpusd.l1 + const 

            Estimate Std. Error t value Pr(>|t|)
usc.l1     0.0137075  0.0124335   1.102    0.271
gbpusd.l1 -0.0438890  0.0351376  -1.249    0.212
const     -0.0006001  0.0004594  -1.306    0.192


Residual standard error: 0.01357 on 874

In [22]:
ind_var2 <- index(bekk2data)[-1]
str(ind_var2)
res_bekk2 <- xts(res_bekk2,order.by = ind_var2)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk2_fit <- bekk_fit(spec = bekk_spec,data = res_bekk2)
bekk2_fit$A
bekk2_fit$A_t
bekk2_fit$G
bekk2_fit$G_t

 Date[1:877], format: "2007-07-20" "2007-07-27" "2007-08-03" "2007-08-10" "2007-08-17" ...


[,1]        [,2]        
[1,]  0.30098712 -0.003236516
[2,] -0.02065668  0.306207721

[,1]       [,2]      
[1,] 15.0571444 -0.3419945
[2,] -0.2507182 11.8617640

[,1]        [,2]       
[1,]  0.94587603 0.002904426
[2,] -0.06204918 0.931384983

[,1]      [,2]      
[1,] 91.191326  0.7000524
[2,] -1.554008 80.1275258

### VAR-BEKK Model Table for US Cocoa - GBPUSD

In [23]:
bekk2 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk2)$varresult$usc$coefficients["const","Estimate"],summary(var_bekk2)$varresult$gbpusd$coefficients["const","Estimate"],
                       summary(var_bekk2)$varresult$usc$coefficients["usc.l1","Estimate"],summary(var_bekk2)$varresult$usc$coefficients["gbpusd.l1","Estimate"],
                                   summary(var_bekk2)$varresult$gbpusd$coefficients["usc.l1","Estimate"],summary(var_bekk2)$varresult$gbpusd$coefficients["gbpusd.l1","Estimate"],
                                   bekk2_fit$A[1,1],bekk2_fit$A[1,2],bekk2_fit$A[2,1],bekk2_fit$A[2,2],bekk2_fit$G[1,1],bekk2_fit$G[1,2],bekk2_fit$G[2,1],bekk2_fit$G[2,2]),
                   Std_error = c(summary(var_bekk2)$varresult$usc$coefficients["const","Std. Error"],summary(var_bekk2)$varresult$gbpusd$coefficients["const","Std. Error"],
                       summary(var_bekk2)$varresult$usc$coefficients["usc.l1","Std. Error"],summary(var_bekk2)$varresult$usc$coefficients["gbpusd.l1","Std. Error"],
                                 summary(var_bekk2)$varresult$gbpusd$coefficients["usc.l1","Std. Error"],summary(var_bekk2)$varresult$gbpusd$coefficients["gbpusd.l1","Std. Error"],
                                 bekk2_fit$A_sd[1,1],bekk2_fit$A_sd[1,2],bekk2_fit$A_sd[2,1],bekk2_fit$A_sd[2,2],bekk2_fit$G_sd[1,1],bekk2_fit$G_sd[1,2],bekk2_fit$G_sd[2,1],bekk2_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk2)$varresult$usc$coefficients["const","t value"],summary(var_bekk2)$varresult$gbpusd$coefficients["const","t value"],
                       summary(var_bekk2)$varresult$usc$coefficients["usc.l1","t value"],summary(var_bekk2)$varresult$usc$coefficients["gbpusd.l1","t value"],
                               summary(var_bekk2)$varresult$gbpusd$coefficients["usc.l1","t value"],summary(var_bekk2)$varresult$gbpusd$coefficients["gbpusd.l1","t value"],
                               bekk2_fit$A_t[1,1],bekk2_fit$A_t[1,2],bekk2_fit$A_t[2,1],bekk2_fit$A_t[2,2],bekk2_fit$G_t[1,1],bekk2_fit$G_t[1,2],bekk2_fit$G_t[2,1],bekk2_fit$G_t[2,2]))

bekk2$Significant_at_5p_level[abs(bekk2$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk2$Significant_at_5p_level[abs(bekk2$T_value) > 1.96 & abs(bekk2$T_value) < 2.58] <- "Stat significant at 5%"
bekk2$Significant_at_5p_level[abs(bekk2$T_value) > 1.645 & abs(bekk2$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk2$Significant_at_5p_level[abs(bekk2$T_value) <= 1.645] <- "Not Statistically Significant"
bekk2

Parameters Coefficient   Std_error    T_value   
1  mu10        0.0013825608 0.0013324066  1.0376418
2  mu20       -0.0006000506 0.0004593885 -1.3061942
3  phi11       0.0555112141 0.0360619560  1.5393290
4  phi12      -0.1380407768 0.1019126965 -1.3545003
5  phi21       0.0137074622 0.0124334784  1.1024640
6  phi22      -0.0438890285 0.0351375646 -1.2490629
7  a11         0.3009871177 0.0199896548 15.0571444
8  a12        -0.0032365156 0.0094636477 -0.3419945
9  a21        -0.0206566844 0.0823900458 -0.2507182
10 a22         0.3062077211 0.0258146867 11.8617640
11 g11         0.9458760260 0.0103724342 91.1913258
12 g12         0.0029044263 0.0041488697  0.7000524
13 g21        -0.0620491756 0.0399284702 -1.5540083
14 g22         0.9313849832 0.0116237831 80.1275258
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Not Statistically Significant
4  Not Statistically Significant
5  Not Statistically Significant
6  Not Statistically Significant
7  Stat significant at 1%       
8  Not Statistically Significant
9  Not Statistically Significant
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Not Statistically Significant
13 Not Statistically Significant
14 Stat significant at 1%

- no transmission

In [24]:
causality(var_bekk2,cause = "usc")$Granger
causality(var_bekk2,cause = "gbpusd")$Granger


	Granger causality H0: usc do not Granger-cause gbpusd

data:  VAR object var_bekk2
F-Test = 1.2154, df1 = 1, df2 = 1748, p-value = 0.2704



	Granger causality H0: gbpusd do not Granger-cause usc

data:  VAR object var_bekk2
F-Test = 1.8347, df1 = 1, df2 = 1748, p-value = 0.1758


## (c) VAR-BEKK: US Cocoa-CHFUSD

In [25]:
bekk3data <- us_w[,c(1,4)]
head(bekk3data)

                   usc       chfusd
2007-07-13 -0.02286903  0.012707420
2007-07-20  0.02522142  0.001682187
2007-07-27 -0.07969033 -0.006685362
2007-08-03 -0.01849051  0.014875514
2007-08-10 -0.03965627 -0.006690586
2007-08-17 -0.04129406 -0.007943236

In [26]:
VARselect(bekk3data,type = "const")
var_bekk3<-VAR(bekk3data,p = 1,type = "const")
res_bekk3 <- residuals(var_bekk3)
res_bekk3 <- as.data.frame(res_bekk3)
summary(var_bekk3)

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.492517e+01 -1.491755e+01 -1.491405e+01 -1.491055e+01 -1.491077e+01
HQ(n)  -1.491256e+01 -1.489653e+01 -1.488464e+01 -1.487273e+01 -1.486455e+01
SC(n)  -1.489222e+01 -1.486264e+01 -1.483718e+01 -1.481171e+01 -1.478997e+01
FPE(n)  3.296727e-07  3.321945e-07  3.333568e-07  3.345259e-07  3.344522e-07
                   6             7             8             9            10
AIC(n) -1.491396e+01 -1.490812e+01 -1.490493e+01 -1.490834e+01 -1.489981e+01
HQ(n)  -1.485933e+01 -1.484508e+01 -1.483349e+01 -1.482849e+01 -1.481156e+01
SC(n)  -1.477119e+01 -1.474339e+01 -1.471824e+01 -1.469968e+01 -1.466919e+01
FPE(n)  3.333898e-07  3.353421e-07  3.364144e-07  3.352723e-07  3.381434e-07


VAR Estimation Results:
Endogenous variables: usc, chfusd 
Deterministic variables: const 
Sample size: 877 
Log Likelihood: 4065.808 
Roots of the characteristic polynomial:
0.06394 0.06097
Call:
VAR(y = bekk3data, p = 1, type = "const")


Estimation results for equation usc: 
usc = usc.l1 + chfusd.l1 + const 

           Estimate Std. Error t value Pr(>|t|)  
usc.l1     0.056521   0.035342   1.599   0.1101  
chfusd.l1 -0.186344   0.091745  -2.031   0.0425 *
const      0.001517   0.001329   1.141   0.2540  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


Residual standard error: 0.0393 on 874 degrees of freedom
Multiple R-Squared: 0.006365,	Adjusted R-squared: 0.004092 
F-statistic: 2.799 on 2 and 874 DF,  p-value: 0.06139 


Estimation results for equation chfusd: 
chfusd = usc.l1 + chfusd.l1 + const 

            Estimate Std. Error t value Pr(>|t|)  
usc.l1    -0.0028787  0.0132772  -0.217   0.8284  
chfusd.l1 -0.0594854  0.0344664  -1.726   0.0847 .
const    

In [27]:
ind_var3 <- index(bekk3data)[-1]
str(ind_var3)
res_bekk3 <- xts(res_bekk3,order.by = ind_var3)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk3_fit <- bekk_fit(spec = bekk_spec,data = res_bekk3)
bekk3_fit$A
bekk3_fit$A_t
bekk3_fit$G
bekk3_fit$G_t

 Date[1:877], format: "2007-07-20" "2007-07-27" "2007-08-03" "2007-08-10" "2007-08-17" ...


[,1]      [,2]       
[1,] 0.2691389 -0.02662968
[2,] 0.1831795  0.43666331

[,1]      [,2]     
[1,] 10.621786 -1.986508
[2,]  2.134578 17.068002

[,1]        [,2]      
[1,]  0.95230986 0.01466669
[2,] -0.04728132 0.86075012

[,1]       [,2]    
[1,] 72.9033751  1.93139
[2,] -0.8555522 38.16946

### VAR-BEKK Model Table for US Cocoa - CHFUSD

In [28]:
bekk3 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk3)$varresult$usc$coefficients["const","Estimate"],summary(var_bekk3)$varresult$chfusd$coefficients["const","Estimate"],
                       summary(var_bekk3)$varresult$usc$coefficients["usc.l1","Estimate"],summary(var_bekk3)$varresult$usc$coefficients["chfusd.l1","Estimate"],
                                   summary(var_bekk3)$varresult$chfusd$coefficients["usc.l1","Estimate"],summary(var_bekk3)$varresult$chfusd$coefficients["chfusd.l1","Estimate"],
                                   bekk3_fit$A[1,1],bekk3_fit$A[1,2],bekk3_fit$A[2,1],bekk3_fit$A[2,2],bekk3_fit$G[1,1],bekk3_fit$G[1,2],bekk3_fit$G[2,1],bekk3_fit$G[2,2]),
                   Std_error = c(summary(var_bekk3)$varresult$usc$coefficients["const","Std. Error"],summary(var_bekk3)$varresult$chfusd$coefficients["const","Std. Error"],
                       summary(var_bekk3)$varresult$usc$coefficients["usc.l1","Std. Error"],summary(var_bekk3)$varresult$usc$coefficients["chfusd.l1","Std. Error"],
                                 summary(var_bekk3)$varresult$chfusd$coefficients["usc.l1","Std. Error"],summary(var_bekk3)$varresult$chfusd$coefficients["chfusd.l1","Std. Error"],
                                 bekk3_fit$A_sd[1,1],bekk3_fit$A_sd[1,2],bekk3_fit$A_sd[2,1],bekk3_fit$A_sd[2,2],bekk3_fit$G_sd[1,1],bekk3_fit$G_sd[1,2],bekk3_fit$G_sd[2,1],bekk3_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk3)$varresult$usc$coefficients["const","t value"],summary(var_bekk3)$varresult$chfusd$coefficients["const","t value"],
                       summary(var_bekk3)$varresult$usc$coefficients["usc.l1","t value"],summary(var_bekk3)$varresult$usc$coefficients["chfusd.l1","t value"],
                               summary(var_bekk3)$varresult$chfusd$coefficients["usc.l1","t value"],summary(var_bekk3)$varresult$chfusd$coefficients["chfusd.l1","t value"],
                               bekk3_fit$A_t[1,1],bekk3_fit$A_t[1,2],bekk3_fit$A_t[2,1],bekk3_fit$A_t[2,2],bekk3_fit$G_t[1,1],bekk3_fit$G_t[1,2],bekk3_fit$G_t[2,1],bekk3_fit$G_t[2,2]))

bekk3$Significant_at_5p_level[abs(bekk3$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk3$Significant_at_5p_level[abs(bekk3$T_value) > 1.96 & abs(bekk3$T_value) < 2.58] <- "Stat significant at 5%"
bekk3$Significant_at_5p_level[abs(bekk3$T_value) > 1.645 & abs(bekk3$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk3$Significant_at_5p_level[abs(bekk3$T_value) <= 1.645] <- "Not Statistically Significant"
bekk3

Parameters Coefficient   Std_error    T_value   
1  mu10        0.0015165844 0.0013287452  1.1413659
2  mu20        0.0003481443 0.0004991762  0.6974377
3  phi11       0.0565214826 0.0353422700  1.5992601
4  phi12      -0.1863436435 0.0917451659 -2.0311004
5  phi21      -0.0028787372 0.0132772030 -0.2168180
6  phi22      -0.0594853925 0.0344663540 -1.7258975
7  a11         0.2691388891 0.0253383840 10.6217859
8  a12        -0.0266296779 0.0134052738 -1.9865076
9  a21         0.1831795056 0.0858153227  2.1345781
10 a22         0.4366633069 0.0255837395 17.0680016
11 g11         0.9523098600 0.0130626306 72.9033751
12 g12         0.0146666880 0.0075938526  1.9313896
13 g21        -0.0472813224 0.0552641023 -0.8555522
14 g22         0.8607501197 0.0225507515 38.1694650
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Not Statistically Significant
4  Stat significant at 5%       
5  Not Statistically Significant
6  Stat significant at 10%      
7  Stat significant at 1%       
8  Stat significant at 5%       
9  Stat significant at 5%       
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Stat significant at 10%      
13 Not Statistically Significant
14 Stat significant at 1%

- mean transmission from CHF to US Cocoa
- shock spillovers work in both ways

In [29]:
causality(var_bekk3,cause = "usc")$Granger
causality(var_bekk3,cause = "chfusd")$Granger


	Granger causality H0: usc do not Granger-cause chfusd

data:  VAR object var_bekk3
F-Test = 0.04701, df1 = 1, df2 = 1748, p-value = 0.8284



	Granger causality H0: chfusd do not Granger-cause usc

data:  VAR object var_bekk3
F-Test = 4.1254, df1 = 1, df2 = 1748, p-value = 0.0424


## (d) VAR-BEKK model for US Cocoa - GHSUSD

In [30]:
head(fr_w)
head(cr_w)

                 eurusd       gbpusd       chfusd       usdgbp        eurgbp
2007-07-13  0.011345725  0.011768041  0.012707420 -0.012031893 -0.0009595159
2007-07-20  0.003150978  0.010561671  0.001682187 -0.010223993 -0.0067425143
2007-07-27 -0.014056529 -0.015439970 -0.006685362  0.015297055  0.0008917293
2007-08-03  0.010216084  0.007480166  0.014875514 -0.007721262  0.0031888492
2007-08-10 -0.005898004 -0.007776587 -0.006690586  0.007822461  0.0022187717
2007-08-17 -0.016011531 -0.021627054 -0.007943236  0.021424385  0.0050110643
                  chfgbp       ghsusd       ghsgbp
2007-07-13  0.0009570421  0.004005436 -0.008009262
2007-07-20 -0.0088982748  0.002202455 -0.008376197
2007-07-27  0.0087979629 -0.003802426  0.011804209
2007-08-03  0.0074008865 -0.002685547 -0.009823491
2007-08-10  0.0010801929 -0.004550623  0.002725996
2007-08-17  0.0136908894  0.007384225  0.028262443

                   usc           lc
2007-07-13 -0.02286903 -0.034778360
2007-07-20  0.02522142  0.003623192
2007-07-27 -0.07969033 -0.061529190
2007-08-03 -0.01849051 -0.036225204
2007-08-10 -0.03965627 -0.027288202
2007-08-17 -0.04129406 -0.023847683

In [31]:
bekk7data <- na.omit(merge(cr_w[,1],fr_w[,7]))
head(bekk7data)

                   usc       ghsusd
2007-07-13 -0.02286903  0.004005436
2007-07-20  0.02522142  0.002202455
2007-07-27 -0.07969033 -0.003802426
2007-08-03 -0.01849051 -0.002685547
2007-08-10 -0.03965627 -0.004550623
2007-08-17 -0.04129406  0.007384225

In [32]:
VARselect(bekk7data,type = "const",lag.max = 4)

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     4      1      1      4 

$criteria
                   1             2             3             4
AIC(n) -1.403072e+01 -1.403096e+01 -1.402719e+01 -1.403985e+01
HQ(n)  -1.401819e+01 -1.401007e+01 -1.399794e+01 -1.400225e+01
SC(n)  -1.399796e+01 -1.397635e+01 -1.395073e+01 -1.394155e+01
FPE(n)  8.063686e-07  8.061794e-07  8.092252e-07  7.990419e-07

In [33]:
var_bekk7<-VAR(bekk7data,p = 4,type = "const")
summary(var_bekk7)


VAR Estimation Results:
Endogenous variables: usc, ghsusd 
Deterministic variables: const 
Sample size: 874 
Log Likelihood: 3673.112 
Roots of the characteristic polynomial:
0.6517 0.6517 0.5837 0.5837 0.3623 0.3623 0.3214 0.3214
Call:
VAR(y = bekk7data, p = 4, type = "const")


Estimation results for equation usc: 
usc = usc.l1 + ghsusd.l1 + usc.l2 + ghsusd.l2 + usc.l3 + ghsusd.l3 + usc.l4 + ghsusd.l4 + const 

           Estimate Std. Error t value Pr(>|t|)
usc.l1     0.044454   0.034887   1.274    0.203
ghsusd.l1  0.087055   0.058971   1.476    0.140
usc.l2    -0.016276   0.034873  -0.467    0.641
ghsusd.l2 -0.045643   0.059094  -0.772    0.440
usc.l3    -0.013705   0.034960  -0.392    0.695
ghsusd.l3 -0.073783   0.059096  -1.249    0.212
usc.l4    -0.012121   0.035092  -0.345    0.730
ghsusd.l4  0.022628   0.059088   0.383    0.702
const      0.001610   0.001379   1.168    0.243


Residual standard error: 0.03938 on 865 degrees of freedom
Multiple R-Squared: 0.00697,	Adjusted R-s

In [34]:
res_bekk7 <- residuals(var_bekk7)
res_bekk7 <- as.data.frame(res_bekk7)

In [35]:
ind_var7 <- index(bekk7data)[-c(1:4)]

In [36]:
res_bekk7 <- xts(res_bekk7,order.by = ind_var7)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk7_fit <- bekk_fit(spec = bekk_spec,data = res_bekk7)
bekk7_fit$A
bekk7_fit$A_t
bekk7_fit$G
bekk7_fit$G_t

[,1]       [,2]       
[1,] 0.25690732 -0.02768364
[2,] 0.02877185  0.68035627

[,1]      [,2]     
[1,] 12.865982 -2.976606
[2,]  0.525831 40.481189

[,1]          [,2]      
[1,]  0.9556232347 0.00688827
[2,] -0.0001395951 0.73575589

[,1]         [,2]     
[1,] 96.310494649  1.018124
[2,] -0.004012118 50.087061

### VAR-BEKK Model Table for US Cocoa - GHSUSD

In [37]:
bekk7 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi13","phi14","phi15","phi16","phi17","phi18","phi21","phi22","phi23","phi24","phi25","phi26","phi27","phi28","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk7)$varresult$usc$coefficients["const","Estimate"],summary(var_bekk7)$varresult$ghsusd$coefficients["const","Estimate"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l1","Estimate"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l1","Estimate"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l2","Estimate"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l2","Estimate"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l3","Estimate"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l3","Estimate"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l4","Estimate"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l4","Estimate"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l1","Estimate"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l1","Estimate"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l2","Estimate"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l2","Estimate"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l3","Estimate"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l3","Estimate"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l4","Estimate"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l4","Estimate"],
                                   bekk7_fit$A[1,1],bekk7_fit$A[1,2],bekk7_fit$A[2,1],bekk7_fit$A[2,2],bekk7_fit$G[1,1],bekk7_fit$G[1,2],bekk7_fit$G[2,1],bekk7_fit$G[2,2]),
                   Std_error = c(summary(var_bekk7)$varresult$usc$coefficients["const","Std. Error"],summary(var_bekk7)$varresult$ghsusd$coefficients["const","Std. Error"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l1","Std. Error"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l1","Std. Error"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l2","Std. Error"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l2","Std. Error"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l3","Std. Error"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l3","Std. Error"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l4","Std. Error"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l4","Std. Error"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l1","Std. Error"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l1","Std. Error"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l2","Std. Error"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l2","Std. Error"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l3","Std. Error"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l3","Std. Error"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l4","Std. Error"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l4","Std. Error"],
                                   bekk7_fit$A_sd[1,1],bekk7_fit$A_sd[1,2],bekk7_fit$A_sd[2,1],bekk7_fit$A_sd[2,2],bekk7_fit$G_sd[1,1],bekk7_fit$G_sd[1,2],bekk7_fit$G_sd[2,1],bekk7_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk7)$varresult$usc$coefficients["const","t value"],summary(var_bekk7)$varresult$ghsusd$coefficients["const","t value"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l1","t value"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l1","t value"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l2","t value"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l2","t value"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l3","t value"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l3","t value"],
                                   summary(var_bekk7)$varresult$usc$coefficients["usc.l4","t value"],summary(var_bekk7)$varresult$usc$coefficients["ghsusd.l4","t value"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l1","t value"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l1","t value"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l2","t value"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l2","t value"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l3","t value"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l3","t value"],
                                   summary(var_bekk7)$varresult$ghsusd$coefficients["usc.l4","t value"],summary(var_bekk7)$varresult$ghsusd$coefficients["ghsusd.l4","t value"],
                                   bekk7_fit$A_t[1,1],bekk7_fit$A_t[1,2],bekk7_fit$A_t[2,1],bekk7_fit$A_t[2,2],bekk7_fit$G_t[1,1],bekk7_fit$G_t[1,2],bekk7_fit$G_t[2,1],bekk7_fit$G_t[2,2]))

bekk7$Significant_at_5p_level[abs(bekk7$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk7$Significant_at_5p_level[abs(bekk7$T_value) > 1.96 & abs(bekk7$T_value) < 2.58] <- "Stat significant at 5%"
bekk7$Significant_at_5p_level[abs(bekk7$T_value) > 1.645 & abs(bekk7$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk7$Significant_at_5p_level[abs(bekk7$T_value) <= 1.645] <- "Not Statistically Significant"
bekk7

Parameters Coefficient   Std_error   T_value     
1  mu10        0.0016102848 0.001378765  1.167917868
2  mu20       -0.0031509437 0.000786509 -4.006239789
3  phi11       0.0444541187 0.034886740  1.274241111
4  phi12       0.0870554164 0.058971111  1.476238358
5  phi13      -0.0162759419 0.034872999 -0.466720458
6  phi14      -0.0456429371 0.059093960 -0.772379058
7  phi15      -0.0137046237 0.034960046 -0.392008174
8  phi16      -0.0737833578 0.059096411 -1.248525196
9  phi17      -0.0121206382 0.035091702 -0.345398979
10 phi18       0.0226275773 0.059088009  0.382947028
11 phi21       0.0084540917 0.019900945  0.424808543
12 phi22       0.0632710880 0.033639740  1.880843556
13 phi23       0.0049145536 0.019893107  0.247048072
14 phi24       0.1086151074 0.033709818  3.222061492
15 phi25       0.0009096331 0.019942762  0.045612194
16 phi26      -0.0476565926 0.033711216 -1.413671704
17 phi27      -0.0086907621 0.020017865 -0.434150301
18 phi28      -0.1456046636 0.033706423 -4.319789793
19 a11         0.2569073215 0.019967953 12.865982146
20 a12        -0.0276836415 0.009300405 -2.976606149
21 a21         0.0287718464 0.054716912  0.525830959
22 a22         0.6803562700 0.016806727 40.481188579
23 g11         0.9556232347 0.009922317 96.310494649
24 g12         0.0068882699 0.006765647  1.018124318
25 g21        -0.0001395951 0.034793365 -0.004012118
26 g22         0.7357558856 0.014689540 50.087060694
   Significant_at_5p_level      
1  Not Statistically Significant
2  Stat significant at 1%       
3  Not Statistically Significant
4  Not Statistically Significant
5  Not Statistically Significant
6  Not Statistically Significant
7  Not Statistically Significant
8  Not Statistically Significant
9  Not Statistically Significant
10 Not Statistically Significant
11 Not Statistically Significant
12 Stat significant at 10%      
13 Not Statistically Significant
14 Stat significant at 1%       
15 Not Statistically Significant
16 Not Statistically Significant
17 Not Statistically Significant
18 Stat significant at 1%       
19 Stat significant at 1%       
20 Stat significant at 1%       
21 Not Statistically Significant
22 Stat significant at 1%       
23 Stat significant at 1%       
24 Not Statistically Significant
25 Not Statistically Significant
26 Stat significant at 1%

In [38]:
causality(var_bekk7,cause = "usc")$Granger
causality(var_bekk7,cause = "ghsusd")$Granger


	Granger causality H0: usc do not Granger-cause ghsusd

data:  VAR object var_bekk7
F-Test = 0.10809, df1 = 4, df2 = 1730, p-value = 0.9797



	Granger causality H0: ghsusd do not Granger-cause usc

data:  VAR object var_bekk7
F-Test = 0.99979, df1 = 4, df2 = 1730, p-value = 0.4064


# (iii) VAR-BEKK Models for London Cocoa

In [39]:
l_w <- na.omit(merge(cr_w[,2],fr_w[,c(4:6)]))
str(l_w)
head(l_w)

An xts object on 2007-07-13 / 2024-05-03 containing: 
  Data:    double [878, 4]
  Columns: lc, usdgbp, eurgbp, chfgbp
  Index:   Date [878] (TZ: "UTC")
  xts Attributes:
    $ ret_type        : chr "log"
    $ coredata_content: chr "logReturn"


                     lc       usdgbp        eurgbp        chfgbp
2007-07-13 -0.034778360 -0.012031893 -0.0009595159  0.0009570421
2007-07-20  0.003623192 -0.010223993 -0.0067425143 -0.0088982748
2007-07-27 -0.061529190  0.015297055  0.0008917293  0.0087979629
2007-08-03 -0.036225204 -0.007721262  0.0031888492  0.0074008865
2007-08-10 -0.027288202  0.007822461  0.0022187717  0.0010801929
2007-08-17 -0.023847683  0.021424385  0.0050110643  0.0136908894

## (a) VAR-BEKK: London Cocoa-USDGBP

In [40]:
bekk4data <- l_w[,c(1,2)]
head(bekk4data)

                     lc       usdgbp
2007-07-13 -0.034778360 -0.012031893
2007-07-20  0.003623192 -0.010223993
2007-07-27 -0.061529190  0.015297055
2007-08-03 -0.036225204 -0.007721262
2007-08-10 -0.027288202  0.007822461
2007-08-17 -0.023847683  0.021424385

In [41]:
VARselect(bekk4data,type = "const")

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.528940e+01 -1.528683e+01 -1.528314e+01 -1.527590e+01 -1.526970e+01
HQ(n)  -1.527679e+01 -1.526582e+01 -1.525372e+01 -1.523808e+01 -1.522347e+01
SC(n)  -1.525645e+01 -1.523192e+01 -1.520626e+01 -1.517707e+01 -1.514889e+01
FPE(n)  2.290330e-07  2.296226e-07  2.304723e-07  2.321454e-07  2.335910e-07
                   6             7             8             9            10
AIC(n) -1.526725e+01 -1.526265e+01 -1.526297e+01 -1.526541e+01 -1.526027e+01
HQ(n)  -1.521262e+01 -1.519961e+01 -1.519153e+01 -1.518556e+01 -1.517202e+01
SC(n)  -1.512448e+01 -1.509791e+01 -1.507627e+01 -1.505675e+01 -1.502965e+01
FPE(n)  2.341642e-07  2.352450e-07  2.351696e-07  2.345981e-07  2.358073e-07

In [42]:
var_bekk4<-VAR(bekk4data,p = 1,type = "const")
res_bekk4 <- residuals(var_bekk4)
res_bekk4 <- as.data.frame(res_bekk4)

In [43]:
ind_var4 <- index(bekk4data)[-1]
str(ind_var4)

 Date[1:877], format: "2007-07-20" "2007-07-27" "2007-08-03" "2007-08-10" "2007-08-17" ...


In [44]:
res_bekk4 <- xts(res_bekk4,order.by = ind_var4)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk4_fit <- bekk_fit(spec = bekk_spec,data = res_bekk4)

In [45]:
bekk4_fit$A
bekk4_fit$A_t
bekk4_fit$G
bekk4_fit$G_t

[,1]       [,2]         
[1,] 0.30148954 -0.0002374186
[2,] 0.06221208  0.3024651071

[,1]       [,2]       
[1,] 12.9062706 -0.02206638
[2,]  0.9448622 12.43010630

[,1]       [,2]        
[1,] 0.94504651 -0.001332668
[2,] 0.03593896  0.933662631

[,1]      [,2]      
[1,] 87.795603 -0.2853983
[2,]  1.033471 77.7366779

### VAR-BEKK Model Table for London Cocoa - USDGBP

In [46]:
bekk4 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk4)$varresult$lc$coefficients["const","Estimate"],summary(var_bekk4)$varresult$usdgbp$coefficients["const","Estimate"],
                                   summary(var_bekk4)$varresult$lc$coefficients["lc.l1","Estimate"],summary(var_bekk4)$varresult$lc$coefficients["usdgbp.l1","Estimate"],
                                   summary(var_bekk4)$varresult$usdgbp$coefficients["lc.l1","Estimate"],summary(var_bekk4)$varresult$usdgbp$coefficients["usdgbp.l1","Estimate"],
                                   bekk4_fit$A[1,1],bekk4_fit$A[1,2],bekk4_fit$A[2,1],bekk4_fit$A[2,2],bekk4_fit$G[1,1],bekk4_fit$G[1,2],bekk4_fit$G[2,1],bekk4_fit$G[2,2]),
                   Std_error = c(summary(var_bekk4)$varresult$lc$coefficients["const","Std. Error"],summary(var_bekk4)$varresult$usdgbp$coefficients["const","Std. Error"],
                                   summary(var_bekk4)$varresult$lc$coefficients["lc.l1","Std. Error"],summary(var_bekk4)$varresult$lc$coefficients["usdgbp.l1","Std. Error"],
                                   summary(var_bekk4)$varresult$usdgbp$coefficients["lc.l1","Std. Error"],summary(var_bekk4)$varresult$usdgbp$coefficients["usdgbp.l1","Std. Error"],
                                   bekk4_fit$A_sd[1,1],bekk4_fit$A_sd[1,2],bekk4_fit$A_sd[2,1],bekk4_fit$A_sd[2,2],bekk4_fit$G_sd[1,1],bekk4_fit$G_sd[1,2],bekk4_fit$G_sd[2,1],bekk4_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk4)$varresult$lc$coefficients["const","t value"],summary(var_bekk4)$varresult$usdgbp$coefficients["const","t value"],
                                   summary(var_bekk4)$varresult$lc$coefficients["lc.l1","t value"],summary(var_bekk4)$varresult$lc$coefficients["usdgbp.l1","t value"],
                                   summary(var_bekk4)$varresult$usdgbp$coefficients["lc.l1","t value"],summary(var_bekk4)$varresult$usdgbp$coefficients["usdgbp.l1","t value"],
                                   bekk4_fit$A_t[1,1],bekk4_fit$A_t[1,2],bekk4_fit$A_t[2,1],bekk4_fit$A_t[2,2],bekk4_fit$G_t[1,1],bekk4_fit$G_t[1,2],bekk4_fit$G_t[2,1],bekk4_fit$G_t[2,2]))

bekk4$Significant_at_5p_level[abs(bekk4$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk4$Significant_at_5p_level[abs(bekk4$T_value) > 1.96 & abs(bekk4$T_value) < 2.58] <- "Stat significant at 5%"
bekk4$Significant_at_5p_level[abs(bekk4$T_value) > 1.645 & abs(bekk4$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk4$Significant_at_5p_level[abs(bekk4$T_value) <= 1.645] <- "Not Statistically Significant"
bekk4

Parameters Coefficient   Std_error    T_value    
1  mu10        0.0018514327 0.0011890602  1.55705548
2  mu20        0.0006089563 0.0004596221  1.32490631
3  phi11       0.0826751669 0.0348861830  2.36985419
4  phi12       0.0803964216 0.0874503048  0.91933838
5  phi21      -0.0170955183 0.0134849869 -1.26774452
6  phi22      -0.0324427214 0.0338032457 -0.95975167
7  a11         0.3014895368 0.0233599268 12.90627061
8  a12        -0.0002374186 0.0107592905 -0.02206638
9  a21         0.0622120833 0.0658424902  0.94486225
10 a22         0.3024651071 0.0243332679 12.43010630
11 g11         0.9450465100 0.0107641668 87.79560263
12 g12        -0.0013326681 0.0046695024 -0.28539832
13 g21         0.0359389562 0.0347749950  1.03347121
14 g22         0.9336626312 0.0120105805 77.73667793
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Stat significant at 5%       
4  Not Statistically Significant
5  Not Statistically Significant
6  Not Statistically Significant
7  Stat significant at 1%       
8  Not Statistically Significant
9  Not Statistically Significant
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Not Statistically Significant
13 Not Statistically Significant
14 Stat significant at 1%

In [47]:
causality(var_bekk4,cause = "lc")$Granger
causality(var_bekk4,cause = "usdgbp")$Granger


	Granger causality H0: lc do not Granger-cause usdgbp

data:  VAR object var_bekk4
F-Test = 1.6072, df1 = 1, df2 = 1748, p-value = 0.2051



	Granger causality H0: usdgbp do not Granger-cause lc

data:  VAR object var_bekk4
F-Test = 0.84518, df1 = 1, df2 = 1748, p-value = 0.358


## (b) VAR-BEKK: London Cocoa-EURGBP

In [48]:
bekk5data <- l_w[,c(1,3)]
head(bekk5data)


                     lc        eurgbp
2007-07-13 -0.034778360 -0.0009595159
2007-07-20  0.003623192 -0.0067425143
2007-07-27 -0.061529190  0.0008917293
2007-08-03 -0.036225204  0.0031888492
2007-08-10 -0.027288202  0.0022187717
2007-08-17 -0.023847683  0.0050110643

In [49]:
VARselect(bekk5data,type = "const")

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.560420e+01 -1.560158e+01 -1.559629e+01 -1.558989e+01 -1.558761e+01
HQ(n)  -1.559159e+01 -1.558057e+01 -1.556687e+01 -1.555207e+01 -1.554139e+01
SC(n)  -1.557125e+01 -1.554667e+01 -1.551942e+01 -1.549105e+01 -1.546681e+01
FPE(n)  1.671797e-07  1.676181e-07  1.685070e-07  1.695889e-07  1.699758e-07
                   6             7             8             9            10
AIC(n) -1.558186e+01 -1.557732e+01 -1.557749e+01 -1.557370e+01 -1.556661e+01
HQ(n)  -1.552723e+01 -1.551429e+01 -1.550605e+01 -1.549385e+01 -1.547836e+01
SC(n)  -1.543909e+01 -1.541259e+01 -1.539080e+01 -1.536504e+01 -1.533599e+01
FPE(n)  1.709566e-07  1.717346e-07  1.717057e-07  1.723591e-07  1.735859e-07

In [50]:
var_bekk5<-VAR(bekk5data,p = 1,type = "const")
res_bekk5 <- residuals(var_bekk5)
res_bekk5 <- as.data.frame(res_bekk5)

In [51]:
ind_var5 <- index(bekk5data)[-1]

In [52]:
res_bekk5 <- xts(res_bekk5,order.by = ind_var5)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk5_fit <- bekk_fit(spec = bekk_spec,data = res_bekk5)
bekk5_fit$A
bekk5_fit$A_t
bekk5_fit$G
bekk5_fit$G_t

[,1]      [,2]         
[1,] 0.3104282 -0.0001425747
[2,] 0.1016647  0.2648040380

[,1]      [,2]       
[1,] 12.954530 -0.01581247
[2,]  1.389303 13.33279233

[,1]        [,2]        
[1,]  0.94045862 0.0009128379
[2,] -0.00383866 0.9520306034

[,1]       [,2]       
[1,] 79.9663263   0.2303922
[2,] -0.1085734 117.8423083

### VAR-BEKK Model Table for London Cocoa-EURGBP

In [53]:
bekk5 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk5)$varresult$lc$coefficients["const","Estimate"],summary(var_bekk5)$varresult$eurgbp$coefficients["const","Estimate"],
                                   summary(var_bekk5)$varresult$lc$coefficients["lc.l1","Estimate"],summary(var_bekk5)$varresult$lc$coefficients["eurgbp.l1","Estimate"],
                                   summary(var_bekk5)$varresult$eurgbp$coefficients["lc.l1","Estimate"],summary(var_bekk5)$varresult$eurgbp$coefficients["eurgbp.l1","Estimate"],
                                   bekk5_fit$A[1,1],bekk5_fit$A[1,2],bekk5_fit$A[2,1],bekk5_fit$A[2,2],bekk5_fit$G[1,1],bekk5_fit$G[1,2],bekk5_fit$G[2,1],bekk5_fit$G[2,2]),
                   Std_error = c(summary(var_bekk5)$varresult$lc$coefficients["const","Std. Error"],summary(var_bekk5)$varresult$eurgbp$coefficients["const","Std. Error"],
                                   summary(var_bekk5)$varresult$lc$coefficients["lc.l1","Std. Error"],summary(var_bekk5)$varresult$lc$coefficients["eurgbp.l1","Std. Error"],
                                   summary(var_bekk5)$varresult$eurgbp$coefficients["lc.l1","Std. Error"],summary(var_bekk5)$varresult$eurgbp$coefficients["eurgbp.l1","Std. Error"],
                                   bekk5_fit$A_sd[1,1],bekk5_fit$A_sd[1,2],bekk5_fit$A_sd[2,1],bekk5_fit$A_sd[2,2],bekk5_fit$G_sd[1,1],bekk5_fit$G_sd[1,2],bekk5_fit$G_sd[2,1],bekk5_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk5)$varresult$lc$coefficients["const","t value"],summary(var_bekk5)$varresult$eurgbp$coefficients["const","t value"],
                                   summary(var_bekk5)$varresult$lc$coefficients["lc.l1","t value"],summary(var_bekk5)$varresult$lc$coefficients["eurgbp.l1","t value"],
                                   summary(var_bekk5)$varresult$eurgbp$coefficients["lc.l1","t value"],summary(var_bekk5)$varresult$eurgbp$coefficients["eurgbp.l1","t value"],
                                   bekk5_fit$A_t[1,1],bekk5_fit$A_t[1,2],bekk5_fit$A_t[2,1],bekk5_fit$A_t[2,2],bekk5_fit$G_t[1,1],bekk5_fit$G_t[1,2],bekk5_fit$G_t[2,1],bekk5_fit$G_t[2,2]))

bekk5$Significant_at_5p_level[abs(bekk5$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk5$Significant_at_5p_level[abs(bekk5$T_value) > 1.96 & abs(bekk5$T_value) < 2.58] <- "Stat significant at 5%"
bekk5$Significant_at_5p_level[abs(bekk5$T_value) > 1.645 & abs(bekk5$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk5$Significant_at_5p_level[abs(bekk5$T_value) <= 1.645] <- "Not Statistically Significant"
bekk5

Parameters Coefficient   Std_error    T_value     
1  mu10        0.0018863400 0.0011888569   1.58668387
2  mu20        0.0003241925 0.0003955541   0.81959085
3  phi11       0.0824471731 0.0352821785   2.33679372
4  phi12       0.0346797733 0.1026584211   0.33781713
5  phi21      -0.0196322795 0.0117390170  -1.67239552
6  phi22      -0.0315928913 0.0341563080  -0.92495042
7  a11         0.3104282273 0.0239629090  12.95453017
8  a12        -0.0001425747 0.0090166029  -0.01581247
9  a21         0.1016647122 0.0731767635   1.38930321
10 a22         0.2648040380 0.0198611087  13.33279233
11 g11         0.9404586249 0.0117606831  79.96632630
12 g12         0.0009128379 0.0039621042   0.23039221
13 g21        -0.0038386596 0.0353554320  -0.10857340
14 g22         0.9520306034 0.0080788523 117.84230830
   Significant_at_5p_level      
1  Not Statistically Significant
2  Not Statistically Significant
3  Stat significant at 5%       
4  Not Statistically Significant
5  Stat significant at 10%      
6  Not Statistically Significant
7  Stat significant at 1%       
8  Not Statistically Significant
9  Not Statistically Significant
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Not Statistically Significant
13 Not Statistically Significant
14 Stat significant at 1%

In [54]:
causality(var_bekk5,cause = "lc")$Granger
causality(var_bekk5,cause = "eurgbp")$Granger


	Granger causality H0: lc do not Granger-cause eurgbp

data:  VAR object var_bekk5
F-Test = 2.7969, df1 = 1, df2 = 1748, p-value = 0.09463



	Granger causality H0: eurgbp do not Granger-cause lc

data:  VAR object var_bekk5
F-Test = 0.11412, df1 = 1, df2 = 1748, p-value = 0.7355


## (c) VAR-BEKK: London Cocoa-CHFGBP

In [55]:
bekk6data <- l_w[,c(1,4)]
head(bekk6data)

                     lc        chfgbp
2007-07-13 -0.034778360  0.0009570421
2007-07-20  0.003623192 -0.0088982748
2007-07-27 -0.061529190  0.0087979629
2007-08-03 -0.036225204  0.0074008865
2007-08-10 -0.027288202  0.0010801929
2007-08-17 -0.023847683  0.0136908894

In [56]:
VARselect(bekk6data,type = "const")

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4             5
AIC(n) -1.509909e+01 -1.509445e+01 -1.509008e+01 -1.508388e+01 -1.508318e+01
HQ(n)  -1.508648e+01 -1.507344e+01 -1.506067e+01 -1.504606e+01 -1.503695e+01
SC(n)  -1.506614e+01 -1.503954e+01 -1.501321e+01 -1.498504e+01 -1.496237e+01
FPE(n)  2.770439e-07  2.783323e-07  2.795503e-07  2.812904e-07  2.814888e-07
                   6             7             8             9            10
AIC(n) -1.507823e+01 -1.507704e+01 -1.507692e+01 -1.507372e+01 -1.507039e+01
HQ(n)  -1.502360e+01 -1.501400e+01 -1.500548e+01 -1.499387e+01 -1.498214e+01
SC(n)  -1.493546e+01 -1.491231e+01 -1.489023e+01 -1.486506e+01 -1.483977e+01
FPE(n)  2.828848e-07  2.832224e-07  2.832566e-07  2.841674e-07  2.851161e-07

In [57]:
var_bekk6<-VAR(bekk6data,p = 1,type = "const")
res_bekk6 <- residuals(var_bekk6)
res_bekk6 <- as.data.frame(res_bekk6)

In [58]:
ind_var6 <- index(bekk6data)[-1]

In [59]:
res_bekk6 <- xts(res_bekk6,order.by = ind_var6)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk6_fit <- bekk_fit(spec = bekk_spec,data = res_bekk6)
bekk6_fit$A
bekk6_fit$A_t
bekk6_fit$G
bekk6_fit$G_t

[,1]      [,2]       
[1,] 0.3234650 -0.02278619
[2,] 0.1553224  0.26616786

[,1]      [,2]     
[1,] 12.741920 -1.178076
[2,]  2.113982  6.868999

[,1]        [,2]       
[1,]  0.93855209 0.005093478
[2,] -0.05496428 0.874862465

[,1]       [,2]      
[1,] 75.9138626  0.5256057
[2,] -0.7749542 17.6054693

### VAR-BEKK Model Table for London Cocoa-CHFGBP

In [60]:
bekk6 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk6)$varresult$lc$coefficients["const","Estimate"],summary(var_bekk6)$varresult$chfgbp$coefficients["const","Estimate"],
                                   summary(var_bekk6)$varresult$lc$coefficients["lc.l1","Estimate"],summary(var_bekk6)$varresult$lc$coefficients["chfgbp.l1","Estimate"],
                                   summary(var_bekk6)$varresult$chfgbp$coefficients["lc.l1","Estimate"],summary(var_bekk6)$varresult$chfgbp$coefficients["chfgbp.l1","Estimate"],
                                   bekk6_fit$A[1,1],bekk6_fit$A[1,2],bekk6_fit$A[2,1],bekk6_fit$A[2,2],bekk6_fit$G[1,1],bekk6_fit$G[1,2],bekk6_fit$G[2,1],bekk6_fit$G[2,2]),
                   Std_error = c(summary(var_bekk6)$varresult$lc$coefficients["const","Std. Error"],summary(var_bekk6)$varresult$chfgbp$coefficients["const","Std. Error"],
                                   summary(var_bekk6)$varresult$lc$coefficients["lc.l1","Std. Error"],summary(var_bekk6)$varresult$lc$coefficients["chfgbp.l1","Std. Error"],
                                   summary(var_bekk6)$varresult$chfgbp$coefficients["lc.l1","Std. Error"],summary(var_bekk6)$varresult$chfgbp$coefficients["chfgbp.l1","Std. Error"],
                                   bekk6_fit$A_sd[1,1],bekk6_fit$A_sd[1,2],bekk6_fit$A_sd[2,1],bekk6_fit$A_sd[2,2],bekk6_fit$G_sd[1,1],bekk6_fit$G_sd[1,2],bekk6_fit$G_sd[2,1],bekk6_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk6)$varresult$lc$coefficients["const","t value"],summary(var_bekk6)$varresult$chfgbp$coefficients["const","t value"],
                                   summary(var_bekk6)$varresult$lc$coefficients["lc.l1","t value"],summary(var_bekk6)$varresult$lc$coefficients["chfgbp.l1","t value"],
                                   summary(var_bekk6)$varresult$chfgbp$coefficients["lc.l1","t value"],summary(var_bekk6)$varresult$chfgbp$coefficients["chfgbp.l1","t value"],
                                   bekk6_fit$A_t[1,1],bekk6_fit$A_t[1,2],bekk6_fit$A_t[2,1],bekk6_fit$A_t[2,2],bekk6_fit$G_t[1,1],bekk6_fit$G_t[1,2],bekk6_fit$G_t[2,1],bekk6_fit$G_t[2,2]))

bekk6$Significant_at_5p_level[abs(bekk6$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk6$Significant_at_5p_level[abs(bekk6$T_value) > 1.96 & abs(bekk6$T_value) < 2.58] <- "Stat significant at 5%"
bekk6$Significant_at_5p_level[abs(bekk6$T_value) > 1.645 & abs(bekk6$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk6$Significant_at_5p_level[abs(bekk6$T_value) <= 1.645] <- "Not Statistically Significant"
bekk6

Parameters Coefficient   Std_error    T_value   
1  mu10        0.0019363986 0.0011901400  1.6270343
2  mu20        0.0009500008 0.0005055014  1.8793238
3  phi11       0.0863778175 0.0349677743  2.4702120
4  phi12      -0.0575559726 0.0797790081 -0.7214426
5  phi21      -0.0182540848 0.0148522516 -1.2290449
6  phi22      -0.0374252051 0.0338854252 -1.1044632
7  a11         0.3234649720 0.0253858891 12.7419201
8  a12        -0.0227861873 0.0193418612 -1.1780762
9  a21         0.1553224018 0.0734738532  2.1139820
10 a22         0.2661678596 0.0387491477  6.8689991
11 g11         0.9385520946 0.0123633822 75.9138626
12 g12         0.0050934785 0.0096906839  0.5256057
13 g21        -0.0549642824 0.0709258489 -0.7749542
14 g22         0.8748624653 0.0496926523 17.6054693
   Significant_at_5p_level      
1  Not Statistically Significant
2  Stat significant at 10%      
3  Stat significant at 5%       
4  Not Statistically Significant
5  Not Statistically Significant
6  Not Statistically Significant
7  Stat significant at 1%       
8  Not Statistically Significant
9  Stat significant at 5%       
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Not Statistically Significant
13 Not Statistically Significant
14 Stat significant at 1%

In [61]:
causality(var_bekk6,cause = "lc")$Granger
causality(var_bekk6,cause = "chfgbp")$Granger


	Granger causality H0: lc do not Granger-cause chfgbp

data:  VAR object var_bekk6
F-Test = 1.5106, df1 = 1, df2 = 1748, p-value = 0.2192



	Granger causality H0: chfgbp do not Granger-cause lc

data:  VAR object var_bekk6
F-Test = 0.52048, df1 = 1, df2 = 1748, p-value = 0.4707


## (d) VAR-BEKK Model for London Cocoa - GHSGBP

In [62]:
bekk8data <- na.omit(merge(cr_w[,2],fr_w[,8]))
head(bekk8data)

                     lc       ghsgbp
2007-07-13 -0.034778360 -0.008009262
2007-07-20  0.003623192 -0.008376197
2007-07-27 -0.061529190  0.011804209
2007-08-03 -0.036225204 -0.009823491
2007-08-10 -0.027288202  0.002725996
2007-08-17 -0.023847683  0.028262443

In [63]:
VARselect(bekk8data,type = "const",lag.max = 4)

$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     1      1      1      1 

$criteria
                   1             2             3             4
AIC(n) -1.391223e+01 -1.390688e+01 -1.390022e+01 -1.390954e+01
HQ(n)  -1.389969e+01 -1.388599e+01 -1.387097e+01 -1.387193e+01
SC(n)  -1.387946e+01 -1.385227e+01 -1.382376e+01 -1.381124e+01
FPE(n)  9.078124e-07  9.126797e-07  9.187800e-07  9.102604e-07

In [64]:
var_bekk8<-VAR(bekk8data,p = 1,type = "const")
res_bekk8 <- residuals(var_bekk8)
res_bekk8 <- as.data.frame(res_bekk8)
summary(var_bekk8)


VAR Estimation Results:
Endogenous variables: lc, ghsgbp 
Deterministic variables: const 
Sample size: 877 
Log Likelihood: 3618.355 
Roots of the characteristic polynomial:
0.07147 0.07147
Call:
VAR(y = bekk8data, p = 1, type = "const")


Estimation results for equation lc: 
lc = lc.l1 + ghsgbp.l1 + const 

          Estimate Std. Error t value Pr(>|t|)  
lc.l1     0.083684   0.034791   2.405   0.0164 *
ghsgbp.l1 0.081355   0.043751   1.859   0.0633 .
const     0.002097   0.001192   1.760   0.0788 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


Residual standard error: 0.03505 on 874 degrees of freedom
Multiple R-Squared: 0.01056,	Adjusted R-squared: 0.008296 
F-statistic: 4.664 on 2 and 874 DF,  p-value: 0.009663 


Estimation results for equation ghsgbp: 
ghsgbp = lc.l1 + ghsgbp.l1 + const 

            Estimate Std. Error t value Pr(>|t|)  
lc.l1     -0.0130876  0.0268671  -0.487   0.6263  
ghsgbp.l1  0.0483105  0.0337863   1.430   0.1531  
const     -0.0023

In [65]:
ind_var8 <- index(bekk8data)[-1]

In [66]:
res_bekk8 <- xts(res_bekk8,order.by = ind_var8)
bekk_spec <- bekk_spec(model = list(type = "bekk",asymmetric = F))
bekk8_fit <- bekk_fit(spec = bekk_spec,data = res_bekk8)
bekk8_fit$A
bekk8_fit$A_t
bekk8_fit$G
bekk8_fit$G_t

[,1]        [,2]       
[1,] 0.266110679 -0.02001824
[2,] 0.005395679  0.64796087

[,1]       [,2]     
[1,] 13.2121534 -1.133803
[2,]  0.1152528 26.687812

[,1]        [,2]       
[1,] 0.956478154 0.005139544
[2,] 0.001962402 0.754858797

[,1]         [,2]      
[1,] 110.16416748  0.3619349
[2,]   0.06344733 32.4602781

### VAR-BEKK Model Table for London Cocoa - GHSGBP

In [67]:
bekk8 <- data.frame(Parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22"),
                   Coefficient = c(summary(var_bekk8)$varresult$lc$coefficients["const","Estimate"],summary(var_bekk8)$varresult$ghsgbp$coefficients["const","Estimate"],
                                   summary(var_bekk8)$varresult$lc$coefficients["lc.l1","Estimate"],summary(var_bekk8)$varresult$lc$coefficients["ghsgbp.l1","Estimate"],
                                   summary(var_bekk8)$varresult$ghsgbp$coefficients["lc.l1","Estimate"],summary(var_bekk8)$varresult$ghsgbp$coefficients["ghsgbp.l1","Estimate"],
                                   bekk8_fit$A[1,1],bekk8_fit$A[1,2],bekk8_fit$A[2,1],bekk8_fit$A[2,2],bekk8_fit$G[1,1],bekk8_fit$G[1,2],bekk8_fit$G[2,1],bekk8_fit$G[2,2]),
                   Std_error = c(summary(var_bekk8)$varresult$lc$coefficients["const","Std. Error"],summary(var_bekk8)$varresult$ghsgbp$coefficients["const","Std. Error"],
                                   summary(var_bekk8)$varresult$lc$coefficients["lc.l1","Std. Error"],summary(var_bekk8)$varresult$lc$coefficients["ghsgbp.l1","Std. Error"],
                                   summary(var_bekk8)$varresult$ghsgbp$coefficients["lc.l1","Std. Error"],summary(var_bekk8)$varresult$ghsgbp$coefficients["ghsgbp.l1","Std. Error"],
                                   bekk8_fit$A_sd[1,1],bekk8_fit$A_sd[1,2],bekk8_fit$A_sd[2,1],bekk8_fit$A_sd[2,2],bekk8_fit$G_sd[1,1],bekk8_fit$G_sd[1,2],bekk8_fit$G_sd[2,1],bekk8_fit$G_sd[2,2]),
                   T_value = c(summary(var_bekk8)$varresult$lc$coefficients["const","t value"],summary(var_bekk8)$varresult$ghsgbp$coefficients["const","t value"],
                                   summary(var_bekk8)$varresult$lc$coefficients["lc.l1","t value"],summary(var_bekk8)$varresult$lc$coefficients["ghsgbp.l1","t value"],
                                   summary(var_bekk8)$varresult$ghsgbp$coefficients["lc.l1","t value"],summary(var_bekk8)$varresult$ghsgbp$coefficients["ghsgbp.l1","t value"],
                                   bekk8_fit$A_t[1,1],bekk8_fit$A_t[1,2],bekk8_fit$A_t[2,1],bekk8_fit$A_t[2,2],bekk8_fit$G_t[1,1],bekk8_fit$G_t[1,2],bekk8_fit$G_t[2,1],bekk8_fit$G_t[2,2]))

bekk8$Significant_at_5p_level[abs(bekk8$T_value) >= 2.58 ] <- "Stat significant at 1%"
bekk8$Significant_at_5p_level[abs(bekk8$T_value) > 1.96 & abs(bekk8$T_value) < 2.58] <- "Stat significant at 5%"
bekk8$Significant_at_5p_level[abs(bekk8$T_value) > 1.645 & abs(bekk8$T_value) <= 1.96 ] <- "Stat significant at 10%"
bekk8$Significant_at_5p_level[abs(bekk8$T_value) <= 1.645] <- "Not Statistically Significant"
bekk8

Parameters Coefficient  Std_error    T_value     
1  mu10        0.002096975 0.0011916491   1.75972543
2  mu20       -0.002366809 0.0009202323  -2.57196915
3  phi11       0.083684469 0.0347913792   2.40532197
4  phi12       0.081355452 0.0437513415   1.85949618
5  phi21      -0.013087609 0.0268670953  -0.48712406
6  phi22       0.048310468 0.0337862853   1.42988399
7  a11         0.266110679 0.0201413555  13.21215339
8  a12        -0.020018243 0.0176558314  -1.13380347
9  a21         0.005395679 0.0468160412   0.11525278
10 a22         0.647960866 0.0242792803  26.68781191
11 g11         0.956478154 0.0086822982 110.16416748
12 g12         0.005139544 0.0142001878   0.36193494
13 g21         0.001962402 0.0309296281   0.06344733
14 g22         0.754858797 0.0232548469  32.46027814
   Significant_at_5p_level      
1  Stat significant at 10%      
2  Stat significant at 5%       
3  Stat significant at 5%       
4  Stat significant at 10%      
5  Not Statistically Significant
6  Not Statistically Significant
7  Stat significant at 1%       
8  Not Statistically Significant
9  Not Statistically Significant
10 Stat significant at 1%       
11 Stat significant at 1%       
12 Not Statistically Significant
13 Not Statistically Significant
14 Stat significant at 1%

In [68]:
causality(var_bekk8,cause = "lc")$Granger
causality(var_bekk8,cause = "ghsgbp")$Granger


	Granger causality H0: lc do not Granger-cause ghsgbp

data:  VAR object var_bekk8
F-Test = 0.23729, df1 = 1, df2 = 1748, p-value = 0.6262



	Granger causality H0: ghsgbp do not Granger-cause lc

data:  VAR object var_bekk8
F-Test = 3.4577, df1 = 1, df2 = 1748, p-value = 0.06312


# Summary of  spillovers for the weekly VAR-BEKK model

In [69]:
bekk_c <- rep(NA,14)
for(i in 1:14){
    bekk_c[i] = paste0(round(bekkc[i,2],4)," (",round(bekkc[i,3],4),")")
}

bekk_1 <- rep(NA,14)
for(i in 1:14){
    bekk_1[i] = paste0(round(bekk1[i,2],4)," (",round(bekk1[i,3],4),")")
}

bekk_2 <- rep(NA,14)
for(i in 1:14){
    bekk_2[i] = paste0(round(bekk2[i,2],4)," (",round(bekk2[i,3],4),")")
}

bekk_3 <- rep(NA,14)
for(i in 1:14){
    bekk_3[i] = paste0(round(bekk3[i,2],4)," (",round(bekk3[i,3],4),")")
}

bekk_4 <- rep(NA,14)
for(i in 1:14){
    bekk_4[i] = paste0(round(bekk4[i,2],4)," (",round(bekk4[i,3],4),")")
}

bekk_5 <- rep(NA,14)
for(i in 1:14){
    bekk_5[i] = paste0(round(bekk5[i,2],4)," (",round(bekk5[i,3],4),")")
}

bekk_6 <- rep(NA,14)
for(i in 1:14){
    bekk_6[i] = paste0(round(bekk6[i,2],4)," (",round(bekk6[i,3],4),")")
}

bekk_7 <- rep(NA,26)
for(i in 1:26){
    bekk_7[i] = paste0(round(bekk7[i,2],4)," (",round(bekk7[i,3],4),")")
}


bekk_8 <- rep(NA,14)
for(i in 1:14){
    bekk_8[i] = paste0(round(bekk8[i,2],4)," (",round(bekk8[i,3],4),")")
}

In [70]:
parameters = c("mu10","mu20","phi11","phi12","phi21","phi22","a11","a12","a21","a22","g11","g12","g21","g22")
parameters2 = c("mu10","mu20","phi11","phi12","phi13","phi14","phi15","phi16","phi17","phi18","phi21","phi22","phi23","phi24","phi25","phi26","phi27","phi28","a11","a12","a21","a22","g11","g12","g21","g22")

In [71]:
weekly_bekk1 <- data.frame("Parameters" = parameters,"BEKKC" = bekk_c,"BEKK1" = bekk_1,"BEKK2" = bekk_2,"BEKK3" = bekk_3,"BEKK4" = bekk_4,"BEKK5" = bekk_5,
                         "BEKK6" = bekk_6,"BEKK8" = bekk_8)
weekly_bekk2 <- data.frame("Parameters" = parameters2,"BEKK7" = bekk_7)

In [72]:
weekly_bekk1

Parameters BEKKC            BEKK1            BEKK2           
1  mu10       0.0013 (0.0013)  0.0015 (0.0013)  0.0014 (0.0013) 
2  mu20       0.0019 (0.0012)  -3e-04 (4e-04)   -6e-04 (5e-04)  
3  phi11      -0.1553 (0.0782) 0.0458 (0.0364)  0.0555 (0.0361) 
4  phi12      0.2479 (0.0881)  -0.0372 (0.1096) -0.138 (0.1019) 
5  phi21      -0.073 (0.07)    -0.0072 (0.0118) 0.0137 (0.0124) 
6  phi22      0.1581 (0.0788)  -0.0028 (0.0355) -0.0439 (0.0351)
7  a11        0.0284 (0.0566)  0.3036 (0.0271)  0.301 (0.02)    
8  a12        -0.1379 (0.0503) -0.0082 (0.0105) -0.0032 (0.0095)
9  a21        0.2969 (0.0525)  0.0358 (0.0885)  -0.0207 (0.0824)
10 a22        0.4491 (0.0519)  0.2781 (0.0284)  0.3062 (0.0258) 
11 g11        0.9614 (0.0221)  0.9338 (0.0166)  0.9459 (0.0104) 
12 g12        -0.0194 (0.0204) 0.0071 (0.0054)  0.0029 (0.0041) 
13 g21        -0.0171 (0.0206) 0.0016 (0.0483)  -0.062 (0.0399) 
14 g22        0.9636 (0.0188)  0.9435 (0.0126)  0.9314 (0.0116) 
   BEKK3            BEKK4            BEKK5            BEKK6           
1  0.0015 (0.0013)  0.0019 (0.0012)  0.0019 (0.0012)  0.0019 (0.0012) 
2  3e-04 (5e-04)    6e-04 (5e-04)    3e-04 (4e-04)    0.001 (5e-04)   
3  0.0565 (0.0353)  0.0827 (0.0349)  0.0824 (0.0353)  0.0864 (0.035)  
4  -0.1863 (0.0917) 0.0804 (0.0875)  0.0347 (0.1027)  -0.0576 (0.0798)
5  -0.0029 (0.0133) -0.0171 (0.0135) -0.0196 (0.0117) -0.0183 (0.0149)
6  -0.0595 (0.0345) -0.0324 (0.0338) -0.0316 (0.0342) -0.0374 (0.0339)
7  0.2691 (0.0253)  0.3015 (0.0234)  0.3104 (0.024)   0.3235 (0.0254) 
8  -0.0266 (0.0134) -2e-04 (0.0108)  -1e-04 (0.009)   -0.0228 (0.0193)
9  0.1832 (0.0858)  0.0622 (0.0658)  0.1017 (0.0732)  0.1553 (0.0735) 
10 0.4367 (0.0256)  0.3025 (0.0243)  0.2648 (0.0199)  0.2662 (0.0387) 
11 0.9523 (0.0131)  0.945 (0.0108)   0.9405 (0.0118)  0.9386 (0.0124) 
12 0.0147 (0.0076)  -0.0013 (0.0047) 9e-04 (0.004)    0.0051 (0.0097) 
13 -0.0473 (0.0553) 0.0359 (0.0348)  -0.0038 (0.0354) -0.055 (0.0709) 
14 0.8608 (0.0226)  0.9337 (0.012)   0.952 (0.0081)   0.8749 (0.0497) 
   BEKK8           
1  0.0021 (0.0012) 
2  -0.0024 (9e-04) 
3  0.0837 (0.0348) 
4  0.0814 (0.0438) 
5  -0.0131 (0.0269)
6  0.0483 (0.0338) 
7  0.2661 (0.0201) 
8  -0.02 (0.0177)  
9  0.0054 (0.0468) 
10 0.648 (0.0243)  
11 0.9565 (0.0087) 
12 0.0051 (0.0142) 
13 0.002 (0.0309)  
14 0.7549 (0.0233)

In [73]:
weekly_bekk2

Parameters BEKK7           
1  mu10       0.0016 (0.0014) 
2  mu20       -0.0032 (8e-04) 
3  phi11      0.0445 (0.0349) 
4  phi12      0.0871 (0.059)  
5  phi13      -0.0163 (0.0349)
6  phi14      -0.0456 (0.0591)
7  phi15      -0.0137 (0.035) 
8  phi16      -0.0738 (0.0591)
9  phi17      -0.0121 (0.0351)
10 phi18      0.0226 (0.0591) 
11 phi21      0.0085 (0.0199) 
12 phi22      0.0633 (0.0336) 
13 phi23      0.0049 (0.0199) 
14 phi24      0.1086 (0.0337) 
15 phi25      9e-04 (0.0199)  
16 phi26      -0.0477 (0.0337)
17 phi27      -0.0087 (0.02)  
18 phi28      -0.1456 (0.0337)
19 a11        0.2569 (0.02)   
20 a12        -0.0277 (0.0093)
21 a21        0.0288 (0.0547) 
22 a22        0.6804 (0.0168) 
23 g11        0.9556 (0.0099) 
24 g12        0.0069 (0.0068) 
25 g21        -1e-04 (0.0348) 
26 g22        0.7358 (0.0147)

# Final VAR-BEKK Table for weekly data (Table 6.7)

In [74]:
weekly_bekk <- data.frame("Parameters" = parameters2,
                         "BEKKC"=c(bekk_c[1:4],rep(NA,6),bekk_c[5:6],rep(NA,6),bekk_c[7:14]),
                         "BEKK1"=c(bekk_1[1:4],rep(NA,6),bekk_1[5:6],rep(NA,6),bekk_1[7:14]),
                         "BEKK2"=c(bekk_2[1:4],rep(NA,6),bekk_2[5:6],rep(NA,6),bekk_2[7:14]),
                          "BEKK3"=c(bekk_3[1:4],rep(NA,6),bekk_3[5:6],rep(NA,6),bekk_3[7:14]),
                          "BEKK4"=c(bekk_4[1:4],rep(NA,6),bekk_4[5:6],rep(NA,6),bekk_4[7:14]),
                         "BEKK5"=c(bekk_5[1:4],rep(NA,6),bekk_5[5:6],rep(NA,6),bekk_5[7:14]),
                          "BEKK6"=c(bekk_6[1:4],rep(NA,6),bekk_6[5:6],rep(NA,6),bekk_6[7:14]),
                         "BEKK7" = bekk_7,
                         "BEKK8" = c(bekk_8[1:4],rep(NA,6),bekk_8[5:6],rep(NA,6),bekk_8[7:14]))

In [75]:
weekly_bekk

Parameters BEKKC            BEKK1            BEKK2           
1  mu10       0.0013 (0.0013)  0.0015 (0.0013)  0.0014 (0.0013) 
2  mu20       0.0019 (0.0012)  -3e-04 (4e-04)   -6e-04 (5e-04)  
3  phi11      -0.1553 (0.0782) 0.0458 (0.0364)  0.0555 (0.0361) 
4  phi12      0.2479 (0.0881)  -0.0372 (0.1096) -0.138 (0.1019) 
5  phi13      NA               NA               NA              
6  phi14      NA               NA               NA              
7  phi15      NA               NA               NA              
8  phi16      NA               NA               NA              
9  phi17      NA               NA               NA              
10 phi18      NA               NA               NA              
11 phi21      -0.073 (0.07)    -0.0072 (0.0118) 0.0137 (0.0124) 
12 phi22      0.1581 (0.0788)  -0.0028 (0.0355) -0.0439 (0.0351)
13 phi23      NA               NA               NA              
14 phi24      NA               NA               NA              
15 phi25      NA               NA               NA              
16 phi26      NA               NA               NA              
17 phi27      NA               NA               NA              
18 phi28      NA               NA               NA              
19 a11        0.0284 (0.0566)  0.3036 (0.0271)  0.301 (0.02)    
20 a12        -0.1379 (0.0503) -0.0082 (0.0105) -0.0032 (0.0095)
21 a21        0.2969 (0.0525)  0.0358 (0.0885)  -0.0207 (0.0824)
22 a22        0.4491 (0.0519)  0.2781 (0.0284)  0.3062 (0.0258) 
23 g11        0.9614 (0.0221)  0.9338 (0.0166)  0.9459 (0.0104) 
24 g12        -0.0194 (0.0204) 0.0071 (0.0054)  0.0029 (0.0041) 
25 g21        -0.0171 (0.0206) 0.0016 (0.0483)  -0.062 (0.0399) 
26 g22        0.9636 (0.0188)  0.9435 (0.0126)  0.9314 (0.0116) 
   BEKK3            BEKK4            BEKK5            BEKK6           
1  0.0015 (0.0013)  0.0019 (0.0012)  0.0019 (0.0012)  0.0019 (0.0012) 
2  3e-04 (5e-04)    6e-04 (5e-04)    3e-04 (4e-04)    0.001 (5e-04)   
3  0.0565 (0.0353)  0.0827 (0.0349)  0.0824 (0.0353)  0.0864 (0.035)  
4  -0.1863 (0.0917) 0.0804 (0.0875)  0.0347 (0.1027)  -0.0576 (0.0798)
5  NA               NA               NA               NA              
6  NA               NA               NA               NA              
7  NA               NA               NA               NA              
8  NA               NA               NA               NA              
9  NA               NA               NA               NA              
10 NA               NA               NA               NA              
11 -0.0029 (0.0133) -0.0171 (0.0135) -0.0196 (0.0117) -0.0183 (0.0149)
12 -0.0595 (0.0345) -0.0324 (0.0338) -0.0316 (0.0342) -0.0374 (0.0339)
13 NA               NA               NA               NA              
14 NA               NA               NA               NA              
15 NA               NA               NA               NA              
16 NA               NA               NA               NA              
17 NA               NA               NA               NA              
18 NA               NA               NA               NA              
19 0.2691 (0.0253)  0.3015 (0.0234)  0.3104 (0.024)   0.3235 (0.0254) 
20 -0.0266 (0.0134) -2e-04 (0.0108)  -1e-04 (0.009)   -0.0228 (0.0193)
21 0.1832 (0.0858)  0.0622 (0.0658)  0.1017 (0.0732)  0.1553 (0.0735) 
22 0.4367 (0.0256)  0.3025 (0.0243)  0.2648 (0.0199)  0.2662 (0.0387) 
23 0.9523 (0.0131)  0.945 (0.0108)   0.9405 (0.0118)  0.9386 (0.0124) 
24 0.0147 (0.0076)  -0.0013 (0.0047) 9e-04 (0.004)    0.0051 (0.0097) 
25 -0.0473 (0.0553) 0.0359 (0.0348)  -0.0038 (0.0354) -0.055 (0.0709) 
26 0.8608 (0.0226)  0.9337 (0.012)   0.952 (0.0081)   0.8749 (0.0497) 
   BEKK7            BEKK8           
1  0.0016 (0.0014)  0.0021 (0.0012) 
2  -0.0032 (8e-04)  -0.0024 (9e-04) 
3  0.0445 (0.0349)  0.0837 (0.0348) 
4  0.0871 (0.059)   0.0814 (0.0438) 
5  -0.0163 (0.0349) NA              
6  -0.0456 (0.0591) NA              
7  -0.0137 (0.035)  NA              
8  -0.0738 (0.0591) NA             